USE [master]
GO
/****** Object:  Database [007BDCONTABILIDAD]    Script Date: 18/02/2023 19:40:28 ******/
CREATE DATABASE [007BDCONTABILIDAD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'007BDCONTABILIDAD_DAT1', FILENAME = N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\007BDCONTABILIDAD.mdf' , SIZE = 6848KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'007BDCONTABILIDAD_LOG1', FILENAME = N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\007BDCONTABILIDAD_1.ldf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
ALTER DATABASE [007BDCONTABILIDAD] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [007BDCONTABILIDAD].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [007BDCONTABILIDAD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET ARITHABORT OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET  MULTI_USER 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [007BDCONTABILIDAD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [007BDCONTABILIDAD] SET QUERY_STORE = OFF
GO
USE [007BDCONTABILIDAD]
GO
/****** Object:  User [usersql]    Script Date: 18/02/2023 19:40:29 ******/
CREATE USER [usersql] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[usersql]
GO
/****** Object:  User [user]    Script Date: 18/02/2023 19:40:29 ******/
CREATE USER [user] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[user]
GO
/****** Object:  User [sqlbackup]    Script Date: 18/02/2023 19:40:29 ******/
CREATE USER [sqlbackup] WITH DEFAULT_SCHEMA=[sqlbackup]
GO
/****** Object:  User [consulta]    Script Date: 18/02/2023 19:40:29 ******/
CREATE USER [consulta] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[consulta]
GO
ALTER ROLE [db_owner] ADD MEMBER [user]
GO
ALTER ROLE [db_owner] ADD MEMBER [consulta]
GO
/****** Object:  Schema [consulta]    Script Date: 18/02/2023 19:40:29 ******/
CREATE SCHEMA [consulta]
GO
/****** Object:  Schema [sqlbackup]    Script Date: 18/02/2023 19:40:29 ******/
CREATE SCHEMA [sqlbackup]
GO
/****** Object:  Schema [user]    Script Date: 18/02/2023 19:40:29 ******/
CREATE SCHEMA [user]
GO
/****** Object:  Schema [usersql]    Script Date: 18/02/2023 19:40:29 ******/
CREATE SCHEMA [usersql]
GO
/****** Object:  Table [dbo].[ADUANA]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADUANA](
	[ADUANA_CODIGO] [varchar](3) NULL,
	[ADUANA_DESCRIPCION] [varchar](80) NULL,
	[FIJO] [bit] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ANEXO]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ANEXO](
	[ANEX_CODIGO] [varchar](11) NOT NULL,
	[TIPOANEX_CODIGO] [varchar](2) NOT NULL,
	[ANEX_RUC] [varchar](11) NULL,
	[ANEX_DESCRIPCION] [varchar](100) NULL,
	[ANEX_REFERENCIA] [varchar](50) NULL,
	[ANEX_DIRECCION] [varchar](100) NULL,
	[ANEX_TELEFONO] [varchar](30) NULL,
	[ANEX_REPRESENTANTE] [varchar](50) NULL,
	[ANEX_GIRO] [varchar](50) NULL,
	[NRETENCION] [bit] NOT NULL,
	[ANEX_NOMBRE] [varchar](20) NULL,
	[ANEX_APE_PAT] [varchar](20) NULL,
	[ANEX_APE_MAT] [varchar](20) NULL,
	[TIPOPERSONA] [varchar](2) NULL,
	[TIPODOCUMENTO] [varchar](1) NULL,
	[DOCUMENTOIDENTIDAD] [varchar](15) NULL,
	[ANE_DETRACCION] [bit] NULL,
	[ANE_TASA_DETRACC] [numeric](16, 0) NULL,
	[COD_DETRAC] [varchar](5) NULL,
	[ANEX_NOMBRE_2] [varchar](20) NULL,
	[ANEX_NACIONALIDAD] [varchar](4) NULL,
	[ANEX_SEXO] [bit] NULL,
	[ANEX_GLOSA] [varchar](60) NULL,
	[TCL_CODIGO] [varchar](3) NULL,
 CONSTRAINT [PK_ANEXO] PRIMARY KEY CLUSTERED 
(
	[ANEX_CODIGO] ASC,
	[TIPOANEX_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ANEXO_CTA_GASTOS]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ANEXO_CTA_GASTOS](
	[TIPOANEXO] [varchar](2) NULL,
	[COD_ANEXO] [varchar](11) NULL,
	[CUENTA] [varchar](18) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ARTICULOS]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARTICULOS](
	[COD_ARTICULOS] [varchar](20) NOT NULL,
	[NOMBRE_ARTICULOS] [varchar](200) NOT NULL,
	[DESC_ARTICULOS] [varchar](200) NULL,
	[UNIDADMED_CODIGO] [varchar](2) NOT NULL,
	[COD_EXISTENCIA] [varchar](2) NULL,
	[UNIDMED_DESCRI] [varchar](10) NULL,
	[EXISTENCIA_DESCRI] [varchar](20) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BALANCE_COMPROBACION]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BALANCE_COMPROBACION](
	[BALCOMP_CODIGO] [varchar](2) NOT NULL,
	[BALCOMP_DESCRIPCION] [varchar](30) NULL,
	[BALCOMP_DEBE] [varchar](14) NULL,
	[BALCOMP_HABER] [varchar](14) NULL,
	[BALCOMP_SITUACION] [varchar](16) NULL,
	[BALCOMP_INDICADOR] [varchar](3) NULL,
 CONSTRAINT [PK_BALCOMP_CODIGO] PRIMARY KEY CLUSTERED 
(
	[BALCOMP_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BALANCE_GENERAL]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BALANCE_GENERAL](
	[BALGRAL_CODIGO] [varchar](2) NOT NULL,
	[BALGRAL_CODIGO1] [varchar](10) NULL,
	[BALGRAL_DESCRI1] [varchar](50) NULL,
	[BALGRAL_FORMUL1] [text] NULL,
	[BALGRAL_CODIGO2] [varchar](10) NULL,
	[BALGRAL_DESCRI2] [varchar](50) NULL,
	[BALGRAL_FORMUL2] [text] NULL,
	[OPTACT] [varchar](1) NULL,
 CONSTRAINT [PK_BALGRAL_CODIGO] PRIMARY KEY CLUSTERED 
(
	[BALGRAL_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BALANCE_GENERAL_2008]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BALANCE_GENERAL_2008](
	[BALGRAL_CODIGO] [varchar](2) NOT NULL,
	[BALGRAL_CODIGO1] [varchar](10) NULL,
	[BALGRAL_DESCRI1] [varchar](50) NULL,
	[BALGRAL_FORMUL1] [text] NULL,
	[BALGRAL_CODIGO2] [varchar](10) NULL,
	[BALGRAL_DESCRI2] [varchar](50) NULL,
	[BALGRAL_FORMUL2] [text] NULL,
	[IDGRUPO] [varchar](3) NULL,
	[OPTACT] [varchar](1) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BALANCE_GENERAL_CMSJ]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BALANCE_GENERAL_CMSJ](
	[BALGRAL_CODIGO] [varchar](2) NOT NULL,
	[BALGRAL_CODIGO1] [varchar](10) NULL,
	[BALGRAL_DESCRI1] [varchar](100) NULL,
	[BALGRAL_FORMUL1] [text] NULL,
	[BALGRAL_CODIGO2] [varchar](10) NULL,
	[BALGRAL_DESCRI2] [varchar](100) NULL,
	[BALGRAL_FORMUL2] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[BALGRAL_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BALANCE_GENERAL_EXT]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BALANCE_GENERAL_EXT](
	[BALGRAL_CODIGO] [nvarchar](2) NOT NULL,
	[BALGRAL_CODIGO1] [nvarchar](10) NULL,
	[BALGRAL_DESCRI1] [nvarchar](50) NULL,
	[BALGRAL_FORMUL1] [ntext] NULL,
	[BALGRAL_CODIGO2] [nvarchar](10) NULL,
	[BALGRAL_DESCRI2] [nvarchar](50) NULL,
	[BALGRAL_FORMUL2] [ntext] NULL,
PRIMARY KEY CLUSTERED 
(
	[BALGRAL_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BANCO]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BANCO](
	[BAN_CODIGO] [varchar](2) NOT NULL,
	[BAN_DESCRIPCION] [varchar](30) NULL,
	[FMCH] [varchar](2) NULL,
	[BAN_EQUIVALENTE] [varchar](2) NULL,
 CONSTRAINT [PK_BAN_CODIGO] PRIMARY KEY CLUSTERED 
(
	[BAN_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CAPITAL_CAB]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAPITAL_CAB](
	[PERIODO] [datetime] NULL,
	[CAPITAL_SOCIAL] [numeric](18, 2) NULL,
	[VALOR_NOMINAL] [numeric](18, 2) NULL,
	[NROACC_SUSC] [numeric](18, 2) NULL,
	[NROACC_PAGA] [numeric](18, 2) NULL,
	[NROACC_TOT] [numeric](18, 2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CAPITAL_DET]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAPITAL_DET](
	[PERIODO] [datetime] NULL,
	[TIPO_DOCUMENTO] [varchar](2) NULL,
	[NRO_DOCUMENTO] [varchar](15) NULL,
	[TIPO_PERSONA] [varchar](2) NULL,
	[RAZON_SOCIAL] [varchar](100) NULL,
	[APE_PAT] [varchar](20) NULL,
	[APE_MAT] [varchar](20) NULL,
	[NOMBRE] [varchar](40) NULL,
	[TIPO_ACCIONES] [varchar](30) NULL,
	[NROACC_ACC] [numeric](18, 2) NULL,
	[PORCPART_ACC] [numeric](18, 8) NULL,
	[CODIGO_ACC] [varchar](11) NULL,
	[NRO_REG] [varchar](10) NULL,
	[COD_TIPO_ACCIONES] [varchar](3) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CBM01$]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CBM01$](
	[CUENTA] [nvarchar](255) NULL,
	[DESCRIPCION] [nvarchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CENTRO_COSTOS]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CENTRO_COSTOS](
	[CENCOST_CODIGO] [varchar](10) NOT NULL,
	[CENCOST_DESCRIPCION] [varchar](30) NULL,
	[CENCOST_TRANSFERENCIA] [int] NULL,
 CONSTRAINT [PK_CENCOST_CODIGO] PRIMARY KEY CLUSTERED 
(
	[CENCOST_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CIERRE]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CIERRE](
	[CIERRE_CODIGO] [varchar](2) NOT NULL,
	[CIERRE_DESCRIPCION] [varchar](50) NULL,
	[CIERRE_COMPROBANTE] [varchar](6) NULL,
 CONSTRAINT [PK_CIERRE_CODIGO] PRIMARY KEY CLUSTERED 
(
	[CIERRE_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COA]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COA](
	[CO_C_PATH] [varchar](30) NULL,
	[CO_N_MONED] [numeric](20, 2) NULL,
	[CO_C_FILE1] [varchar](8) NULL,
	[CO_C_FILE2] [varchar](8) NULL,
	[CO_C_FILE3] [varchar](8) NULL,
	[CO_C_FILE4] [varchar](8) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COMPROBANTES]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPROBANTES](
	[COMP_INDICADOR] [varchar](1) NOT NULL,
	[PLANCTA_CODIGO] [varchar](18) NOT NULL,
	[TIPOMON_CODIGO] [varchar](2) NULL,
 CONSTRAINT [COMP_INDICADOR] PRIMARY KEY CLUSTERED 
(
	[COMP_INDICADOR] ASC,
	[PLANCTA_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONCEPTOS_GENERALES]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONCEPTOS_GENERALES](
	[CONCGRAL_CODIGO] [varchar](20) NOT NULL,
	[CONCGRAL_DESCRIPCION] [varchar](30) NULL,
	[CONCGRAL_TIPO] [varchar](1) NULL,
	[CONCGRAL_CONTEC] [varchar](50) NULL,
	[CONCGRAL_CONTEN] [numeric](20, 4) NULL,
	[CONCGRAL_CONTED] [datetime] NULL,
	[CONCGRAL_CONTEL] [bit] NOT NULL,
	[CONCGRAL_USO] [varchar](100) NULL,
	[CONCGRAL_MOD] [varchar](1) NULL,
 CONSTRAINT [PK_CONCGRAL_CODIGO] PRIMARY KEY CLUSTERED 
(
	[CONCGRAL_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONFIGURACION_0662]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIGURACION_0662](
	[COD_PLANCTA] [varchar](18) NULL,
	[COD_PDT] [varchar](4) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONFIGURACION_0664_PCGE]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIGURACION_0664_PCGE](
	[COD_PLANCTA] [varchar](18) NULL,
	[COD_PDT] [varchar](5) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONFIGURACION_0664_PCGR]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIGURACION_0664_PCGR](
	[COD_PLANCTA] [varchar](18) NULL,
	[COD_PDT] [varchar](5) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONFIGURACION_0668_PCGE]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIGURACION_0668_PCGE](
	[COD_PLANCTA] [varchar](18) NULL,
	[COD_PDT] [varchar](5) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONFIGURACION_0668_PCGR]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIGURACION_0668_PCGR](
	[COD_PLANCTA] [varchar](18) NULL,
	[COD_PDT] [varchar](5) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONFIGURACION_0670_PCGE]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONFIGURACION_0670_PCGE](
	[COD_PLANCTA] [varchar](18) NULL,
	[COD_PDT] [varchar](6) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONVERSION_MONEDA]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONVERSION_MONEDA](
	[COVMON_CODIGO] [varchar](3) NOT NULL,
	[COVMON_DESCRIPCION] [varchar](15) NULL,
 CONSTRAINT [PK_COVMON_CODIGO] PRIMARY KEY CLUSTERED 
(
	[COVMON_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COSTO_CLASE_9]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COSTO_CLASE_9](
	[CENCOST_CODIGO] [varchar](10) NULL,
	[COSTCLAS9_CARGO] [varchar](80) NULL,
	[COSTCLAS9_ABONO] [varchar](18) NULL,
	[COSTCLAS9_FACTOR] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COSTO_INV_VALOR]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COSTO_INV_VALOR](
	[CODIGO] [varchar](12) NULL,
	[DESCRIPCION] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COSTO_INV_VALOR_DET]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COSTO_INV_VALOR_DET](
	[CODIGO] [varchar](12) NULL,
	[ANNO] [varchar](4) NULL,
	[MONTO] [numeric](18, 2) NULL,
	[COD_PROCESO] [varchar](5) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COSTO_OBRAS]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COSTO_OBRAS](
	[COSTO_CODIGO] [varchar](10) NULL,
	[COSTO_DESCRIPCION] [varchar](30) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COSTOS]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COSTOS](
	[CONTADOR] [varchar](15) NULL,
	[D_TIPODOC] [varchar](1) NULL,
	[D_NUMDOC] [varchar](15) NULL,
	[PERIODO] [varchar](4) NULL,
	[TIPO_PER] [varchar](2) NULL,
	[TIPO_DOC] [varchar](1) NULL,
	[NUM_DOC] [varchar](15) NULL,
	[IMPORTE] [varchar](15) NULL,
	[AP_PATER] [varchar](20) NULL,
	[AP_MATER] [varchar](20) NULL,
	[NOMBRE1] [varchar](20) NULL,
	[NOMBRE2] [varchar](20) NULL,
	[RAZON_SOC] [varchar](40) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUENTA_BANCARIA]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUENTA_BANCARIA](
	[BAN_CODIGO] [varchar](2) NOT NULL,
	[CTABAN_CODIGO] [varchar](20) NOT NULL,
	[CTABAN_DESCRIPCION] [varchar](30) NULL,
	[CTABAN_CUENTA] [varchar](18) NULL,
	[TIPOMON_CODIGO] [varchar](2) NULL,
	[TIPDOC_CODIGO] [varchar](2) NULL,
	[CTABAN_NUM] [varchar](50) NULL,
 CONSTRAINT [BAN_CODIGO] PRIMARY KEY CLUSTERED 
(
	[BAN_CODIGO] ASC,
	[CTABAN_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUENTA_TELE_ANEXO]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUENTA_TELE_ANEXO](
	[ANEXO] [varchar](13) NULL,
	[BAN_CODIGO] [varchar](2) NULL,
	[CTABAN_CODIGO] [varchar](25) NULL,
	[MON_CODIGO] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DETALLE_CIERRE]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DETALLE_CIERRE](
	[CIERRE_CODIGO] [varchar](2) NULL,
	[DETCIERRE_SECUENCIA] [varchar](4) NULL,
	[TIPOCIER_CODIGO] [varchar](1) NULL,
	[DETCIERRE_CUENTA] [varchar](18) NULL,
	[DETCIERRE_TRANSFERENCIA] [varchar](18) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EGP_FUNCION_NATURALEZA]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EGP_FUNCION_NATURALEZA](
	[EGP_TIPO] [varchar](1) NOT NULL,
	[EGP_FN_SECUENCIA] [varchar](2) NOT NULL,
	[EGP_FN_CONCEPTO] [varchar](10) NULL,
	[EGP_FN_DESCRIPCION] [varchar](50) NULL,
	[EGP_FN_FORMULA] [text] NULL,
	[OPTACT] [varchar](1) NULL,
 CONSTRAINT [PK_EGP_TIPO] PRIMARY KEY CLUSTERED 
(
	[EGP_TIPO] ASC,
	[EGP_FN_SECUENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EGP_FUNCION_NATURALEZA_2008]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EGP_FUNCION_NATURALEZA_2008](
	[EGP_TIPO] [varchar](1) NOT NULL,
	[EGP_FN_SECUENCIA] [varchar](2) NOT NULL,
	[EGP_FN_CONCEPTO] [varchar](10) NULL,
	[EGP_FN_DESCRIPCION] [varchar](50) NULL,
	[EGP_FN_FORMULA] [text] NULL,
	[OPTACT] [varchar](1) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EGP_FUNCION_NATURALEZA_EXT]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EGP_FUNCION_NATURALEZA_EXT](
	[EGP_TIPO] [nvarchar](1) NOT NULL,
	[EGP_FN_SECUENCIA] [nvarchar](2) NOT NULL,
	[EGP_FN_CONCEPTO] [nvarchar](10) NULL,
	[EGP_FN_DESCRIPCION] [nvarchar](50) NULL,
	[EGP_FN_FORMULA] [ntext] NULL,
 CONSTRAINT [UN_EGP_FUNC_NAT_EXT] UNIQUE NONCLUSTERED 
(
	[EGP_TIPO] ASC,
	[EGP_FN_SECUENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EGP_TIPO]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EGP_TIPO](
	[EGP_TIPO] [varchar](1) NULL,
	[EGP_DESCRIPCION] [varchar](20) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EJERCICIO_CONTABLE]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EJERCICIO_CONTABLE](
	[EJECONT_ANO] [varchar](4) NULL,
	[EJECONT_CIERRE] [varchar](12) NULL,
	[EJECONT_INICIO] [datetime] NULL,
	[EJECONT_FINAL] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ENTIDAD_FINANCIERA]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ENTIDAD_FINANCIERA](
	[ENTFIN_CODIGO] [varchar](3) NULL,
	[ENTFIN_DESCRIPCION] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EQUIESTABLE]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EQUIESTABLE](
	[COD_INVENTA] [varchar](2) NULL,
	[COD_CONTAB] [varchar](4) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EQUIVART]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EQUIVART](
	[COD_ART] [varchar](20) NULL,
	[COD_ALMACEN] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EQUIVTIPOEXIST]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EQUIVTIPOEXIST](
	[COD_INVENTA] [varchar](2) NULL,
	[COD_CONTAB] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EQUIVTIPOPE]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EQUIVTIPOPE](
	[COD_INVENTA] [varchar](2) NULL,
	[COD_CONTAB] [varchar](2) NULL,
	[TIPOPE_INVENTA] [varchar](1) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EQUIVUM]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EQUIVUM](
	[COD_INVENTA] [varchar](6) NULL,
	[COD_CONTAB] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EST_COSTO_VNT_ANUAL]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EST_COSTO_VNT_ANUAL](
	[PERIODO] [datetime] NULL,
	[COSTO_INV_INI_PROD_TER] [numeric](18, 2) NULL,
	[COSTO_PRODUCC_PROD_TER] [numeric](18, 2) NULL,
	[COSTO_PROD_TER_DISP_VENTA] [numeric](18, 2) NULL,
	[COSTO_INV_FIN_PROD_TER] [numeric](18, 2) NULL,
	[AJUSTES_DIVERSOS] [numeric](18, 2) NULL,
	[COSTO_VENTA] [numeric](18, 2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ESTABLECIMIENTO]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESTABLECIMIENTO](
	[CODIGO] [varchar](5) NULL,
	[DESCRIPCION] [varchar](70) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ESTADO_RESULTADO_CMSJ]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESTADO_RESULTADO_CMSJ](
	[SECUENCIA] [varchar](2) NOT NULL,
	[CONCEPTO] [varchar](10) NULL,
	[DESCRIPCION] [varchar](100) NULL,
	[FORMULA] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[SECUENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EXISTENCIAS]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EXISTENCIAS](
	[COD_EXISTENCIA] [varchar](20) NULL,
	[TIPOEXIS_CODIGO] [varchar](2) NOT NULL,
	[DESC_EXISTENCIA] [varchar](100) NOT NULL,
	[UNIDADMED_CODIGO] [varchar](2) NOT NULL,
	[CANTIDAD] [numeric](18, 5) NULL,
	[COSTO_UNI_MN] [numeric](18, 5) NULL,
	[COSTO_TOT_MN] [numeric](18, 5) NULL,
	[COSTO_UNI_ME] [numeric](18, 5) NULL,
	[COSTO_TOT_ME] [numeric](18, 5) NULL,
	[PLANCTA_CODIGO] [varchar](18) NULL,
	[PERIODO] [varchar](4) NULL,
	[DES_UNIDMED] [varchar](10) NULL,
	[DES_TIPOEXIS] [varchar](20) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FORMATOS_REP]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FORMATOS_REP](
	[EGP_TIPO] [int] NULL,
	[EGP_FN_SECUENCIA] [varchar](2) NULL,
	[EGP_FN_CONCEPTO] [varchar](10) NULL,
	[EGP_FN_DESCRIPCION] [varchar](50) NULL,
	[EGP_FN_FORMULA] [varchar](3000) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FORMULA_RATIO]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FORMULA_RATIO](
	[TIPORATIO_CODIGO] [varchar](1) NOT NULL,
	[FRATIO_SECUENCIA] [varchar](2) NOT NULL,
	[FRATIO_CONCEPTO] [varchar](12) NULL,
	[FRATIO_DESCRIPCION] [varchar](50) NULL,
	[FRATIO_FORMULA] [text] NULL,
 CONSTRAINT [TIPORATIO_CODIGO] PRIMARY KEY CLUSTERED 
(
	[TIPORATIO_CODIGO] ASC,
	[FRATIO_SECUENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FORMULA_RATIO_2008]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FORMULA_RATIO_2008](
	[TIPORATIO_CODIGO] [varchar](1) NOT NULL,
	[FRATIO_SECUENCIA] [varchar](2) NOT NULL,
	[FRATIO_CONCEPTO] [varchar](12) NULL,
	[FRATIO_DESCRIPCION] [varchar](50) NULL,
	[FRATIO_FORMULA] [text] NULL,
	[TIPORATIO_COD] [varchar](2) NULL,
	[OPTACT] [varchar](1) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FORMULA_RATIO_EXT]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FORMULA_RATIO_EXT](
	[TIPORATIO_CODIGO] [nvarchar](1) NOT NULL,
	[FRATIO_SECUENCIA] [nvarchar](2) NOT NULL,
	[FRATIO_CONCEPTO] [nvarchar](12) NULL,
	[FRATIO_DESCRIPCION] [nvarchar](50) NULL,
	[FRATIO_FORMULA] [ntext] NULL,
 CONSTRAINT [UN_FORMULA_RATIO_EXT] UNIQUE NONCLUSTERED 
(
	[TIPORATIO_CODIGO] ASC,
	[FRATIO_SECUENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FORMULA_RATIO_PCGE]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FORMULA_RATIO_PCGE](
	[TIPORATIO_CODIGO] [varchar](1) NOT NULL,
	[FRATIO_SECUENCIA] [varchar](2) NOT NULL,
	[FRATIO_CONCEPTO] [varchar](12) NULL,
	[FRATIO_DESCRIPCION] [varchar](50) NULL,
	[FRATIO_FORMULA] [text] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GANACIAS_DIFERIDAS]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GANACIAS_DIFERIDAS](
	[CODIGO_GANDIF] [varchar](10) NULL,
	[CONCEPTO_GANDIF] [varchar](40) NULL,
	[SALFIN_GANDIF] [numeric](18, 2) NULL,
	[PERIODO] [varchar](4) NULL,
	[VOUCHER] [varchar](20) NULL,
	[TD] [varchar](2) NULL,
	[SERIE] [varchar](20) NULL,
	[NUMERO] [varchar](20) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GASTOS_INGRESOS]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GASTOS_INGRESOS](
	[GASING_CODIGO] [varchar](3) NULL,
	[GASING_DESCRIPCION] [varchar](30) NULL,
	[GASING_TIPO] [varchar](1) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IMP_MENSUALES]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IMP_MENSUALES](
	[CO_C_ANO] [varchar](4) NOT NULL,
	[CO_C_MES] [varchar](2) NOT NULL,
	[CO_N_CBSCF] [numeric](20, 2) NULL,
	[CO_N_CBNCF] [numeric](20, 2) NULL,
	[CO_N_CBNGR] [numeric](20, 2) NULL,
	[CO_N_CBMIX] [numeric](20, 2) NULL,
	[CO_N_CIMIX] [numeric](20, 2) NULL,
	[CO_N_CISCF] [numeric](20, 2) NULL,
	[CO_N_CINCF] [numeric](20, 2) NULL,
	[CO_N_CICPA] [numeric](20, 2) NULL,
	[CO_N_VBAFE] [numeric](20, 2) NULL,
	[CO_N_VBINA] [numeric](20, 2) NULL,
	[CO_N_VIGV] [numeric](20, 2) NULL,
	[CO_N_CREDI] [numeric](20, 2) NULL,
	[CO_N_IGV] [numeric](20, 2) NULL,
	[CO_L_CALCU] [bit] NOT NULL,
	[CO_N_IRBAS] [numeric](20, 2) NULL,
	[CO_N_IRMTO] [numeric](20, 2) NULL,
	[CO_C_IRMET] [varchar](1) NULL,
	[CO_N_IRFAC] [numeric](20, 4) NULL,
	[CO_L_IRCAL] [bit] NOT NULL,
	[CO_N_ANBAS] [numeric](20, 2) NULL,
	[CO_N_ANMTO] [numeric](20, 2) NULL,
	[CO_C_ANMAJ] [varchar](2) NULL,
	[CO_N_ANCUO] [numeric](20, 2) NULL,
	[CO_N_ANFAJ] [numeric](20, 2) NULL,
	[CO_N_ANFAC] [numeric](20, 2) NULL,
	[CO_L_ANCAL] [bit] NOT NULL,
	[II_N_CBSCF] [numeric](20, 2) NULL,
	[II_N_CBNCF] [numeric](20, 2) NULL,
	[II_N_CBNGR] [numeric](20, 2) NULL,
	[II_N_CISCF] [numeric](20, 2) NULL,
	[II_N_CBMIX] [numeric](20, 2) NULL,
	[II_N_CIMIX] [numeric](20, 2) NULL,
 CONSTRAINT [CO_C_ANO] PRIMARY KEY CLUSTERED 
(
	[CO_C_ANO] ASC,
	[CO_C_MES] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IMPTO_A_LA_RENTA]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IMPTO_A_LA_RENTA](
	[CO_C_TIPO] [varchar](1) NULL,
	[CO_C_SECUE] [varchar](3) NULL,
	[CO_C_SIGNO] [varchar](1) NULL,
	[CO_A_MOTIV] [varchar](50) NULL,
	[CO_A_FORMU] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INTANGIBLES]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INTANGIBLES](
	[CODIGO_INTANGIBLE] [varchar](12) NULL,
	[DESC_INTANGIBLE] [varchar](40) NULL,
	[TIPOINT_CODIGO] [varchar](2) NOT NULL,
	[FECINIOPE] [datetime] NULL,
	[VALCONTINT] [numeric](18, 2) NULL,
	[AMOCONTACU] [numeric](18, 2) NULL,
	[VALNETCONTINT] [numeric](18, 2) NULL,
	[VOUCHER] [varchar](20) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IPM]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IPM](
	[CO_C_ANO] [varchar](4) NULL,
	[CO_C_MES] [varchar](2) NULL,
	[CO_N_FACTO] [numeric](20, 2) NULL,
	[CO_N_IPM] [numeric](20, 2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LIBRO_REGISTRO]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LIBRO_REGISTRO](
	[LIBREG_CODIGO] [varchar](3) NULL,
	[LIBREG_DESCRIPCION] [varchar](80) NULL,
	[FIJO] [bit] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAEINVENTARIO]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAEINVENTARIO](
	[NRO_TRANSACCION] [varchar](20) NOT NULL,
	[COD_ARTICULOS] [varchar](50) NOT NULL,
	[TIPO_MOVIMIENTO] [char](2) NOT NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[TIPO_DOCUMENTO] [varchar](2) NOT NULL,
	[SERIE_DOCUMENTO] [varchar](4) NULL,
	[NUMERO_DOCUMENTO] [varchar](23) NULL,
	[TIPOOPER_CODIGO] [varchar](11) NOT NULL,
	[CANTIDAD_ENTRADA] [numeric](28, 6) NULL,
	[CANTIDAD_SALIDA] [numeric](28, 6) NULL,
	[COSTO_UNITARIO_ENT] [numeric](28, 6) NULL,
	[COSTO_UNITARIO_SAL] [numeric](28, 6) NULL,
	[COSTO_TOTAL_ENT] [numeric](28, 6) NULL,
	[COSTO_TOTAL_SAL] [numeric](28, 6) NULL,
	[CANTIDAD_FINAL] [numeric](18, 6) NULL,
	[COSTO_UNITARIO_FINAL] [numeric](18, 6) NULL,
	[COSTO_TOTAL_FINAL] [numeric](18, 6) NULL,
	[TIPOOPER_DESCRI] [varchar](20) NULL,
	[ESTABLECIMIENTO] [varchar](5) NULL,
	[ALMA_INV] [varchar](2) NULL,
	[TD_INV] [varchar](2) NULL,
	[NUMDOC_INV] [varchar](10) NULL,
	[TIPDOC_DESCRIPCION] [varchar](20) NULL,
	[ITEM_INV] [int] NULL,
	[CODMOV_INV] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MANT_ACTIVO_DETALLE]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MANT_ACTIVO_DETALLE](
	[CODIGO] [varchar](12) NULL,
	[ANNO] [varchar](4) NULL,
	[ACT_SALDO_INICIAL] [numeric](18, 2) NULL,
	[ACT_ADQUISICIONES] [numeric](18, 2) NULL,
	[ACT_MEJORAS] [numeric](18, 2) NULL,
	[ACT_RETIROS_BAJAS] [numeric](18, 2) NULL,
	[ACT_OTROS_AJUSTES] [numeric](18, 2) NULL,
	[ACT_AJUSTE_INFLACION] [numeric](18, 2) NULL,
	[DEP_METODO_APLICADO] [varchar](20) NULL,
	[DEP_NRO_DOCUMENTO] [varchar](23) NULL,
	[DEP_PORCENTAJE] [numeric](10, 6) NULL,
	[DEP_ACUMULADA_EJER_ANT] [numeric](18, 2) NULL,
	[DEP_EJRCICIO] [numeric](18, 2) NULL,
	[DEP_EJERCICIO_RETIROS] [numeric](18, 2) NULL,
	[DEP_OTROS_AJUSTES] [numeric](18, 2) NULL,
	[DEP_AJUSTE_INFLACION] [numeric](18, 2) NULL,
	[DIF_AJUSTE_DIF_CAMBIO] [numeric](18, 2) NULL,
	[DIF_VALOR_MN] [numeric](18, 2) NULL,
	[DIF_DEP_EJERCICIO] [numeric](18, 2) NULL,
	[DIF_DEP_RETIROS_BAJAS] [numeric](18, 2) NULL,
	[DIF_DEP_OTROS_AJUSTE] [numeric](18, 2) NULL,
	[TIPO_CAMBIO_ACTIVO] [numeric](10, 6) NULL,
	[GRUPO] [varchar](5) NULL,
	[DEP_METODO_APLICADO_PLE] [varchar](5) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MANT_ACTIVOFIJO_2008]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MANT_ACTIVOFIJO_2008](
	[CODIGO] [varchar](12) NULL,
	[CUENTA_CONTABLE] [varchar](18) NULL,
	[DESCRIPCION] [varchar](40) NULL,
	[MARCA] [varchar](20) NULL,
	[MODELO] [varchar](20) NULL,
	[NRO_SERIE] [varchar](20) NULL,
	[FECHA_ADQUISICION] [smalldatetime] NULL,
	[FECHA_INICIO] [smalldatetime] NULL,
	[VALOR_ADQUISICION_ME] [numeric](18, 2) NULL,
	[TIPO_CAMBIO_ADQUISICION] [numeric](10, 6) NULL,
	[VALOR_ADQUISICION_MN] [numeric](18, 2) NULL,
	[TIPO_MONEDA] [varchar](2) NULL,
	[GRUPO] [varchar](5) NULL,
	[COD_TIPO] [varchar](1) NULL,
	[ESTADO_ACTIVO] [varchar](1) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MANT_ACTIVOS_REVALUADOS]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MANT_ACTIVOS_REVALUADOS](
	[CODIGO] [varchar](12) NULL,
	[ANNO] [varchar](4) NULL,
	[ACT_SALDO_INI] [numeric](18, 2) NULL,
	[ACT_ADQ_ADICIONES] [numeric](18, 2) NULL,
	[ACT_MEJORAS] [numeric](18, 2) NULL,
	[ACT_RETIROS_BAJAS] [numeric](18, 2) NULL,
	[ACT_OTROS_AJUSTES] [numeric](18, 2) NULL,
	[ACT_VOLUNTARIA] [numeric](18, 2) NULL,
	[ACT_REORG_SOCIEDADES] [numeric](18, 2) NULL,
	[ACT_OTROS] [numeric](18, 2) NULL,
	[ACT_AJUSTE_INFLACION] [numeric](18, 2) NULL,
	[DEP_METODO_APLICADO] [varchar](20) NULL,
	[DEP_NRO_DOCUMENTO] [varchar](23) NULL,
	[DEP_PORCENTAJE] [numeric](10, 6) NULL,
	[DEP_ACUM_CIERRE_EJER_ANT] [numeric](18, 2) NULL,
	[DEP_EJER_SIN_CONSIDERAR] [numeric](18, 2) NULL,
	[DEP_RELACIONADA_RETIROS] [numeric](18, 2) NULL,
	[DEP_REL_OTROS_AJUSTE] [numeric](18, 2) NULL,
	[DEP_VOLUNTARIA] [numeric](18, 2) NULL,
	[DEP_REORG_SOCIEDAD] [numeric](18, 2) NULL,
	[DEP_OTROS] [numeric](18, 2) NULL,
	[DEP_AJUSTE_INFLACION] [numeric](18, 2) NULL,
	[GRUPO] [varchar](5) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MANT_ARRENDAMIENTO_FINANCIERO]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MANT_ARRENDAMIENTO_FINANCIERO](
	[ANNO] [varchar](4) NULL,
	[FECHA_CONTRATO] [smalldatetime] NULL,
	[NRO_CONTRATO] [varchar](30) NULL,
	[FECHA_INICIO_ARREND] [smalldatetime] NULL,
	[NRO_CUOTAS_PACTADAS] [numeric](18, 2) NULL,
	[MONTO_TOTAL_CONTRATO] [numeric](18, 2) NULL,
	[CODIGO] [varchar](12) NULL,
	[GRUPO] [varchar](5) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MANT_PROCESOS_COSTOS]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MANT_PROCESOS_COSTOS](
	[CODIGO] [varchar](5) NULL,
	[DESCRIPCION] [varchar](50) NULL,
	[COD_AGRUPA] [varchar](1) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MANTREPCTASXPAG]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MANTREPCTASXPAG](
	[PLANCTA_CODIGO] [varchar](18) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MESES]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MESES](
	[COD_MES] [varchar](2) NOT NULL,
	[DES_MES] [varchar](15) NOT NULL,
 CONSTRAINT [PK_COD_MES] PRIMARY KEY CLUSTERED 
(
	[COD_MES] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MONEDA]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MONEDA](
	[MONEDA_CODIGO] [varchar](1) NULL,
	[MONEDA_DESCRIPCION] [varchar](20) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MOVCONSIGNACIONES]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MOVCONSIGNACIONES](
	[NRO_TRANSACCION] [varchar](15) NULL,
	[COD_ARTICULOS] [varchar](20) NULL,
	[TIPO_MOVIMIENTO] [char](2) NOT NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[TIPO_DOCUMENTO] [varchar](2) NOT NULL,
	[SERIE_DOCUMENTO] [varchar](20) NULL,
	[NUMERO_DOCUMENTO] [varchar](23) NULL,
	[FECHA_ENTDEV] [datetime] NULL,
	[TIPOANEX_CODIGO] [varchar](2) NOT NULL,
	[ANEX_CODIGO] [varchar](11) NOT NULL,
	[CANTIDAD_ENTREGADA] [numeric](18, 6) NULL,
	[CANTIDAD_DEVUELTA] [numeric](18, 6) NULL,
	[CANTIDAD_VENDIDA] [numeric](18, 6) NULL,
	[SERIE_GUIA] [varchar](4) NULL,
	[NUMERO_GUIA] [varchar](21) NULL,
	[FECHA_DOCUMENTO] [smalldatetime] NULL,
	[FECHA_GUIA] [smalldatetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MOVCONSIGNATARIO]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MOVCONSIGNATARIO](
	[NRO_TRANSACCION] [varchar](15) NULL,
	[COD_ARTICULOS] [varchar](20) NULL,
	[TIPO_MOVIMIENTO] [char](2) NOT NULL,
	[FECHA_REGISTRO] [datetime] NOT NULL,
	[TIPO_DOCUMENTO] [varchar](2) NOT NULL,
	[SERIE_DOCUMENTO] [varchar](20) NULL,
	[NUMERO_DOCUMENTO] [varchar](23) NULL,
	[FECHA_ENTDEV] [datetime] NULL,
	[TIPOANEX_CODIGO] [varchar](2) NOT NULL,
	[ANEX_CODIGO] [varchar](11) NOT NULL,
	[CANTIDAD_ENTREGADA] [numeric](18, 6) NULL,
	[CANTIDAD_DEVUELTA] [numeric](18, 6) NULL,
	[CANTIDAD_VENDIDA] [numeric](18, 6) NULL,
	[SERIE_GUIA] [varchar](4) NULL,
	[NUMERO_GUIA] [varchar](21) NULL,
	[FECHA_DOCUMENTO] [smalldatetime] NULL,
	[FECHA_GUIA] [smalldatetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NIVEL_PLAN_EXT]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NIVEL_PLAN_EXT](
	[NIVEL] [int] NULL,
	[NIV01] [int] NULL,
	[NIV02] [int] NULL,
	[NIV03] [int] NULL,
	[NIV04] [int] NULL,
	[NIV05] [int] NULL,
	[NIV06] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARAMETROS]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARAMETROS](
	[VER_COMPVENT_INAFECTO] [bit] NULL,
	[VER_FECHA_EXTRACTO] [bit] NULL,
	[VER_RANGODIA_REGVTACOMP] [bit] NULL,
	[OSITRAN] [varchar](30) NULL,
	[VER_AUTO_GLOSA_COM] [bit] NULL,
	[VER_AUTO_RUC_COM] [bit] NULL,
	[VER_SUBDI_USU] [bit] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARTIDA_PRESUPUESTAL]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTIDA_PRESUPUESTAL](
	[PARTPRES_CODIGO] [varchar](4) NULL,
	[PARTPRES_DESCRIPCION] [varchar](40) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PLAN_CONFIGURACION]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLAN_CONFIGURACION](
	[COD_EMPRESA_DES] [varchar](18) NULL,
	[COD_EMPRESA_ORIG] [varchar](18) NULL,
	[ANIO] [varchar](4) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PLAN_CUENTA_DET_AUTO]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLAN_CUENTA_DET_AUTO](
	[PLANCTA_CODIGO] [varchar](18) NULL,
	[PLANCTA_CARGO] [varchar](18) NULL,
	[PLANCTA_ABONO] [varchar](18) NULL,
	[PLANCTA_PORCENT] [int] NULL,
	[ORDEN] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PLAN_CUENTA_EXTERIOR]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLAN_CUENTA_EXTERIOR](
	[CTAEX_CODIGO] [varchar](18) NULL,
	[CTAEX_DESCRIPCION] [varchar](50) NULL,
	[CTAEX_TIPO] [varchar](1) NULL,
	[CTAEX_NIVEL] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PLAN_CUENTA_NACIONAL]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLAN_CUENTA_NACIONAL](
	[PLANCTA_CODIGO] [varchar](18) NOT NULL,
	[PLANCTA_DESCRIPCION] [varchar](100) NULL,
	[PLANCTA_NIVEL] [smallint] NULL,
	[TIPOANEX_CODIGO] [varchar](2) NULL,
	[PLANCTA_CENTCOST] [bit] NOT NULL,
	[TIPOCTA_CODIGO] [varchar](2) NULL,
	[PLANCTA_AUTO] [bit] NOT NULL,
	[PLANCTA_CARGO1] [varchar](18) NULL,
	[PLANCTA_CARGO2] [varchar](18) NULL,
	[PLANCTA_CARGO3] [varchar](18) NULL,
	[PLANCTA_ABONO1] [varchar](18) NULL,
	[PLANCTA_ABONO2] [varchar](18) NULL,
	[PLANCTA_ABONO3] [varchar](18) NULL,
	[PLANCTA_PORCENT1] [int] NULL,
	[PLANCTA_PORCENT2] [int] NULL,
	[PLANCTA_PORCENT3] [int] NULL,
	[PLANCTA_AJUSTE] [bit] NOT NULL,
	[PLANCTA_PARTIDA] [varchar](4) NULL,
	[PLANCTA_DIF_CAMBIO] [varchar](3) NULL,
	[PLANCTA_MONETARIA] [bit] NOT NULL,
	[PLANCTA_CON_COSTO] [varchar](3) NULL,
	[PLANCTA_PLAN_EXTERIOR] [varchar](18) NULL,
	[PLANCTA_ESTADO] [varchar](1) NULL,
	[PLANCTA_COSTO_OBRA] [varchar](10) NULL,
	[PLANCTA_CODIGO_DES] [varchar](18) NULL,
	[ESituacion] [varchar](15) NOT NULL,
	[EResultado] [varchar](15) NOT NULL,
	[EPatrimonio] [varchar](15) NOT NULL,
	[TSituacion] [varchar](15) NOT NULL,
	[TResultado] [varchar](15) NOT NULL,
	[TPatrimonio] [varchar](15) NOT NULL,
	[CSituacion] [varchar](15) NOT NULL,
	[CResultado] [varchar](15) NOT NULL,
	[CPatrimonio] [varchar](15) NOT NULL,
 CONSTRAINT [PK_PLANCTA_CODIGO] PRIMARY KEY CLUSTERED 
(
	[PLANCTA_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRESUPUESTO_CCOSTO]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRESUPUESTO_CCOSTO](
	[PRESU_CECOS] [varchar](10) NULL,
	[GASING_CODIGO] [varchar](3) NULL,
	[PRESU_ANOIN] [varchar](7) NULL,
	[PRESU_ANOFI] [varchar](7) NULL,
	[PRESU_MOPMN] [numeric](20, 2) NULL,
	[PRESU_MOPME] [numeric](20, 2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REPORTES]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPORTES](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](60) NULL,
	[DESCRI] [varchar](1000) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RESULTADOS_ANUALES]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESULTADOS_ANUALES](
	[CO_C_ANO] [varchar](4) NULL,
	[CO_N_INGAN] [numeric](20, 2) NULL,
	[CO_N_INGIM] [numeric](20, 2) NULL,
	[CO_N_IMPRE] [numeric](20, 2) NULL,
	[CO_N_RESUL] [numeric](20, 2) NULL,
	[CO_N_PAGIR] [numeric](20, 2) NULL,
	[CO_N_ACTNE] [numeric](20, 2) NULL,
	[CO_L_CALCU] [bit] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUBD_USU]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUBD_USU](
	[SUBDIAR_CODIGO] [varchar](2) NULL,
	[USU_CODIGO] [varchar](8) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUBDIARIOS]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUBDIARIOS](
	[SUBDIAR_CODIGO] [varchar](2) NOT NULL,
	[SUBDIAR_DESCRIPCION] [varchar](30) NULL,
	[SUBDIAR_BREVE] [varchar](3) NULL,
	[SUBDIAR_AUTOM] [bit] NOT NULL,
	[SUBDIAR_EQUIVALENTE] [varchar](2) NULL,
 CONSTRAINT [PK_SUBDIAR_CODIGO] PRIMARY KEY CLUSTERED 
(
	[SUBDIAR_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_TIPO_CLIENTE]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_TIPO_CLIENTE](
	[TCL_CODIGO] [varchar](3) NOT NULL,
	[TCL_DESCRIPCION] [varchar](25) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TABLA_CTA_COMPROB_CV]    Script Date: 18/02/2023 19:40:29 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TABLA_CTA_COMPROB_CV](
	[TABLCOMPR_INDIC] [varchar](1) NULL,
	[TABLCOMPR_CUENT] [varchar](18) NULL,
	[TABLCOMPR_MONED] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TABLA_CTAAJUSTE]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TABLA_CTAAJUSTE](
	[TABLCTAAJU_CUENT] [varchar](18) NULL,
	[TABLCTAAJU_AJUST] [varchar](18) NULL,
	[TABLCTAAJU_FLUCT] [varchar](18) NULL,
	[TABLCTAAJU_METAJ] [varchar](1) NULL,
	[TABLCTAAJU_TIPFA] [varchar](1) NULL,
	[TABLCTAAJU_RELAC] [varchar](18) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TABLA_ESTRUCCOSTOS]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TABLA_ESTRUCCOSTOS](
	[TABL_ESTRUCCOS_CUENT] [varchar](18) NULL,
	[TABL_ESTRUCCOS_SECUE] [varchar](2) NULL,
	[TABL_ESTRUCCOS_CODIG] [varchar](18) NULL,
	[TABL_ESTRUCCOS_DESCR] [varchar](40) NULL,
	[TABL_ESTRUCCOS_FACTO] [numeric](20, 2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TABLA_IPM]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TABLA_IPM](
	[TABLIPM_ANO] [varchar](4) NULL,
	[TABLIPM_MES] [varchar](2) NULL,
	[TABLIPM_FACTO] [numeric](20, 2) NULL,
	[TABLIPM_IPM] [numeric](20, 2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TASA_MIXTO]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TASA_MIXTO](
	[ANNO] [varchar](4) NULL,
	[MES] [varchar](2) NULL,
	[TASA] [numeric](10, 4) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPCAM_CIERRE]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPCAM_CIERRE](
	[PERIODO] [varchar](6) NULL,
	[TC_COMP] [decimal](20, 3) NULL,
	[TC_VTA] [decimal](20, 3) NULL,
	[TC_EQUICOMP] [decimal](20, 6) NULL,
	[TC_EQUIVTA] [decimal](20, 6) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPCAM_CIERRE_]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPCAM_CIERRE_](
	[PERIODO] [varchar](6) NULL,
	[TC_COMP] [numeric](20, 3) NULL,
	[TC_VTA] [numeric](20, 3) NULL,
	[TC_EQUICOMP] [numeric](20, 6) NULL,
	[TC_EQUIVTA] [numeric](20, 6) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_ACCIONES]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_ACCIONES](
	[CODIGO] [varchar](20) NULL,
	[DESCRIPCION] [varchar](40) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_ANEXO]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_ANEXO](
	[TIPOANEX_CODIGO] [varchar](2) NOT NULL,
	[TIPOANEX_DESCRIPCION] [varchar](30) NULL,
 CONSTRAINT [PK_TIPOANEX_CODIGO] PRIMARY KEY CLUSTERED 
(
	[TIPOANEX_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_CAMBIO]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_CAMBIO](
	[TIPOMON_CODIGO] [varchar](2) NULL,
	[TIPOCAMB_FECHA] [datetime] NULL,
	[TIPOCAMB_COMPRA] [decimal](20, 3) NULL,
	[TIPOCAMB_EQCOMPRA] [decimal](20, 6) NULL,
	[TIPOCAMB_VENTA] [decimal](20, 3) NULL,
	[TIPOCAMB_EQVENTA] [decimal](20, 6) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_CAMBIO_]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_CAMBIO_](
	[TIPOMON_CODIGO] [varchar](2) NULL,
	[TIPOCAMB_FECHA] [datetime] NULL,
	[TIPOCAMB_COMPRA] [numeric](20, 3) NULL,
	[TIPOCAMB_EQCOMPRA] [numeric](20, 6) NULL,
	[TIPOCAMB_VENTA] [numeric](20, 3) NULL,
	[TIPOCAMB_EQVENTA] [numeric](20, 6) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_CAMBIO_MES_CMSJ]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_CAMBIO_MES_CMSJ](
	[ANNOMES] [varchar](6) NOT NULL,
	[VALOR] [decimal](15, 3) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_CAMBIO_MES_CMSJ_]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_CAMBIO_MES_CMSJ_](
	[ANNOMES] [varchar](6) NOT NULL,
	[VALOR] [numeric](15, 3) NULL,
PRIMARY KEY CLUSTERED 
(
	[ANNOMES] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_CIERRE]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_CIERRE](
	[TIPOCIER_CODIGO] [varchar](1) NULL,
	[TIPOCIER_DESCRIPCION] [varchar](20) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_CONSUMO_PRODUCCION]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_CONSUMO_PRODUCCION](
	[NIVEL] [varchar](7) NULL,
	[CODIGO_TCP] [varchar](12) NULL,
	[DESCRIPCION_TCP] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_CONSUMO_PRODUCCION_DET]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_CONSUMO_PRODUCCION_DET](
	[CODIGO_TCP] [varchar](5) NULL,
	[NIVEL] [varchar](7) NULL,
	[ANNO] [varchar](4) NULL,
	[MONTO_01] [numeric](18, 2) NULL,
	[MONTO_02] [numeric](18, 2) NULL,
	[MONTO_03] [numeric](18, 2) NULL,
	[MONTO_04] [numeric](18, 2) NULL,
	[MONTO_05] [numeric](18, 2) NULL,
	[MONTO_06] [numeric](18, 2) NULL,
	[MONTO_07] [numeric](18, 2) NULL,
	[MONTO_08] [numeric](18, 2) NULL,
	[MONTO_09] [numeric](18, 2) NULL,
	[MONTO_10] [numeric](18, 2) NULL,
	[MONTO_11] [numeric](18, 2) NULL,
	[MONTO_12] [numeric](18, 2) NULL,
	[COD_PROCESO] [varchar](5) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_CUENTA]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_CUENTA](
	[TIPOCTA_CODIGO] [varchar](2) NULL,
	[TIPOCTA_DESCRIPCION] [varchar](25) NULL,
	[TIPOCTA_ABREVIATURA] [varchar](3) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_EXISTENCIA]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_EXISTENCIA](
	[TIPOEXIS_CODIGO] [varchar](2) NULL,
	[TIPOEXIS_DESCRIPCION] [varchar](80) NULL,
	[FIJO] [bit] NULL,
	[EQUIV_EXIS_INV] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_INTANGIBLE]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_INTANGIBLE](
	[TIPOINT_CODIGO] [varchar](2) NULL,
	[TIPOINT_DESCRIPCION] [varchar](80) NULL,
	[FIJO] [bit] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_MEDIO_PAGO]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_MEDIO_PAGO](
	[TIPOMEDIO_CODIGO] [varchar](3) NULL,
	[TIPOMEDIO_DESCRIPCION] [varchar](80) NULL,
	[FIJO] [bit] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_MONEDA]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_MONEDA](
	[TIPOMON_CODIGO] [varchar](2) NOT NULL,
	[TIPOMON_DESCRIPCION] [varchar](20) NULL,
	[TIPOMON_NACIONALIDAD] [bit] NOT NULL,
	[TIPOMON_SIMBOLO] [varchar](2) NULL,
	[TIPOMON_EQUIVALENTE] [varchar](1) NULL,
 CONSTRAINT [PK_TIPOMON_CODIGO] PRIMARY KEY CLUSTERED 
(
	[TIPOMON_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_OPERACION]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_OPERACION](
	[TIPOOPER_CODIGO] [varchar](2) NULL,
	[TIPOOPER_DESCRIPCION] [varchar](80) NULL,
	[FIJO] [bit] NULL,
	[EQUIV_OPER_INV] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_RATIO]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_RATIO](
	[TIPORATIO_CODIGO] [varchar](1) NOT NULL,
	[TIPORATIO_DESCRIPCION] [varchar](50) NULL,
 CONSTRAINT [PK_TIPORATIO_CODIGO] PRIMARY KEY CLUSTERED 
(
	[TIPORATIO_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPOS_DE_DOCUMENTOS]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPOS_DE_DOCUMENTOS](
	[TIPDOC_CODIGO] [varchar](2) NOT NULL,
	[TIPDOC_DESCRIPCION] [varchar](25) NULL,
	[TIPDOC_SUNAT] [varchar](2) NULL,
	[TIPDOC_RESTA] [bit] NOT NULL,
	[TIPDOC_REFERENCIA] [bit] NOT NULL,
	[TIPDOC_FILE] [varchar](8) NULL,
	[TIPDOC_FECHAVTO] [bit] NOT NULL,
	[TIPO_EQUI] [varchar](3) NULL,
	[TIPDOC_FECHAVTO_VTA] [bit] NULL,
 CONSTRAINT [PK_TIPDOC_CODIGO] PRIMARY KEY CLUSTERED 
(
	[TIPDOC_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UNIDAD_MEDIDA]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UNIDAD_MEDIDA](
	[UNIDADMED_CODIGO] [varchar](2) NULL,
	[UNIDADMED_DESCRIPCION] [varchar](80) NULL,
	[FIJO] [bit] NULL,
	[EQUIV_INV] [varchar](6) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VALORES]    Script Date: 18/02/2023 19:40:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VALORES](
	[TIPO_DOCUMENTO] [varchar](1) NULL,
	[NRO_DOCUMENTO] [varchar](15) NULL,
	[TIPO_PERSONA] [varchar](2) NOT NULL,
	[RAZON_SOCIAL] [varchar](60) NULL,
	[APE_PAT] [varchar](20) NULL,
	[APE_MAT] [varchar](20) NULL,
	[NOMBRE] [varchar](20) NULL,
	[DENOMINACION] [varchar](2) NULL,
	[VAL_NOM_UNITARIO] [numeric](18, 2) NULL,
	[CANTIDAD] [numeric](18, 2) NULL,
	[COSTO_TOTAL] [numeric](18, 2) NULL,
	[PROV_TOTAL] [numeric](18, 2) NULL,
	[TOTAL_NETO] [numeric](18, 2) NULL,
	[PERIODO] [varchar](4) NULL,
	[VOUCHER] [varchar](20) NULL,
	[NOMBRE2] [varchar](20) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ANEXO] ADD  CONSTRAINT [DF__ANEXO__NRETENCIO__77BFCB91]  DEFAULT (0) FOR [NRETENCION]
GO
ALTER TABLE [dbo].[ANEXO] ADD  CONSTRAINT [DF__ANEXO__ANE_DETRA__78B3EFCA]  DEFAULT (0) FOR [ANE_DETRACCION]
GO
ALTER TABLE [dbo].[ANEXO] ADD  CONSTRAINT [DF__ANEXO__ANE_TASA___79A81403]  DEFAULT (0) FOR [ANE_TASA_DETRACC]
GO
ALTER TABLE [dbo].[ANEXO] ADD  CONSTRAINT [DF__ANEXO__ANEX_SEXO__7A9C383C]  DEFAULT (0) FOR [ANEX_SEXO]
GO
ALTER TABLE [dbo].[CENTRO_COSTOS] ADD  DEFAULT (0) FOR [CENCOST_TRANSFERENCIA]
GO
ALTER TABLE [dbo].[COA] ADD  DEFAULT (0) FOR [CO_N_MONED]
GO
ALTER TABLE [dbo].[CONCEPTOS_GENERALES] ADD  DEFAULT (0) FOR [CONCGRAL_CONTEN]
GO
ALTER TABLE [dbo].[CONCEPTOS_GENERALES] ADD  DEFAULT (0) FOR [CONCGRAL_CONTEL]
GO
ALTER TABLE [dbo].[COSTO_CLASE_9] ADD  DEFAULT (0) FOR [COSTCLAS9_FACTOR]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_CBSCF]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_CBNCF]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_CBNGR]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_CBMIX]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_CIMIX]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_CISCF]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_CINCF]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_CICPA]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_VBAFE]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_VBINA]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_VIGV]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_CREDI]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_IGV]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_L_CALCU]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_IRBAS]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_IRMTO]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_IRFAC]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_L_IRCAL]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_ANBAS]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_ANMTO]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_ANCUO]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_ANFAJ]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_N_ANFAC]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [CO_L_ANCAL]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [II_N_CBSCF]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [II_N_CBNCF]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [II_N_CBNGR]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [II_N_CISCF]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [II_N_CBMIX]
GO
ALTER TABLE [dbo].[IMP_MENSUALES] ADD  DEFAULT (0) FOR [II_N_CIMIX]
GO
ALTER TABLE [dbo].[IPM] ADD  DEFAULT (0) FOR [CO_N_FACTO]
GO
ALTER TABLE [dbo].[IPM] ADD  DEFAULT (0) FOR [CO_N_IPM]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_EXTERIOR] ADD  DEFAULT (0) FOR [CTAEX_NIVEL]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__PLANC__45F365D3]  DEFAULT (0) FOR [PLANCTA_NIVEL]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__PLANC__46E78A0C]  DEFAULT (0) FOR [PLANCTA_CENTCOST]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__PLANC__47DBAE45]  DEFAULT (0) FOR [PLANCTA_AUTO]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__PLANC__48CFD27E]  DEFAULT (0) FOR [PLANCTA_PORCENT1]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__PLANC__49C3F6B7]  DEFAULT (0) FOR [PLANCTA_PORCENT2]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__PLANC__4AB81AF0]  DEFAULT (0) FOR [PLANCTA_PORCENT3]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__PLANC__4BAC3F29]  DEFAULT (0) FOR [PLANCTA_AJUSTE]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__PLANC__4CA06362]  DEFAULT (0) FOR [PLANCTA_MONETARIA]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__ESitu__10216507]  DEFAULT ('') FOR [ESituacion]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__EResu__11158940]  DEFAULT ('') FOR [EResultado]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__EPatr__1209AD79]  DEFAULT ('') FOR [EPatrimonio]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__TSitu__12FDD1B2]  DEFAULT ('') FOR [TSituacion]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__TResu__13F1F5EB]  DEFAULT ('') FOR [TResultado]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__TPatr__14E61A24]  DEFAULT ('') FOR [TPatrimonio]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__CSitu__15DA3E5D]  DEFAULT ('') FOR [CSituacion]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__CResu__16CE6296]  DEFAULT ('') FOR [CResultado]
GO
ALTER TABLE [dbo].[PLAN_CUENTA_NACIONAL] ADD  CONSTRAINT [DF__PLAN_CUEN__CPatr__17C286CF]  DEFAULT ('') FOR [CPatrimonio]
GO
ALTER TABLE [dbo].[PRESUPUESTO_CCOSTO] ADD  DEFAULT (0) FOR [PRESU_MOPMN]
GO
ALTER TABLE [dbo].[PRESUPUESTO_CCOSTO] ADD  DEFAULT (0) FOR [PRESU_MOPME]
GO
ALTER TABLE [dbo].[RESULTADOS_ANUALES] ADD  DEFAULT (0) FOR [CO_N_INGAN]
GO
ALTER TABLE [dbo].[RESULTADOS_ANUALES] ADD  DEFAULT (0) FOR [CO_N_INGIM]
GO
ALTER TABLE [dbo].[RESULTADOS_ANUALES] ADD  DEFAULT (0) FOR [CO_N_IMPRE]
GO
ALTER TABLE [dbo].[RESULTADOS_ANUALES] ADD  DEFAULT (0) FOR [CO_N_RESUL]
GO
ALTER TABLE [dbo].[RESULTADOS_ANUALES] ADD  DEFAULT (0) FOR [CO_N_PAGIR]
GO
ALTER TABLE [dbo].[RESULTADOS_ANUALES] ADD  DEFAULT (0) FOR [CO_N_ACTNE]
GO
ALTER TABLE [dbo].[RESULTADOS_ANUALES] ADD  DEFAULT (0) FOR [CO_L_CALCU]
GO
ALTER TABLE [dbo].[SUBDIARIOS] ADD  DEFAULT (0) FOR [SUBDIAR_AUTOM]
GO
ALTER TABLE [dbo].[TABLA_ESTRUCCOSTOS] ADD  DEFAULT (0) FOR [TABL_ESTRUCCOS_FACTO]
GO
ALTER TABLE [dbo].[TABLA_IPM] ADD  DEFAULT (0) FOR [TABLIPM_FACTO]
GO
ALTER TABLE [dbo].[TABLA_IPM] ADD  DEFAULT (0) FOR [TABLIPM_IPM]
GO
ALTER TABLE [dbo].[TIPO_CAMBIO_] ADD  DEFAULT (0) FOR [TIPOCAMB_COMPRA]
GO
ALTER TABLE [dbo].[TIPO_CAMBIO_] ADD  DEFAULT (0) FOR [TIPOCAMB_EQCOMPRA]
GO
ALTER TABLE [dbo].[TIPO_CAMBIO_] ADD  DEFAULT (0) FOR [TIPOCAMB_VENTA]
GO
ALTER TABLE [dbo].[TIPO_CAMBIO_] ADD  DEFAULT (0) FOR [TIPOCAMB_EQVENTA]
GO
ALTER TABLE [dbo].[TIPO_MONEDA] ADD  DEFAULT (0) FOR [TIPOMON_NACIONALIDAD]
GO
ALTER TABLE [dbo].[TIPOS_DE_DOCUMENTOS] ADD  DEFAULT (0) FOR [TIPDOC_RESTA]
GO
ALTER TABLE [dbo].[TIPOS_DE_DOCUMENTOS] ADD  DEFAULT (0) FOR [TIPDOC_REFERENCIA]
GO
ALTER TABLE [dbo].[TIPOS_DE_DOCUMENTOS] ADD  DEFAULT (0) FOR [TIPDOC_FECHAVTO]
GO
ALTER TABLE [dbo].[TIPOS_DE_DOCUMENTOS] ADD  DEFAULT (0) FOR [TIPDOC_FECHAVTO_VTA]
GO
USE [master]
GO
ALTER DATABASE [007BDCONTABILIDAD] SET  READ_WRITE 
GO
