USE [master]
GO
/****** Object:  Database [CP]    Script Date: 18/02/2023 19:49:02 ******/
CREATE DATABASE [CP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CP_Data', FILENAME = N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\CP.MDF' , SIZE = 52096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'CP_Log', FILENAME = N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\CP.LDF' , SIZE = 4672KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
ALTER DATABASE [CP] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CP].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [CP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CP] SET ARITHABORT OFF 
GO
ALTER DATABASE [CP] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [CP] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [CP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CP] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CP] SET  MULTI_USER 
GO
ALTER DATABASE [CP] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [CP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CP] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CP] SET QUERY_STORE = OFF
GO
USE [CP]
GO
/****** Object:  User [user]    Script Date: 18/02/2023 19:49:03 ******/
CREATE USER [user] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[user]
GO
/****** Object:  User [sqlbackup]    Script Date: 18/02/2023 19:49:03 ******/
CREATE USER [sqlbackup] WITH DEFAULT_SCHEMA=[sqlbackup]
GO
/****** Object:  User [consulta]    Script Date: 18/02/2023 19:49:03 ******/
CREATE USER [consulta] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[consulta]
GO
ALTER ROLE [db_owner] ADD MEMBER [user]
GO
ALTER ROLE [db_owner] ADD MEMBER [consulta]
GO
/****** Object:  Schema [consulta]    Script Date: 18/02/2023 19:49:03 ******/
CREATE SCHEMA [consulta]
GO
/****** Object:  Schema [sqlbackup]    Script Date: 18/02/2023 19:49:03 ******/
CREATE SCHEMA [sqlbackup]
GO
/****** Object:  Schema [user]    Script Date: 18/02/2023 19:49:03 ******/
CREATE SCHEMA [user]
GO
/****** Object:  View [dbo].[relacion cabecera y detalle asiento contable]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[relacion cabecera y detalle asiento contable]
AS
SELECT     dbo.CPI0305.NUMES_I01, dbo.CPI0305.SUBDI_I01, dbo.CPI0305.NUCOM_I01, dbo.CPI0305.MONED_I01, dbo.CPI0305.TICAM_I01, 
                      dbo.CPI0305.GLOSA_I01, dbo.CPI0405.CUENT_I02, dbo.CPI0405.COSTO_I02, dbo.CPI0405.MAEST_I02, dbo.CPI0405.DEFEC_I02, 
                      dbo.CPI0405.SOLES_I02, dbo.CPI0405.DOLAR_I02, dbo.CPI0405.NUREG_I02, dbo.CPI0405.NUDOC_I02, dbo.CPI0405.TIDOC_I02, 
                      dbo.CPI0405.FEDOC_I02
FROM         dbo.CPI0305 INNER JOIN
                      dbo.CPI0405 ON dbo.CPI0305.IDCAB_I01 = dbo.CPI0405.IDCAB_I02
GO
/****** Object:  View [dbo].[relacion cpi01 con cpi03 y cpi04]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[relacion cpi01 con cpi03 y cpi04]
AS
SELECT     dbo.CPI0105.IDCPP_I01, dbo.CPI0305.IDCPP_I01 AS Expr1, dbo.CPI0305.IDCAB_I01, dbo.CPI0405.IDCAB_I02, dbo.CPI0405.IDDET_I02, 
                      dbo.CPI0105.PERIO_I01, dbo.CPI0105.VOUCH_I01, dbo.CPI0305.NUCOM_I01, dbo.CPI0305.MONED_I01, dbo.CPI0305.TICAM_I01, 
                      dbo.CPI0305.GLOSA_I01, dbo.CPI0405.CUENT_I02, dbo.CPI0405.MAEST_I02, dbo.CPI0405.DEFEC_I02, dbo.CPI0405.SOLES_I02, 
                      dbo.CPI0405.DOLAR_I02, dbo.CPI0105.VALSO_I01, dbo.CPI0105.VALDO_I01, dbo.CPI0305.DEBIT_I01, dbo.CPI0305.CREDI_I01
FROM         dbo.CPI0105 INNER JOIN
                      dbo.CPI0305 ON dbo.CPI0105.IDCPP_I01 = dbo.CPI0305.IDCPP_I01 INNER JOIN
                      dbo.CPI0405 ON dbo.CPI0305.IDCAB_I01 = dbo.CPI0405.IDCAB_I02
GO
/****** Object:  Table [dbo].[CPI01]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI01](
	[IDCAB_I01] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PERIO_I01] [char](7) NOT NULL,
	[LOCAL_I01] [char](2) NOT NULL,
	[SUBDI_I01] [char](2) NULL,
	[CTPPG_I01] [varchar](8) NOT NULL,
	[VOUCH_I01] [char](12) NOT NULL,
	[FEREG_I01] [datetime] NOT NULL,
	[DEFEC_I01] [char](10) NOT NULL,
	[MAEST_I01] [char](11) NOT NULL,
	[TIDOC_I01] [char](2) NULL,
	[SEDOC_I01] [char](4) NULL,
	[NUDOC_I01] [char](17) NULL,
	[FEDOC_I01] [datetime] NULL,
	[DESTI_I01] [char](2) NULL,
	[MONED_I01] [char](12) NOT NULL,
	[CONVE_I01] [char](3) NULL,
	[TICAM_I01] [float] NOT NULL,
	[SUBSO_I01] [float] NOT NULL,
	[IGVSO_I01] [float] NOT NULL,
	[OTSSO_I01] [float] NULL,
	[VALSO_I01] [float] NOT NULL,
	[SUBDO_I01] [float] NOT NULL,
	[IGVDO_I01] [float] NOT NULL,
	[OTSDO_I01] [float] NULL,
	[VALDO_I01] [float] NOT NULL,
	[OBSER_I01] [char](100) NOT NULL,
	[CONTA_I01] [char](1) NULL,
	[FECON_I01] [datetime] NULL,
	[STATU_I01] [char](1) NULL,
	[USUAR_I01] [char](10) NULL,
	[CANCE_I01] [char](1) NULL,
	[IDCAN_I01] [int] NULL,
	[IDCSS_I01] [char](8) NULL,
	[FEVEN_I01] [datetime] NULL,
	[SALDO_I01] [float] NULL,
	[RENOV_I01] [datetime] NULL,
	[FLDET_I01] [bit] NULL,
	[CDDET_I01] [varchar](2) NULL,
	[PFACT_I01] [int] NULL,
	[FVENC_I01] [datetime] NULL,
	[FLPPD_I01] [bit] NULL,
	[FPDET_I01] [varchar](2) NULL,
	[FLDCD_I01] [bit] NULL,
	[POIGV_I01] [float] NULL,
	[FVORI_I01] [datetime] NULL,
 CONSTRAINT [PK_CPI0105] PRIMARY KEY CLUSTERED 
(
	[IDCAB_I01] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI01COPYdmagr]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI01COPYdmagr](
	[IDCAB_I01] [int] NOT NULL,
	[PERIO_I01] [char](7) NOT NULL,
	[LOCAL_I01] [char](2) NOT NULL,
	[SUBDI_I01] [char](2) NULL,
	[CTPPG_I01] [char](8) NOT NULL,
	[VOUCH_I01] [char](12) NOT NULL,
	[FEREG_I01] [datetime] NOT NULL,
	[DEFEC_I01] [char](10) NOT NULL,
	[MAEST_I01] [char](11) NOT NULL,
	[TIDOC_I01] [char](2) NULL,
	[SEDOC_I01] [char](4) NULL,
	[NUDOC_I01] [char](17) NULL,
	[FEDOC_I01] [datetime] NULL,
	[DESTI_I01] [char](2) NULL,
	[MONED_I01] [char](12) NOT NULL,
	[CONVE_I01] [char](3) NULL,
	[TICAM_I01] [float] NOT NULL,
	[SUBSO_I01] [float] NOT NULL,
	[IGVSO_I01] [float] NOT NULL,
	[OTSSO_I01] [float] NULL,
	[VALSO_I01] [float] NOT NULL,
	[SUBDO_I01] [float] NOT NULL,
	[IGVDO_I01] [float] NOT NULL,
	[OTSDO_I01] [float] NULL,
	[VALDO_I01] [float] NOT NULL,
	[OBSER_I01] [char](100) NOT NULL,
	[CONTA_I01] [char](1) NULL,
	[FECON_I01] [datetime] NULL,
	[STATU_I01] [char](1) NULL,
	[USUAR_I01] [char](10) NULL,
	[CANCE_I01] [char](1) NULL,
	[IDCAN_I01] [int] NULL,
	[IDCSS_I01] [char](8) NULL,
	[FEVEN_I01] [datetime] NULL,
	[SALDO_I01] [float] NULL,
	[RENOV_I01] [datetime] NULL,
	[FLDET_I01] [bit] NULL,
	[CDDET_I01] [varchar](2) NULL,
	[PFACT_I01] [int] NULL,
	[FVENC_I01] [datetime] NULL,
	[FLPPD_I01] [bit] NULL,
	[FPDET_I01] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI01COPYdmagrLTS]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI01COPYdmagrLTS](
	[IDCAB_I01] [int] NOT NULL,
	[PERIO_I01] [char](7) NOT NULL,
	[LOCAL_I01] [char](2) NOT NULL,
	[SUBDI_I01] [char](2) NULL,
	[CTPPG_I01] [char](8) NOT NULL,
	[VOUCH_I01] [char](12) NOT NULL,
	[FEREG_I01] [datetime] NOT NULL,
	[DEFEC_I01] [char](10) NOT NULL,
	[MAEST_I01] [char](11) NOT NULL,
	[TIDOC_I01] [char](2) NULL,
	[SEDOC_I01] [char](4) NULL,
	[NUDOC_I01] [char](17) NULL,
	[FEDOC_I01] [datetime] NULL,
	[DESTI_I01] [char](2) NULL,
	[MONED_I01] [char](12) NOT NULL,
	[CONVE_I01] [char](3) NULL,
	[TICAM_I01] [float] NOT NULL,
	[SUBSO_I01] [float] NOT NULL,
	[IGVSO_I01] [float] NOT NULL,
	[OTSSO_I01] [float] NULL,
	[VALSO_I01] [float] NOT NULL,
	[SUBDO_I01] [float] NOT NULL,
	[IGVDO_I01] [float] NOT NULL,
	[OTSDO_I01] [float] NULL,
	[VALDO_I01] [float] NOT NULL,
	[OBSER_I01] [char](100) NOT NULL,
	[CONTA_I01] [char](1) NULL,
	[FECON_I01] [datetime] NULL,
	[STATU_I01] [char](1) NULL,
	[USUAR_I01] [char](10) NULL,
	[CANCE_I01] [char](1) NULL,
	[IDCAN_I01] [int] NULL,
	[IDCSS_I01] [char](8) NULL,
	[FEVEN_I01] [datetime] NULL,
	[SALDO_I01] [float] NULL,
	[RENOV_I01] [datetime] NULL,
	[FLDET_I01] [bit] NULL,
	[CDDET_I01] [varchar](2) NULL,
	[PFACT_I01] [int] NULL,
	[FVENC_I01] [datetime] NULL,
	[FLPPD_I01] [bit] NULL,
	[FPDET_I01] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI02]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI02](
	[IDDET_I02] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I02] [int] NOT NULL,
	[ITEM__I02] [varchar](5) NOT NULL,
	[CUENT_I02] [varchar](8) NOT NULL,
	[COSTO_I02] [varchar](8) NULL,
	[MAEST_I02] [varchar](11) NULL,
	[TIDOC_I02] [varchar](2) NOT NULL,
	[SEDOC_I02] [varchar](4) NOT NULL,
	[NUDOC_I02] [varchar](17) NOT NULL,
	[FEDOC_I02] [datetime] NOT NULL,
	[DEFEC_I02] [varchar](1) NOT NULL,
	[SOLES_I02] [float] NOT NULL,
	[DOLAR_I02] [float] NOT NULL,
	[REFER_I02] [varchar](100) NULL,
	[FEVEN_I02] [datetime] NULL,
	[IDPRO_I02] [int] NULL,
	[FLANT_I02] [bit] NULL,
	[FLCAN_I02] [bit] NULL,
	[SDOAN_I02] [float] NULL,
	[FLFEC_I02] [bit] NULL,
	[FLCNF_I02] [bit] NULL,
 CONSTRAINT [PK_CPI0405] PRIMARY KEY CLUSTERED 
(
	[IDDET_I02] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI02COPYdmagr]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI02COPYdmagr](
	[IDCAB_I01] [int] NOT NULL,
	[PERIO_I01] [char](7) NOT NULL,
	[LOCAL_I01] [char](2) NOT NULL,
	[SUBDI_I01] [char](2) NULL,
	[CTPPG_I01] [char](8) NOT NULL,
	[VOUCH_I01] [char](12) NOT NULL,
	[FEREG_I01] [datetime] NOT NULL,
	[DEFEC_I01] [char](10) NOT NULL,
	[MAEST_I01] [char](11) NOT NULL,
	[TIDOC_I01] [char](2) NULL,
	[SEDOC_I01] [char](4) NULL,
	[NUDOC_I01] [char](17) NULL,
	[FEDOC_I01] [datetime] NULL,
	[DESTI_I01] [char](2) NULL,
	[MONED_I01] [char](12) NOT NULL,
	[CONVE_I01] [char](3) NULL,
	[TICAM_I01] [float] NOT NULL,
	[SUBSO_I01] [float] NOT NULL,
	[IGVSO_I01] [float] NOT NULL,
	[OTSSO_I01] [float] NULL,
	[VALSO_I01] [float] NOT NULL,
	[SUBDO_I01] [float] NOT NULL,
	[IGVDO_I01] [float] NOT NULL,
	[OTSDO_I01] [float] NULL,
	[VALDO_I01] [float] NOT NULL,
	[OBSER_I01] [char](100) NOT NULL,
	[CONTA_I01] [char](1) NULL,
	[FECON_I01] [datetime] NULL,
	[STATU_I01] [char](1) NULL,
	[USUAR_I01] [char](10) NULL,
	[CANCE_I01] [char](1) NULL,
	[IDCAN_I01] [int] NULL,
	[IDCSS_I01] [char](8) NULL,
	[FEVEN_I01] [datetime] NULL,
	[SALDO_I01] [float] NULL,
	[RENOV_I01] [datetime] NULL,
	[FLDET_I01] [bit] NULL,
	[CDDET_I01] [varchar](2) NULL,
	[PFACT_I01] [int] NULL,
	[FVENC_I01] [datetime] NULL,
	[FLPPD_I01] [bit] NULL,
	[FPDET_I01] [varchar](2) NULL,
	[IDDET_I02] [int] NOT NULL,
	[IDCAB_I02] [int] NOT NULL,
	[ITEM__I02] [varchar](5) NOT NULL,
	[CUENT_I02] [varchar](8) NOT NULL,
	[COSTO_I02] [varchar](8) NULL,
	[MAEST_I02] [varchar](11) NULL,
	[TIDOC_I02] [varchar](2) NOT NULL,
	[SEDOC_I02] [varchar](4) NOT NULL,
	[NUDOC_I02] [varchar](17) NOT NULL,
	[FEDOC_I02] [datetime] NOT NULL,
	[DEFEC_I02] [varchar](1) NOT NULL,
	[SOLES_I02] [float] NOT NULL,
	[DOLAR_I02] [float] NOT NULL,
	[REFER_I02] [varchar](100) NULL,
	[FEVEN_I02] [datetime] NULL,
	[IDPRO_I02] [int] NULL,
	[FLANT_I02] [bit] NULL,
	[FLCAN_I02] [bit] NULL,
	[SDOAN_I02] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI02COPYdmagrLTS]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI02COPYdmagrLTS](
	[IDCAB_I01] [int] NOT NULL,
	[PERIO_I01] [char](7) NOT NULL,
	[LOCAL_I01] [char](2) NOT NULL,
	[SUBDI_I01] [char](2) NULL,
	[CTPPG_I01] [char](8) NOT NULL,
	[VOUCH_I01] [char](12) NOT NULL,
	[FEREG_I01] [datetime] NOT NULL,
	[DEFEC_I01] [char](10) NOT NULL,
	[MAEST_I01] [char](11) NOT NULL,
	[TIDOC_I01] [char](2) NULL,
	[SEDOC_I01] [char](4) NULL,
	[NUDOC_I01] [char](17) NULL,
	[FEDOC_I01] [datetime] NULL,
	[DESTI_I01] [char](2) NULL,
	[MONED_I01] [char](12) NOT NULL,
	[CONVE_I01] [char](3) NULL,
	[TICAM_I01] [float] NOT NULL,
	[SUBSO_I01] [float] NOT NULL,
	[IGVSO_I01] [float] NOT NULL,
	[OTSSO_I01] [float] NULL,
	[VALSO_I01] [float] NOT NULL,
	[SUBDO_I01] [float] NOT NULL,
	[IGVDO_I01] [float] NOT NULL,
	[OTSDO_I01] [float] NULL,
	[VALDO_I01] [float] NOT NULL,
	[OBSER_I01] [char](100) NOT NULL,
	[CONTA_I01] [char](1) NULL,
	[FECON_I01] [datetime] NULL,
	[STATU_I01] [char](1) NULL,
	[USUAR_I01] [char](10) NULL,
	[CANCE_I01] [char](1) NULL,
	[IDCAN_I01] [int] NULL,
	[IDCSS_I01] [char](8) NULL,
	[FEVEN_I01] [datetime] NULL,
	[SALDO_I01] [float] NULL,
	[RENOV_I01] [datetime] NULL,
	[FLDET_I01] [bit] NULL,
	[CDDET_I01] [varchar](2) NULL,
	[PFACT_I01] [int] NULL,
	[FVENC_I01] [datetime] NULL,
	[FLPPD_I01] [bit] NULL,
	[FPDET_I01] [varchar](2) NULL,
	[IDDET_I02] [int] NOT NULL,
	[IDCAB_I02] [int] NOT NULL,
	[ITEM__I02] [varchar](5) NOT NULL,
	[CUENT_I02] [varchar](8) NOT NULL,
	[COSTO_I02] [varchar](8) NULL,
	[MAEST_I02] [varchar](11) NULL,
	[TIDOC_I02] [varchar](2) NOT NULL,
	[SEDOC_I02] [varchar](4) NOT NULL,
	[NUDOC_I02] [varchar](17) NOT NULL,
	[FEDOC_I02] [datetime] NOT NULL,
	[DEFEC_I02] [varchar](1) NOT NULL,
	[SOLES_I02] [float] NOT NULL,
	[DOLAR_I02] [float] NOT NULL,
	[REFER_I02] [varchar](100) NULL,
	[FEVEN_I02] [datetime] NULL,
	[IDPRO_I02] [int] NULL,
	[FLANT_I02] [bit] NULL,
	[FLCAN_I02] [bit] NULL,
	[SDOAN_I02] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI03]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI03](
	[IDDET_I03] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I03] [int] NOT NULL,
	[SEGUI_I03] [varchar](4) NULL,
	[NUGUI_I03] [varchar](8) NULL,
	[IDALM_I03] [int] NOT NULL,
 CONSTRAINT [PK_CPI03] PRIMARY KEY CLUSTERED 
(
	[IDDET_I03] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI04]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI04](
	[IDDET_I04] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I04] [int] NULL,
	[TIDOC_I04] [varchar](2) NULL,
	[SEDOC_I04] [varchar](4) NULL,
	[NUDOC_I04] [varchar](17) NULL,
	[IDPRO_I04] [int] NULL,
	[FEDOC_I04] [datetime] NULL,
 CONSTRAINT [PK_CPI04] PRIMARY KEY CLUSTERED 
(
	[IDDET_I04] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI05]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI05](
	[IDDET_I05] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I05] [int] NULL,
	[NUDOC_I05] [varchar](17) NULL,
	[FEDOC_I05] [datetime] NULL,
 CONSTRAINT [PK_CPI05] PRIMARY KEY CLUSTERED 
(
	[IDDET_I05] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI06]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI06](
	[PERIO_I06] [char](7) NULL,
	[MAEST_I06] [char](11) NULL,
	[CUENT_I06] [varchar](8) NULL,
	[FEDOC_I06] [datetime] NULL,
	[TIMOV_I06] [char](1) NULL,
	[VOUCH_I06] [char](12) NULL,
	[TIDOC_I06] [char](2) NULL,
	[SEDOC_I06] [char](4) NULL,
	[NUDOC_I06] [varchar](20) NULL,
	[MONED_I06] [char](1) NULL,
	[CARSO_I06] [float] NULL,
	[CARDO_I06] [float] NULL,
	[TICAM_I06] [float] NULL,
	[DEFEC_I06] [char](1) NULL,
	[REFER_I06] [varchar](100) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI07]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI07](
	[IDCAB_I07] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[MAEST_I07] [varchar](11) NULL,
	[NOMBR_I07] [varchar](35) NULL,
	[NULOT_I07] [varchar](6) NULL,
	[TOTAL_I07] [float] NULL,
 CONSTRAINT [PK_CPI07] PRIMARY KEY CLUSTERED 
(
	[IDCAB_I07] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI08]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI08](
	[IDDET_I08] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I08] [int] NULL,
	[MAEST_I08] [varchar](11) NULL,
	[NUPRO_I08] [varchar](9) NULL,
	[CDDET_I08] [varchar](3) NULL,
	[CTADT_I08] [varchar](11) NULL,
	[IMPOR_I08] [float] NULL,
	[CDTOP_I08] [varchar](2) NULL,
 CONSTRAINT [PK_CPI08] PRIMARY KEY CLUSTERED 
(
	[IDDET_I08] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI09]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI09](
	[IDCAB_I09] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[NULOT_I09] [varchar](6) NULL,
	[NUMES_I09] [varchar](7) NULL,
	[NUSEM_I09] [varchar](7) NULL,
	[FEPAG_I09] [datetime] NULL,
	[TOTAV_I09] [float] NULL,
	[TOTAG_I09] [float] NULL,
	[TOTAL_I09] [float] NULL,
	[USUAR_I09] [varchar](20) NULL,
	[LOCAL_I09] [varchar](2) NULL,
 CONSTRAINT [PK_CPI09] PRIMARY KEY CLUSTERED 
(
	[IDCAB_I09] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI0x]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI0x](
	[PERIO_I05] [char](7) NULL,
	[MAEST_I05] [char](11) NULL,
	[FEDOC_I05] [datetime] NULL,
	[TIMOV_I05] [char](1) NULL,
	[CUENT_I05] [char](6) NULL,
	[TIDOC_I05] [char](2) NULL,
	[VOUCH_I05] [char](12) NULL,
	[MONED_I05] [char](1) NULL,
	[DEFEC_I05] [char](1) NULL,
	[NUSER_I05] [char](4) NULL,
	[NUDOC_I05] [char](8) NULL,
	[SOLES_I05] [float] NULL,
	[DOLAR_I05] [float] NULL,
	[TICAM_I05] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPI10]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPI10](
	[IDDET_I10] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I10] [int] NULL,
	[ITEM__I10] [varchar](3) NULL,
	[MAEST_I10] [varchar](11) NULL,
	[DSMAE_I10] [varchar](50) NULL,
	[TIDOC_I10] [varchar](2) NULL,
	[SEDOC_I10] [varchar](4) NULL,
	[NUDOC_I10] [varchar](20) NULL,
	[FEDOC_I10] [datetime] NULL,
	[OBSER_I10] [varchar](100) NULL,
	[VALDO_I10] [float] NULL,
	[TICAM_I10] [float] NULL,
	[VALSO_I10] [float] NULL,
	[PORCE_I10] [float] NULL,
	[TOTAL_I10] [float] NULL,
	[CTADT_I10] [varchar](20) NULL,
	[CDTOP_I10] [varchar](3) NULL,
	[RUBRO_I10] [varchar](2) NULL,
 CONSTRAINT [PK_CPI10] PRIMARY KEY CLUSTERED 
(
	[IDDET_I10] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPR01]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPR01](
	[PERIO_R01] [char](7) NULL,
	[MAEST_R01] [char](11) NULL,
	[CUENT_R01] [varchar](8) NULL,
	[FEDOC_R01] [datetime] NULL,
	[TIMOV_R01] [char](1) NULL,
	[VOUCH_R01] [char](12) NULL,
	[TIDOC_R01] [char](2) NULL,
	[SEDOC_R01] [char](4) NULL,
	[NUDOC_R01] [varchar](20) NULL,
	[MONED_R01] [char](1) NULL,
	[ABOSO_R01] [float] NULL,
	[CARSO_R01] [float] NULL,
	[ABODO_R01] [float] NULL,
	[CARDO_R01] [float] NULL,
	[TICAM_R01] [float] NULL,
	[DEFEC_R01] [char](1) NULL,
	[REFER_R01] [varchar](100) NULL,
	[RENOV_R01] [datetime] NULL,
	[FLDCD_R01] [bit] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPR02]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPR02](
	[CLASE_R02] [char](5) NOT NULL,
	[MAEST_R02] [char](11) NOT NULL,
	[PERIO_R02] [char](7) NOT NULL,
	[SNSOL_R02] [float] NULL,
	[DBSOL_R02] [float] NULL,
	[HBSOL_R02] [float] NULL,
	[SASOL_R02] [float] NULL,
	[SNDOL_R02] [float] NULL,
	[DBDOL_R02] [float] NULL,
	[HBDOL_R02] [float] NULL,
	[SADOL_R02] [float] NULL,
	[DEBE__R02] [float] NULL,
	[HABE__R02] [float] NULL,
 CONSTRAINT [PK_CPR02A] PRIMARY KEY CLUSTERED 
(
	[CLASE_R02] ASC,
	[MAEST_R02] ASC,
	[PERIO_R02] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPR02DDD]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPR02DDD](
	[CLASE_R02] [char](5) NOT NULL,
	[MAEST_R02] [char](11) NOT NULL,
	[PERIO_R02] [char](7) NOT NULL,
	[DEBE__R02] [float] NULL,
	[HABE__R02] [float] NULL,
 CONSTRAINT [PK_CPR02] PRIMARY KEY CLUSTERED 
(
	[CLASE_R02] ASC,
	[MAEST_R02] ASC,
	[PERIO_R02] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPT01]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPT01](
	[CODIG_T01] [char](8) NULL,
	[DESCR_T01] [char](50) NULL,
	[MONED_T01] [char](1) NULL,
	[SUBDI_T01] [char](2) NULL,
	[CUENT_T01] [varchar](8) NULL,
	[CTIGV_T01] [varchar](8) NULL,
	[TANEX_T01] [char](2) NULL,
	[RUBRO_T01] [varchar](2) NULL,
	[LOCAL_T01] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPT02]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPT02](
	[CODIG_T02] [char](2) NULL,
	[DESCR_T02] [char](30) NULL,
	[ABREV_T02] [char](2) NULL,
	[SUBDI_T02] [char](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPT03]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPT03](
	[CODIG_T03] [char](2) NULL,
	[DESCR_T03] [char](30) NULL,
	[ABREV_T03] [char](2) NULL,
	[CUENT_T03] [varchar](8) NULL,
	[PORCE_T03] [float] NULL,
	[AFIMP_T03] [bit] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPT04]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPT04](
	[CODIG_T04] [char](8) NULL,
	[DESCR_T04] [char](50) NULL,
	[MONED_T04] [char](1) NULL,
	[SUBDI_T04] [char](2) NULL,
	[CUENT_T04] [varchar](8) NULL,
	[CTIGV_T04] [varchar](8) NULL,
	[TANEX_T04] [char](2) NULL,
	[RUBRO_T04] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPT05]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPT05](
	[CODIG_T05] [char](8) NULL,
	[DESCR_T05] [char](50) NULL,
	[MONED_T05] [char](1) NULL,
	[SUBDI_T05] [char](2) NULL,
	[CUENT_T05] [varchar](8) NULL,
	[CTIGV_T05] [varchar](8) NULL,
	[TANEX_T05] [char](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPT06]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPT06](
	[CODIG_T06] [char](8) NULL,
	[DESCR_T06] [char](50) NULL,
	[MONED_T06] [char](1) NULL,
	[SUBDI_T06] [char](2) NULL,
	[CUENT_T06] [varchar](8) NULL,
	[CTIGV_T06] [varchar](8) NULL,
	[TANEX_T06] [char](2) NULL,
	[RUBRO_T06] [varchar](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPT07]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPT07](
	[CODIG_T07] [char](2) NOT NULL,
	[DESCR_T07] [varchar](20) NULL,
	[ABREV_T07] [char](3) NULL,
	[DESDE_T07] [datetime] NULL,
	[HASTA_T07] [datetime] NULL,
	[TRDIS_T07] [int] NULL,
	[ANO___T07] [char](4) NULL,
	[IDSEM_T07] [char](7) NOT NULL,
	[STATU_T07] [char](1) NULL,
	[STAT2_T07] [char](1) NULL,
 CONSTRAINT [PK_CPT07] PRIMARY KEY CLUSTERED 
(
	[IDSEM_T07] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPT08]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPT08](
	[CODIG_T08] [varchar](2) NOT NULL,
	[DESCR_T08] [varchar](50) NULL,
	[ABREV_T08] [varchar](20) NULL,
	[FLSEC_T08] [bit] NULL,
 CONSTRAINT [PK_CPT08] PRIMARY KEY CLUSTERED 
(
	[CODIG_T08] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPT09]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPT09](
	[CODIG_T09] [varchar](2) NOT NULL,
	[DESCR_T09] [varchar](50) NULL,
	[MONED_T09] [char](1) NULL,
	[SUBDI_T09] [char](2) NULL,
	[CUENT_T09] [varchar](8) NULL,
	[CTIGV_T09] [varchar](8) NULL,
	[TANEX_T09] [char](2) NULL,
	[RUBRO_T09] [varchar](2) NULL,
	[CTINT_T09] [varchar](8) NULL,
	[CTFEC_T09] [varchar](8) NULL,
	[SERDF_T09] [varchar](4) NULL,
	[TDODF_T09] [varchar](2) NULL,
	[FREVC_T09] [int] NULL,
	[TAFEC_T09] [varchar](2) NULL,
	[ANFEC_T09] [varchar](11) NULL,
 CONSTRAINT [PK_CPT09] PRIMARY KEY CLUSTERED 
(
	[CODIG_T09] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPW05]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPW05](
	[USUAR_W05] [varchar](50) NULL,
	[LOCAL_W05] [char](2) NULL,
	[CTPPG_W05] [varchar](8) NULL,
	[VOUCH_W05] [char](12) NULL,
	[MONED_W05] [char](1) NULL,
	[CONVE_W05] [char](3) NULL,
	[TICAM_W05] [float] NULL,
	[MAEST_W05] [char](11) NULL,
	[TIDOC_W05] [char](2) NULL,
	[SEDOC_W05] [char](4) NULL,
	[NUDOC_W05] [varchar](50) NULL,
	[FEDOC_W05] [datetime] NULL,
	[SUBSO_W05] [float] NULL,
	[IGVSO_W05] [float] NULL,
	[OTSSO_W05] [float] NULL,
	[VALSO_W05] [float] NULL,
	[SUBDO_W05] [float] NULL,
	[IGVDO_W05] [float] NULL,
	[OTSDO_W05] [float] NULL,
	[VALDO_W05] [float] NULL,
	[OBSER_W05] [varchar](100) NULL,
	[DESTI_W05] [char](2) NULL,
	[COMPU_W05] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPW06]    Script Date: 18/02/2023 19:49:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPW06](
	[VOUCH_W06] [varchar](12) NULL,
	[NOMBR_W06] [varchar](50) NULL,
	[TIDOC_W06] [varchar](2) NULL,
	[SEDOC_W06] [varchar](4) NULL,
	[NUDOC_W06] [varchar](20) NULL,
	[FEDOC_W06] [datetime] NULL,
	[OBSER_W06] [varchar](100) NULL,
	[VALDO_W06] [float] NULL,
	[TICAM_W06] [float] NULL,
	[VALSO_W06] [float] NULL,
	[PORCE_W06] [float] NULL,
	[SOLES_W06] [float] NULL,
	[CTADT_W06] [varchar](50) NULL,
	[NDPAG_W06] [varchar](20) NULL,
	[USUAR_W06] [varchar](20) NULL,
	[COMPU_W06] [varchar](20) NULL,
	[MAEST_W06] [varchar](11) NULL,
	[ABREV_W06] [varchar](2) NULL,
	[CDDET_W06] [varchar](2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_SUBDI_I01]  DEFAULT ('04') FOR [SUBDI_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_TICAM_I01]  DEFAULT (0) FOR [TICAM_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_SUBSO_I01]  DEFAULT (0) FOR [SUBSO_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_IGVSO_I01]  DEFAULT (0) FOR [IGVSO_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_OTSSO_I01]  DEFAULT (0) FOR [OTSSO_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_VALSO_I01]  DEFAULT (0) FOR [VALSO_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_SUBDO_I01]  DEFAULT (0) FOR [SUBDO_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_IGVDO_I01]  DEFAULT (0) FOR [IGVDO_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_OTSDO_I01]  DEFAULT (0) FOR [OTSDO_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_VALDO_I01]  DEFAULT (0) FOR [VALDO_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_CONTA_I01]  DEFAULT ('N') FOR [CONTA_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_STATU_I01]  DEFAULT ('E') FOR [STATU_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_CANCE_I01]  DEFAULT ('N') FOR [CANCE_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_IDCAN_I01]  DEFAULT (0) FOR [IDCAN_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_SALDO_I01]  DEFAULT (0) FOR [SALDO_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_FLDET_I01]  DEFAULT (0) FOR [FLDET_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_CDDET_I01]  DEFAULT (' ') FOR [CDDET_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_PFACT_I01]  DEFAULT (0) FOR [PFACT_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_FLPPD_I01]  DEFAULT (0) FOR [FLPPD_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_FPDET_I01]  DEFAULT (' ') FOR [FPDET_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_FLDCD_I01]  DEFAULT (0) FOR [FLDCD_I01]
GO
ALTER TABLE [dbo].[CPI01] ADD  CONSTRAINT [DF_CPI01_POIGV_I01]  DEFAULT (0.19) FOR [POIGV_I01]
GO
ALTER TABLE [dbo].[CPI02] ADD  CONSTRAINT [DF_CPI02_DEFEC_I02]  DEFAULT ('0') FOR [DEFEC_I02]
GO
ALTER TABLE [dbo].[CPI02] ADD  CONSTRAINT [DF_CPI02_SOLES_I02]  DEFAULT (0) FOR [SOLES_I02]
GO
ALTER TABLE [dbo].[CPI02] ADD  CONSTRAINT [DF_CPI02_DOLAR_I02]  DEFAULT (0) FOR [DOLAR_I02]
GO
ALTER TABLE [dbo].[CPI02] ADD  CONSTRAINT [DF_CPI02_IDPRO_I02]  DEFAULT (0) FOR [IDPRO_I02]
GO
ALTER TABLE [dbo].[CPI02] ADD  CONSTRAINT [DF_CPI02_FLANT_I02]  DEFAULT (0) FOR [FLANT_I02]
GO
ALTER TABLE [dbo].[CPI02] ADD  CONSTRAINT [DF_CPI02_FLCAN_I02]  DEFAULT (0) FOR [FLCAN_I02]
GO
ALTER TABLE [dbo].[CPI02] ADD  CONSTRAINT [DF_CPI02_SDOAN_I02]  DEFAULT (0) FOR [SDOAN_I02]
GO
ALTER TABLE [dbo].[CPI02] ADD  CONSTRAINT [DF_CPI02_FLFEC_I02]  DEFAULT (0) FOR [FLFEC_I02]
GO
ALTER TABLE [dbo].[CPI02] ADD  CONSTRAINT [DF_CPI02_FLCNF_I02]  DEFAULT (0) FOR [FLCNF_I02]
GO
ALTER TABLE [dbo].[CPI03] ADD  CONSTRAINT [DF_CPI03_IDCAB_I03]  DEFAULT (0) FOR [IDCAB_I03]
GO
ALTER TABLE [dbo].[CPI03] ADD  CONSTRAINT [DF_CPI03_SEGUI_I03]  DEFAULT (' ') FOR [SEGUI_I03]
GO
ALTER TABLE [dbo].[CPI03] ADD  CONSTRAINT [DF_CPI03_NUGUI_I03]  DEFAULT (' ') FOR [NUGUI_I03]
GO
ALTER TABLE [dbo].[CPI03] ADD  CONSTRAINT [DF_CPI03_IDALM_I03]  DEFAULT (0) FOR [IDALM_I03]
GO
ALTER TABLE [dbo].[CPI04] ADD  CONSTRAINT [DF_CPI04_IDCAB_I04]  DEFAULT (0) FOR [IDCAB_I04]
GO
ALTER TABLE [dbo].[CPI04] ADD  CONSTRAINT [DF_CPI04_TIDOC_I04]  DEFAULT (' ') FOR [TIDOC_I04]
GO
ALTER TABLE [dbo].[CPI04] ADD  CONSTRAINT [DF_CPI04_SEDOC_I04]  DEFAULT (' ') FOR [SEDOC_I04]
GO
ALTER TABLE [dbo].[CPI04] ADD  CONSTRAINT [DF_CPI04_NUDOC_I04]  DEFAULT (' ') FOR [NUDOC_I04]
GO
ALTER TABLE [dbo].[CPI04] ADD  CONSTRAINT [DF_CPI04_IDPRO_I04]  DEFAULT (0) FOR [IDPRO_I04]
GO
ALTER TABLE [dbo].[CPI05] ADD  CONSTRAINT [DF_CPI05_IDCAB_I05]  DEFAULT (0) FOR [IDCAB_I05]
GO
ALTER TABLE [dbo].[CPI05] ADD  CONSTRAINT [DF_CPI05_NUDOC_I05]  DEFAULT (' ') FOR [NUDOC_I05]
GO
ALTER TABLE [dbo].[CPI06] ADD  CONSTRAINT [DF_CPI06_CARSO_I06]  DEFAULT (0) FOR [CARSO_I06]
GO
ALTER TABLE [dbo].[CPI06] ADD  CONSTRAINT [DF_CPI06_CARDO_I06]  DEFAULT (0) FOR [CARDO_I06]
GO
ALTER TABLE [dbo].[CPI06] ADD  CONSTRAINT [DF_CPI06_TICAM_I06]  DEFAULT (0) FOR [TICAM_I06]
GO
ALTER TABLE [dbo].[CPI07] ADD  CONSTRAINT [DF_CPI07_MAEST_I07]  DEFAULT (' ') FOR [MAEST_I07]
GO
ALTER TABLE [dbo].[CPI07] ADD  CONSTRAINT [DF_CPI07_NOMBR_I07]  DEFAULT (' ') FOR [NOMBR_I07]
GO
ALTER TABLE [dbo].[CPI07] ADD  CONSTRAINT [DF_CPI07_NULOT_I07]  DEFAULT (' ') FOR [NULOT_I07]
GO
ALTER TABLE [dbo].[CPI07] ADD  CONSTRAINT [DF_CPI07_TOTAL_I07]  DEFAULT (0) FOR [TOTAL_I07]
GO
ALTER TABLE [dbo].[CPI08] ADD  CONSTRAINT [DF_CPI08_IDCAB_I08]  DEFAULT (0) FOR [IDCAB_I08]
GO
ALTER TABLE [dbo].[CPI08] ADD  CONSTRAINT [DF_CPI08_MAEST_I08]  DEFAULT (' ') FOR [MAEST_I08]
GO
ALTER TABLE [dbo].[CPI08] ADD  CONSTRAINT [DF_CPI08_NUPRO_I08]  DEFAULT (' ') FOR [NUPRO_I08]
GO
ALTER TABLE [dbo].[CPI08] ADD  CONSTRAINT [DF_CPI08_CDDET_I08]  DEFAULT (' ') FOR [CDDET_I08]
GO
ALTER TABLE [dbo].[CPI08] ADD  CONSTRAINT [DF_CPI08_CTADT_I08]  DEFAULT (' ') FOR [CTADT_I08]
GO
ALTER TABLE [dbo].[CPI08] ADD  CONSTRAINT [DF_CPI08_IMPOR_I08]  DEFAULT (0) FOR [IMPOR_I08]
GO
ALTER TABLE [dbo].[CPI08] ADD  CONSTRAINT [DF_CPI08_CDTOP_I08]  DEFAULT (' ') FOR [CDTOP_I08]
GO
ALTER TABLE [dbo].[CPI09] ADD  CONSTRAINT [DF_CPI09_NULOT_I09]  DEFAULT (' ') FOR [NULOT_I09]
GO
ALTER TABLE [dbo].[CPI09] ADD  CONSTRAINT [DF_CPI09_NUMES_I09]  DEFAULT (' ') FOR [NUMES_I09]
GO
ALTER TABLE [dbo].[CPI09] ADD  CONSTRAINT [DF_CPI09_NUSEM_I09]  DEFAULT (' ') FOR [NUSEM_I09]
GO
ALTER TABLE [dbo].[CPI09] ADD  CONSTRAINT [DF_CPI09_TOTAV_I09]  DEFAULT (0) FOR [TOTAV_I09]
GO
ALTER TABLE [dbo].[CPI09] ADD  CONSTRAINT [DF_CPI09_TOTAG_I09]  DEFAULT (0) FOR [TOTAG_I09]
GO
ALTER TABLE [dbo].[CPI09] ADD  CONSTRAINT [DF_CPI09_TOTAL_I09]  DEFAULT (0) FOR [TOTAL_I09]
GO
ALTER TABLE [dbo].[CPI09] ADD  CONSTRAINT [DF_CPI09_USUAR_I09]  DEFAULT (' ') FOR [USUAR_I09]
GO
ALTER TABLE [dbo].[CPI09] ADD  CONSTRAINT [DF_CPI09_LOCAL_I01]  DEFAULT (' ') FOR [LOCAL_I09]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_IDCAB_I10]  DEFAULT (0) FOR [IDCAB_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_ITEM__I10]  DEFAULT (' ') FOR [ITEM__I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_MAEST_I10]  DEFAULT (' ') FOR [MAEST_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_DSMAE_I10]  DEFAULT (' ') FOR [DSMAE_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_TIDOC_I10]  DEFAULT (' ') FOR [TIDOC_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_SEDOC_I10]  DEFAULT (' ') FOR [SEDOC_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_NUDOC_I10]  DEFAULT (' ') FOR [NUDOC_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_OBSER_I10]  DEFAULT (' ') FOR [OBSER_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_VALDO_I10]  DEFAULT (0) FOR [VALDO_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_TICAM_I10]  DEFAULT (0) FOR [TICAM_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_VALSO_I10]  DEFAULT (0) FOR [VALSO_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_PORCE_I10]  DEFAULT (0) FOR [PORCE_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_TOTAL_I10]  DEFAULT (0) FOR [TOTAL_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_CTADT_I10]  DEFAULT (' ') FOR [CTADT_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_CDTOP_I10]  DEFAULT (' ') FOR [CDTOP_I10]
GO
ALTER TABLE [dbo].[CPI10] ADD  CONSTRAINT [DF_CPI10_RUBRO_I10]  DEFAULT (' ') FOR [RUBRO_I10]
GO
ALTER TABLE [dbo].[CPR01] ADD  CONSTRAINT [DF_CPR01_ABOSO_R01]  DEFAULT (0) FOR [ABOSO_R01]
GO
ALTER TABLE [dbo].[CPR01] ADD  CONSTRAINT [DF_CPR01_CARSO_R01]  DEFAULT (0) FOR [CARSO_R01]
GO
ALTER TABLE [dbo].[CPR01] ADD  CONSTRAINT [DF_CPR01_ABODO_R01]  DEFAULT (0) FOR [ABODO_R01]
GO
ALTER TABLE [dbo].[CPR01] ADD  CONSTRAINT [DF_CPR01_CARDO_R01]  DEFAULT (0) FOR [CARDO_R01]
GO
ALTER TABLE [dbo].[CPR01] ADD  CONSTRAINT [DF_CPR01_FLDCD_R01]  DEFAULT (0) FOR [FLDCD_R01]
GO
ALTER TABLE [dbo].[CPR02] ADD  CONSTRAINT [DF_CPR02A_SNSOL_R02]  DEFAULT (0) FOR [SNSOL_R02]
GO
ALTER TABLE [dbo].[CPR02] ADD  CONSTRAINT [DF_CPR02A_DBSOL_R02]  DEFAULT (0) FOR [DBSOL_R02]
GO
ALTER TABLE [dbo].[CPR02] ADD  CONSTRAINT [DF_CPR02A_HBSOL_R02]  DEFAULT (0) FOR [HBSOL_R02]
GO
ALTER TABLE [dbo].[CPR02] ADD  CONSTRAINT [DF_CPR02A_SASOL_R02]  DEFAULT (0) FOR [SASOL_R02]
GO
ALTER TABLE [dbo].[CPR02] ADD  CONSTRAINT [DF_CPR02A_SNDOL_R02]  DEFAULT (0) FOR [SNDOL_R02]
GO
ALTER TABLE [dbo].[CPR02] ADD  CONSTRAINT [DF_CPR02A_DBDOL_R02]  DEFAULT (0) FOR [DBDOL_R02]
GO
ALTER TABLE [dbo].[CPR02] ADD  CONSTRAINT [DF_CPR02A_HBDOL_R02]  DEFAULT (0) FOR [HBDOL_R02]
GO
ALTER TABLE [dbo].[CPR02] ADD  CONSTRAINT [DF_CPR02A_SADOL_R02]  DEFAULT (0) FOR [SADOL_R02]
GO
ALTER TABLE [dbo].[CPR02] ADD  CONSTRAINT [DF_CPR02A_DEBE__R02]  DEFAULT (0) FOR [DEBE__R02]
GO
ALTER TABLE [dbo].[CPR02] ADD  CONSTRAINT [DF_CPR02A_HABE__R02]  DEFAULT (0) FOR [HABE__R02]
GO
ALTER TABLE [dbo].[CPR02DDD] ADD  CONSTRAINT [DF_CPR02_DEB00_R02]  DEFAULT (0) FOR [DEBE__R02]
GO
ALTER TABLE [dbo].[CPR02DDD] ADD  CONSTRAINT [DF_CPR02_HAB00_R02]  DEFAULT (0) FOR [HABE__R02]
GO
ALTER TABLE [dbo].[CPT01] ADD  CONSTRAINT [DF_CPT01_RUBRO_T01]  DEFAULT (' ') FOR [RUBRO_T01]
GO
ALTER TABLE [dbo].[CPT01] ADD  CONSTRAINT [DF_CPT01_LOCAL_T01]  DEFAULT (' ') FOR [LOCAL_T01]
GO
ALTER TABLE [dbo].[CPT03] ADD  CONSTRAINT [DF_CPT03_PORCE_T03]  DEFAULT (0) FOR [PORCE_T03]
GO
ALTER TABLE [dbo].[CPT03] ADD  CONSTRAINT [DF_CPT03_AFIMP_T03]  DEFAULT (0) FOR [AFIMP_T03]
GO
ALTER TABLE [dbo].[CPT04] ADD  CONSTRAINT [DF_CPT04_RUBRO_T04]  DEFAULT (' ') FOR [RUBRO_T04]
GO
ALTER TABLE [dbo].[CPT05] ADD  CONSTRAINT [DF_CPT05_CODIG_T05]  DEFAULT (' ') FOR [CODIG_T05]
GO
ALTER TABLE [dbo].[CPT05] ADD  CONSTRAINT [DF_CPT05_DESCR_T05]  DEFAULT (' ') FOR [DESCR_T05]
GO
ALTER TABLE [dbo].[CPT05] ADD  CONSTRAINT [DF_CPT05_MONED_T05]  DEFAULT (' ') FOR [MONED_T05]
GO
ALTER TABLE [dbo].[CPT05] ADD  CONSTRAINT [DF_CPT05_SUBDI_T05]  DEFAULT (' ') FOR [SUBDI_T05]
GO
ALTER TABLE [dbo].[CPT05] ADD  CONSTRAINT [DF_CPT05_CUENT_T05]  DEFAULT (' ') FOR [CUENT_T05]
GO
ALTER TABLE [dbo].[CPT05] ADD  CONSTRAINT [DF_CPT05_CTIGV_T05]  DEFAULT (' ') FOR [CTIGV_T05]
GO
ALTER TABLE [dbo].[CPT05] ADD  CONSTRAINT [DF_CPT05_TANEX_T05]  DEFAULT (' ') FOR [TANEX_T05]
GO
ALTER TABLE [dbo].[CPT06] ADD  CONSTRAINT [DF_CPT06_CODIG_T06]  DEFAULT (' ') FOR [CODIG_T06]
GO
ALTER TABLE [dbo].[CPT06] ADD  CONSTRAINT [DF_CPT06_DESCR_T06]  DEFAULT (' ') FOR [DESCR_T06]
GO
ALTER TABLE [dbo].[CPT06] ADD  CONSTRAINT [DF_CPT06_MONED_T06]  DEFAULT (' ') FOR [MONED_T06]
GO
ALTER TABLE [dbo].[CPT06] ADD  CONSTRAINT [DF_CPT06_SUBDI_T06]  DEFAULT (' ') FOR [SUBDI_T06]
GO
ALTER TABLE [dbo].[CPT06] ADD  CONSTRAINT [DF_CPT06_CUENT_T06]  DEFAULT (' ') FOR [CUENT_T06]
GO
ALTER TABLE [dbo].[CPT06] ADD  CONSTRAINT [DF_CPT06_CTIGV_T06]  DEFAULT (' ') FOR [CTIGV_T06]
GO
ALTER TABLE [dbo].[CPT06] ADD  CONSTRAINT [DF_CPT06_TANEX_T06]  DEFAULT (' ') FOR [TANEX_T06]
GO
ALTER TABLE [dbo].[CPT06] ADD  CONSTRAINT [DF_CPT06_RUBRO_T06]  DEFAULT (' ') FOR [RUBRO_T06]
GO
ALTER TABLE [dbo].[CPT08] ADD  CONSTRAINT [DF_CPT08_FLSEC_T08]  DEFAULT (0) FOR [FLSEC_T08]
GO
ALTER TABLE [dbo].[CPW05] ADD  CONSTRAINT [DF_CPW05_CANTI_W05]  DEFAULT (0) FOR [SUBSO_W05]
GO
ALTER TABLE [dbo].[CPW05] ADD  CONSTRAINT [DF_CPW05_PRECI_W05]  DEFAULT (0) FOR [IGVSO_W05]
GO
ALTER TABLE [dbo].[CPW05] ADD  CONSTRAINT [DF_CPW05_SOLES_W05]  DEFAULT (0) FOR [OTSSO_W05]
GO
ALTER TABLE [dbo].[CPW05] ADD  CONSTRAINT [DF_CPW05_DOLAR_W05]  DEFAULT (0) FOR [VALSO_W05]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_VOUCH_W06]  DEFAULT (' ') FOR [VOUCH_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_NOMBR_W06]  DEFAULT (' ') FOR [NOMBR_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_TIDOC_W06]  DEFAULT (' ') FOR [TIDOC_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_SEDOC_W06]  DEFAULT (' ') FOR [SEDOC_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_NUDOC_W06]  DEFAULT (' ') FOR [NUDOC_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_OBSER_W06]  DEFAULT (' ') FOR [OBSER_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_VALDO_W06]  DEFAULT (0) FOR [VALDO_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_TICAM_W06]  DEFAULT (0) FOR [TICAM_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_VALSO_W06]  DEFAULT (0) FOR [VALSO_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_PORCE_W06]  DEFAULT (0) FOR [PORCE_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_SOLES_W06]  DEFAULT (0) FOR [SOLES_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_CTADT_W06]  DEFAULT (' ') FOR [CTADT_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_NDPAG_W06]  DEFAULT (' ') FOR [NDPAG_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_MAEST_W06]  DEFAULT (' ') FOR [MAEST_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_ABREV_W06]  DEFAULT (' ') FOR [ABREV_W06]
GO
ALTER TABLE [dbo].[CPW06] ADD  CONSTRAINT [DF_CPW06_CDDET_W06]  DEFAULT (' ') FOR [CDDET_W06]
GO
ALTER TABLE [dbo].[CPI02]  WITH NOCHECK ADD  CONSTRAINT [FK_CPI02_CPI01] FOREIGN KEY([IDCAB_I02])
REFERENCES [dbo].[CPI01] ([IDCAB_I01])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CPI02] CHECK CONSTRAINT [FK_CPI02_CPI01]
GO
ALTER TABLE [dbo].[CPI03]  WITH NOCHECK ADD  CONSTRAINT [FK_CPI03_CPI01] FOREIGN KEY([IDCAB_I03])
REFERENCES [dbo].[CPI01] ([IDCAB_I01])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CPI03] CHECK CONSTRAINT [FK_CPI03_CPI01]
GO
ALTER TABLE [dbo].[CPI04]  WITH NOCHECK ADD  CONSTRAINT [FK_CPI04_CPI01] FOREIGN KEY([IDCAB_I04])
REFERENCES [dbo].[CPI01] ([IDCAB_I01])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CPI04] CHECK CONSTRAINT [FK_CPI04_CPI01]
GO
ALTER TABLE [dbo].[CPI05]  WITH NOCHECK ADD  CONSTRAINT [FK_CPI05_CPI01] FOREIGN KEY([IDCAB_I05])
REFERENCES [dbo].[CPI01] ([IDCAB_I01])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CPI05] CHECK CONSTRAINT [FK_CPI05_CPI01]
GO
ALTER TABLE [dbo].[CPI08]  WITH CHECK ADD  CONSTRAINT [FK_CPI08_CPI07] FOREIGN KEY([IDCAB_I08])
REFERENCES [dbo].[CPI07] ([IDCAB_I07])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CPI08] CHECK CONSTRAINT [FK_CPI08_CPI07]
GO
ALTER TABLE [dbo].[CPI10]  WITH NOCHECK ADD  CONSTRAINT [FK_CPI10_CPI09] FOREIGN KEY([IDCAB_I10])
REFERENCES [dbo].[CPI09] ([IDCAB_I09])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CPI10] CHECK CONSTRAINT [FK_CPI10_CPI09]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FLAG INDICA SI SE HA PROGRAMADO PAGO DE DETRACCIONES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPI01', @level2type=N'COLUMN',@level2name=N'FLPPD_I01'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FORMA DE PAGO DETRACCIONES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPI01', @level2type=N'COLUMN',@level2name=N'FPDET_I01'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'PORCENTAJE IGV' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPI01', @level2type=N'COLUMN',@level2name=N'POIGV_I01'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'fecah de vencimiento original' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPI01', @level2type=N'COLUMN',@level2name=N'FVORI_I01'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N''' ''' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPI02', @level2type=N'COLUMN',@level2name=N'COSTO_I02'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N''' ''' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPI02', @level2type=N'COLUMN',@level2name=N'MAEST_I02'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N''' ''' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPI02', @level2type=N'COLUMN',@level2name=N'REFER_I02'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FLAG INDICA SI ES UN DOCUMENTO FEC' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPI02', @level2type=N'COLUMN',@level2name=N'FLFEC_I02'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FLAG INDICA SI EL FEC ESTA CANCELADO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPI02', @level2type=N'COLUMN',@level2name=N'FLCNF_I02'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'0' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPR01', @level2type=N'COLUMN',@level2name=N'CARSO_R01'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DEBE ANTERIOR SOLES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPR02DDD', @level2type=N'COLUMN',@level2name=N'DEBE__R02'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'HABER ANTERIOR SOLES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPR02DDD', @level2type=N'COLUMN',@level2name=N'HABE__R02'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FLAG QUE INDICA SI ESTA AFECTO A IMPUESTOS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPT03', @level2type=N'COLUMN',@level2name=N'AFIMP_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FLAG INDICA SI SE PAGA POR SECHUM' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CPT08', @level2type=N'COLUMN',@level2name=N'FLSEC_T08'
GO
USE [master]
GO
ALTER DATABASE [CP] SET  READ_WRITE 
GO
