USE [master]
GO
/****** Object:  Database [CT]    Script Date: 18/02/2023 19:49:28 ******/
CREATE DATABASE [CT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CT_Data', FILENAME = N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\CT.MDF' , SIZE = 4026880KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'CT_Log', FILENAME = N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\CT_1.LDF' , SIZE = 52416KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
ALTER DATABASE [CT] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CT].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [CT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CT] SET ARITHABORT OFF 
GO
ALTER DATABASE [CT] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [CT] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [CT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CT] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CT] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CT] SET  MULTI_USER 
GO
ALTER DATABASE [CT] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [CT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CT] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CT] SET QUERY_STORE = OFF
GO
USE [CT]
GO
/****** Object:  User [vvasquez]    Script Date: 18/02/2023 19:49:28 ******/
CREATE USER [vvasquez] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[vvasquez]
GO
/****** Object:  User [user]    Script Date: 18/02/2023 19:49:28 ******/
CREATE USER [user] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[user]
GO
/****** Object:  User [sqlbackup]    Script Date: 18/02/2023 19:49:28 ******/
CREATE USER [sqlbackup] WITH DEFAULT_SCHEMA=[sqlbackup]
GO
/****** Object:  User [migarcia]    Script Date: 18/02/2023 19:49:28 ******/
CREATE USER [migarcia] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[migarcia]
GO
/****** Object:  User [consulta]    Script Date: 18/02/2023 19:49:28 ******/
CREATE USER [consulta] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[consulta]
GO
ALTER ROLE [db_datareader] ADD MEMBER [vvasquez]
GO
ALTER ROLE [db_owner] ADD MEMBER [user]
GO
ALTER ROLE [db_datareader] ADD MEMBER [migarcia]
GO
ALTER ROLE [db_owner] ADD MEMBER [consulta]
GO
/****** Object:  Schema [consulta]    Script Date: 18/02/2023 19:49:28 ******/
CREATE SCHEMA [consulta]
GO
/****** Object:  Schema [migarcia]    Script Date: 18/02/2023 19:49:28 ******/
CREATE SCHEMA [migarcia]
GO
/****** Object:  Schema [sqlbackup]    Script Date: 18/02/2023 19:49:28 ******/
CREATE SCHEMA [sqlbackup]
GO
/****** Object:  Schema [user]    Script Date: 18/02/2023 19:49:28 ******/
CREATE SCHEMA [user]
GO
/****** Object:  Schema [vvasquez]    Script Date: 18/02/2023 19:49:28 ******/
CREATE SCHEMA [vvasquez]
GO
/****** Object:  Table [dbo].[CTR12]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTR12](
	[IDCAB_R12] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TCONS_R12] [varchar](2) NOT NULL,
	[TDIST_R12] [varchar](2) NOT NULL,
	[PERIO_R12] [varchar](7) NOT NULL,
	[FUNDO_R12] [varchar](2) NOT NULL,
	[DSFDO_R12] [varchar](50) NULL,
	[CULTI_R12] [varchar](4) NULL,
	[DSCUL_R12] [varchar](50) NULL,
	[VARIE_R12] [varchar](6) NULL,
	[DSVAR_R12] [varchar](50) NULL,
	[LOTE__R12] [varchar](8) NOT NULL,
	[DSLOT_R12] [varchar](100) NULL,
	[FEDOC_R12] [datetime] NULL,
	[CLSN1_R12] [varchar](2) NOT NULL,
	[DCLN1_R12] [varchar](50) NULL,
	[CLSN2_R12] [varchar](3) NOT NULL,
	[DCLN2_R12] [varchar](50) NULL,
	[CLSN3_R12] [varchar](4) NOT NULL,
	[DCLN3_R12] [varchar](50) NULL,
	[CODMA_R12] [varchar](9) NULL,
	[DESMA_R12] [varchar](100) NULL,
	[SOLES_R12] [float] NULL,
	[CAMPA_R12] [varchar](20) NULL,
	[CODUG_R12] [varchar](2) NULL,
	[CANTI_R12] [float] NULL,
 CONSTRAINT [PK_CTR12] PRIMARY KEY CLUSTERED 
(
	[IDCAB_R12] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[COSTOS_DIR_E_IND_VIEW]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[COSTOS_DIR_E_IND_VIEW]
AS
SELECT     dbo.CTR12.TCONS_R12, dbo.CTR12.TDIST_R12, dbo.CTR12.PERIO_R12, dbo.CTR12.FUNDO_R12, dbo.CTR12.DSFDO_R12, dbo.CTR12.CULTI_R12, 
                      dbo.CTR12.DSCUL_R12, dbo.CTR12.VARIE_R12, dbo.CTR12.DSVAR_R12, dbo.CTR12.LOTE__R12, dbo.CTR12.DSLOT_R12, dbo.CTR12.FEDOC_R12, 
                      dbo.CTR12.CLSN1_R12, dbo.CTR12.DCLN1_R12, dbo.CTR12.CLSN2_R12, dbo.CTR12.DCLN2_R12, dbo.CTR12.CLSN3_R12, dbo.CTR12.DCLN3_R12, 
                      dbo.CTR12.CODMA_R12, dbo.CTR12.DESMA_R12, dbo.CTR12.SOLES_R12, dbo.CTR12.CAMPA_R12, PR.dbo.PRT15.DESCR_T15, 
                      dbo.CTR12.CODUG_R12, dbo.CTR12.CANTI_R12
FROM         dbo.CTR12 INNER JOIN
                      PR.dbo.PRT15 INNER JOIN
                      PR.dbo.PRT08 ON PR.dbo.PRT15.CAMPA_T15 = PR.dbo.PRT08.ABREV_T08 ON dbo.CTR12.CAMPA_R12 = PR.dbo.PRT15.ABREV_T15
WHERE     (dbo.CTR12.PERIO_R12 >= '2018-01')
GO
/****** Object:  Table [dbo].[CTR01]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTR01](
	[COSTO] [nvarchar](8) NULL,
	[CAMPO] [nvarchar](50) NULL,
	[SEMANA] [nvarchar](50) NULL,
	[SumaDeTOTAL] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTR02]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTR02](
	[LOCAL_R02] [char](2) NULL,
	[PERIO_R02] [char](7) NULL,
	[CAMPO_R02] [char](8) NULL,
	[DSCAM_R02] [varchar](50) NULL,
	[TIPOC_R02] [char](2) NULL,
	[DSTIC_R02] [varchar](50) NULL,
	[RUBRO_R02] [char](8) NULL,
	[DSRUB_R02] [varchar](50) NULL,
	[HORAS_R02] [float] NULL,
	[VALOR_R02] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTR03]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTR03](
	[TRABA_R03] [varchar](100) NULL,
	[SEMAN_R03] [char](7) NULL,
	[DEL___R03] [datetime] NULL,
	[AL____R03] [datetime] NULL,
	[CENTR_R03] [varchar](50) NULL,
	[TOTAL_R03] [float] NULL,
	[TPLLA_R03] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTR10]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTR10](
	[IDCAB_R10] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TDIST_R10] [varchar](2) NOT NULL,
	[PERIO_R10] [varchar](7) NOT NULL,
	[LOTE__R10] [varchar](8) NOT NULL,
	[COSTO_R10] [varchar](8) NOT NULL,
	[FEDOC_R10] [datetime] NULL,
	[CLASE_R10] [varchar](4) NOT NULL,
	[CODMA_R10] [varchar](9) NOT NULL,
	[HECTA_R10] [float] NULL,
	[SOLES_R10] [float] NULL,
	[CAMPA_R10] [varchar](20) NULL,
	[CANTI_R10] [float] NULL,
 CONSTRAINT [PK_CTR10] PRIMARY KEY CLUSTERED 
(
	[IDCAB_R10] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTR11]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTR11](
	[IDCAB_R11] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TDIST_R11] [varchar](2) NOT NULL,
	[PERIO_R11] [varchar](7) NOT NULL,
	[MAQUI_R11] [varchar](2) NOT NULL,
	[LOTE__R11] [varchar](8) NOT NULL,
	[COSTO_R11] [varchar](8) NOT NULL,
	[FEDOC_R11] [datetime] NULL,
	[CLASE_R11] [varchar](4) NULL,
	[CODMA_R11] [varchar](9) NULL,
	[HORAS_R11] [float] NULL,
	[SOLES_R11] [float] NULL,
	[CAMPA_R11] [varchar](20) NULL,
 CONSTRAINT [PK_CTR11] PRIMARY KEY CLUSTERED 
(
	[IDCAB_R11] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTR13]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTR13](
	[IDCAB_R13] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TIOPE_R13] [varchar](2) NULL,
	[TIPOC_R13] [varchar](1) NOT NULL,
	[PERIO_R13] [varchar](7) NOT NULL,
	[FUNDO_R13] [varchar](2) NOT NULL,
	[CULTI_R13] [varchar](4) NOT NULL,
	[VARIE_R13] [varchar](6) NOT NULL,
	[LOTE__R13] [varchar](8) NOT NULL,
	[FEDOC_R13] [datetime] NULL,
	[CLSN1_R13] [varchar](2) NULL,
	[CLSN2_R13] [varchar](3) NULL,
	[CLASE_R13] [varchar](4) NOT NULL,
	[CUENT_R13] [varchar](8) NOT NULL,
	[DEBE__R13] [float] NULL,
	[HABER_R13] [float] NULL,
	[CAMPA_R13] [varchar](20) NULL,
	[CODUG_R13] [varchar](2) NULL,
 CONSTRAINT [PK_CTR13] PRIMARY KEY CLUSTERED 
(
	[IDCAB_R13] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTR14]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTR14](
	[IDCAB_R14] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TIOPE_R14] [varchar](2) NULL,
	[TIPOC_R14] [varchar](1) NOT NULL,
	[PERIO_R14] [varchar](7) NOT NULL,
	[FUNDO_R14] [varchar](2) NOT NULL,
	[CULTI_R14] [varchar](4) NOT NULL,
	[VARIE_R14] [varchar](6) NOT NULL,
	[LOTE__R14] [varchar](8) NOT NULL,
	[FEDOC_R14] [datetime] NULL,
	[CLSN1_R14] [varchar](2) NULL,
	[CLSN2_R14] [varchar](3) NULL,
	[CLASE_R14] [varchar](4) NOT NULL,
	[CUENT_R14] [varchar](8) NOT NULL,
	[GASTO_R14] [varchar](8) NULL,
	[DEBE__R14] [float] NULL,
	[HABER_R14] [float] NULL,
	[CAMPA_R14] [varchar](20) NULL,
	[CODUG_R14] [varchar](2) NULL,
	[TIDOC_R14] [varchar](2) NULL,
	[NUSER_R14] [varchar](4) NULL,
	[NUDOC_R14] [varchar](8) NULL,
	[GLOSA_R14] [varchar](50) NULL,
	[FEMIS_R14] [datetime] NULL,
 CONSTRAINT [PK_CTR14] PRIMARY KEY CLUSTERED 
(
	[IDCAB_R14] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTT10]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTT10](
	[CODIG_T10] [varchar](2) NOT NULL,
	[DESCR_T10] [varchar](50) NULL,
	[ABREV_T10] [varchar](20) NULL,
 CONSTRAINT [PK_CTT10] PRIMARY KEY CLUSTERED 
(
	[CODIG_T10] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTT11]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTT11](
	[CODIG_T11] [varchar](2) NOT NULL,
	[DESCR_T11] [varchar](50) NULL,
	[ABREV_T11] [varchar](30) NULL,
 CONSTRAINT [PK_CTT11] PRIMARY KEY CLUSTERED 
(
	[CODIG_T11] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTT12]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTT12](
	[CODIG_T12] [varchar](2) NOT NULL,
	[DESCR_T12] [varchar](50) NULL,
	[ABREV_T12] [varchar](20) NULL,
 CONSTRAINT [PK_CTT12] PRIMARY KEY CLUSTERED 
(
	[CODIG_T12] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTT13]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTT13](
	[CODIG_T13] [varchar](2) NOT NULL,
	[DESCR_T13] [varchar](50) NULL,
	[abrev_t13] [varchar](10) NULL,
 CONSTRAINT [PK_CTT13] PRIMARY KEY CLUSTERED 
(
	[CODIG_T13] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTW01]    Script Date: 18/02/2023 19:49:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTW01](
	[IDCAB_W01] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TCONS_W01] [varchar](2) NOT NULL,
	[TDIST_W01] [varchar](2) NOT NULL,
	[PERIO_W01] [varchar](7) NOT NULL,
	[FUNDO_W01] [varchar](2) NOT NULL,
	[DSFDO_W01] [varchar](50) NULL,
	[CULTI_W01] [varchar](4) NULL,
	[DSCUL_W01] [varchar](50) NULL,
	[VARIE_W01] [varchar](6) NULL,
	[DSVAR_W01] [varchar](50) NULL,
	[LOTE__W01] [varchar](8) NOT NULL,
	[DSLOT_W01] [varchar](50) NULL,
	[FEDOC_W01] [datetime] NULL,
	[CLSN1_W01] [varchar](2) NOT NULL,
	[DCLN1_W01] [varchar](50) NULL,
	[CLSN2_W01] [varchar](3) NOT NULL,
	[DCLN2_W01] [varchar](50) NULL,
	[CLSN3_W01] [varchar](4) NOT NULL,
	[DCLN3_W01] [varchar](50) NULL,
	[CODMA_W01] [varchar](9) NULL,
	[DESMA_W01] [varchar](100) NULL,
	[SOLES_W01] [float] NULL,
	[CAMPA_W01] [varchar](20) NULL,
	[CODUG_W01] [varchar](2) NULL,
	[USUAR_W01] [varchar](20) NULL,
	[COMPU_W01] [varchar](50) NULL,
	[CANTI_W01] [float] NULL,
	[DESDE_W01] [datetime] NULL,
	[HASTA_W01] [datetime] NULL,
	[LTFDH_W01] [varchar](30) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTR02] ADD  CONSTRAINT [DF_CTR02_HORAS_R02]  DEFAULT (0) FOR [HORAS_R02]
GO
ALTER TABLE [dbo].[CTR02] ADD  CONSTRAINT [DF_CTR01_VALOR_R01]  DEFAULT (0) FOR [VALOR_R02]
GO
ALTER TABLE [dbo].[CTR03] ADD  CONSTRAINT [DF_CTR03_SEMAN_R03]  DEFAULT (' ') FOR [SEMAN_R03]
GO
ALTER TABLE [dbo].[CTR03] ADD  CONSTRAINT [DF_CTR03_CENTR_R03]  DEFAULT (' ') FOR [CENTR_R03]
GO
ALTER TABLE [dbo].[CTR03] ADD  CONSTRAINT [DF_CTR03_TOTAL_R03]  DEFAULT (0) FOR [TOTAL_R03]
GO
ALTER TABLE [dbo].[CTR03] ADD  CONSTRAINT [DF_CTR03_TPLLA_R03]  DEFAULT (' ') FOR [TPLLA_R03]
GO
ALTER TABLE [dbo].[CTR10] ADD  CONSTRAINT [DF_CTR10_CANTI_R10]  DEFAULT (0) FOR [CANTI_R10]
GO
ALTER TABLE [dbo].[CTR12] ADD  CONSTRAINT [DF_CTR12_CANTI_R12]  DEFAULT (0) FOR [CANTI_R12]
GO
ALTER TABLE [dbo].[CTW01] ADD  CONSTRAINT [DF_CTW01_CANTI_W01]  DEFAULT (0) FOR [CANTI_W01]
GO
USE [master]
GO
ALTER DATABASE [CT] SET  READ_WRITE 
GO
