USE [master]
GO
/****** Object:  Database [PL]    Script Date: 18/02/2023 19:52:05 ******/
CREATE DATABASE [PL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PL_Data', FILENAME = N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\PL.MDF' , SIZE = 3456KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'PL_Log', FILENAME = N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\PL.LDF' , SIZE = 3840KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
ALTER DATABASE [PL] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PL].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [PL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PL] SET ARITHABORT OFF 
GO
ALTER DATABASE [PL] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [PL] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [PL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PL] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PL] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PL] SET  MULTI_USER 
GO
ALTER DATABASE [PL] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [PL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PL] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [PL] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PL] SET QUERY_STORE = OFF
GO
USE [PL]
GO
/****** Object:  User [user]    Script Date: 18/02/2023 19:52:05 ******/
CREATE USER [user] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[user]
GO
/****** Object:  User [sqlbackup]    Script Date: 18/02/2023 19:52:05 ******/
CREATE USER [sqlbackup] WITH DEFAULT_SCHEMA=[sqlbackup]
GO
/****** Object:  User [COPACABANA\rcervantes]    Script Date: 18/02/2023 19:52:05 ******/
CREATE USER [COPACABANA\rcervantes] FOR LOGIN [COPACABANA\rcervantes] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  User [consulta]    Script Date: 18/02/2023 19:52:05 ******/
CREATE USER [consulta] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[consulta]
GO
ALTER ROLE [db_owner] ADD MEMBER [user]
GO
ALTER ROLE [db_owner] ADD MEMBER [consulta]
GO
/****** Object:  Schema [consulta]    Script Date: 18/02/2023 19:52:06 ******/
CREATE SCHEMA [consulta]
GO
/****** Object:  Schema [sqlbackup]    Script Date: 18/02/2023 19:52:06 ******/
CREATE SCHEMA [sqlbackup]
GO
/****** Object:  Schema [user]    Script Date: 18/02/2023 19:52:06 ******/
CREATE SCHEMA [user]
GO
/****** Object:  Table [dbo].[PLR50]    Script Date: 18/02/2023 19:52:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLR50](
	[IDCAB_R50] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PERIO_R50] [varchar](7) NULL,
	[DESCR_R50] [varchar](100) NULL,
	[NEMPL_R50] [varchar](100) NULL,
	[BASIC_R50] [float] NULL,
	[AFAMI_R50] [float] NULL,
	[RESPO_R50] [float] NULL,
	[TURNO_R50] [float] NULL,
	[BAMES_R50] [float] NULL,
	[AFMES_R50] [float] NULL,
	[REMES_R50] [float] NULL,
	[TUMES_R50] [float] NULL,
	[RBRUT_R50] [float] NULL,
	[GRATI_R50] [float] NULL,
	[SGRAT_R50] [float] NULL,
	[RCOMP_R50] [float] NULL,
	[MESES_R50] [int] NULL,
	[TOCTS_R50] [float] NULL,
	[T1CTS_R50] [float] NULL,
	[RJUDI_R50] [float] NULL,
	[CTSNT_R50] [float] NULL,
	[CUENT_R50] [varchar](50) NULL,
	[TIPOT_R50] [varchar](1) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PLR51]    Script Date: 18/02/2023 19:52:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLR51](
	[IDCAB_R51] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PERIO_R51] [varchar](4) NOT NULL,
	[RAEAI_R51] [float] NULL,
	[PTCEA_R51] [float] NULL,
	[RBAAI_R51] [float] NULL,
	[PORDI_R51] [int] NULL,
	[MONDI_R51] [float] NULL,
	[NTDLE_R51] [int] NULL,
	[RCTPE_R51] [float] NULL,
 CONSTRAINT [PK_PLR51] PRIMARY KEY CLUSTERED 
(
	[PERIO_R51] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PLR52]    Script Date: 18/02/2023 19:52:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLR52](
	[IDCAB_R52] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PERIO_R52] [varchar](4) NULL,
	[NOMBR_R52] [varchar](100) NULL,
	[RUBRO_R52] [varchar](20) NULL,
	[NDLET_R52] [int] NULL,
	[PTSDL_R52] [float] NULL,
	[RCTPT_R52] [float] NULL,
	[PTSRP_R52] [float] NULL,
	[TOTAL_R52] [float] NULL,
	[TIPOT_R52] [varchar](1) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PLR53]    Script Date: 18/02/2023 19:52:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLR53](
	[IDCAB_R53] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PERIO_R53] [varchar](7) NULL,
	[DESCR_R53] [varchar](100) NULL,
	[NEMPL_R53] [varchar](100) NULL,
	[BASIC_R53] [float] NULL,
	[AFAMI_R53] [float] NULL,
	[RESPO_R53] [float] NULL,
	[TURNO_R53] [float] NULL,
	[BAMES_R53] [float] NULL,
	[AFMES_R53] [float] NULL,
	[REMES_R53] [float] NULL,
	[TUMES_R53] [float] NULL,
	[RBRUT_R53] [float] NULL,
	[CTSGR_R53] [float] NULL,
	[CTCTS_R53] [float] NULL,
	[CTNME_R53] [float] NULL,
	[CTPAG_R53] [float] NULL,
	[CGBO9_R53] [float] NULL,
	[CGMCO_R53] [float] NULL,
	[CGNME_R53] [float] NULL,
	[CGGTR_R53] [float] NULL,
	[CGAMA_R53] [float] NULL,
	[CGGRA_R53] [float] NULL,
	[CVFIN_R53] [datetime] NULL,
	[CVFCE_R53] [datetime] NULL,
	[CVNME_R53] [float] NULL,
	[CVMCO_R53] [float] NULL,
	[CVPOR_R53] [float] NULL,
	[CVDAO_R53] [float] NULL,
	[CV5TA_R53] [float] NULL,
	[CVPAG_R53] [float] NULL,
	[TOLIQ_R53] [float] NULL,
	[RETJU_R53] [float] NULL,
	[PTMPE_R53] [float] NULL,
	[CUENT_R53] [varchar](50) NULL,
	[TIPOT_R53] [varchar](1) NULL,
 CONSTRAINT [PK_PLR53] PRIMARY KEY CLUSTERED 
(
	[IDCAB_R53] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_PERIO_R50]  DEFAULT (' ') FOR [PERIO_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_DESCR_R50]  DEFAULT (' ') FOR [DESCR_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_NEMPL_R50]  DEFAULT (' ') FOR [NEMPL_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_BASIC_R50]  DEFAULT (0) FOR [BASIC_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_AFAMI_R50]  DEFAULT (0) FOR [AFAMI_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_RESPO_R50]  DEFAULT (0) FOR [RESPO_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_TURNO_R50]  DEFAULT (0) FOR [TURNO_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_BAMES_R50]  DEFAULT (0) FOR [BAMES_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_AFMES_R50]  DEFAULT (0) FOR [AFMES_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_REMES_R50]  DEFAULT (0) FOR [REMES_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_TUMES_R50]  DEFAULT (0) FOR [TUMES_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_RBRUT_R50]  DEFAULT (0) FOR [RBRUT_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_GRATI_R50]  DEFAULT (0) FOR [GRATI_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_SGRAT_R50]  DEFAULT (0) FOR [SGRAT_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_RCOMP_R50]  DEFAULT (0) FOR [RCOMP_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_MESES_R50]  DEFAULT (0) FOR [MESES_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_TOCTS_R50]  DEFAULT (0) FOR [TOCTS_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_T1CTS_R50]  DEFAULT (0) FOR [T1CTS_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_RJUDI_R50]  DEFAULT (0) FOR [RJUDI_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_CTSNT_R50]  DEFAULT (0) FOR [CTSNT_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_CUENT_R50]  DEFAULT (' ') FOR [CUENT_R50]
GO
ALTER TABLE [dbo].[PLR50] ADD  CONSTRAINT [DF_PLR50_TIPOT_R50]  DEFAULT (' ') FOR [TIPOT_R50]
GO
ALTER TABLE [dbo].[PLR51] ADD  CONSTRAINT [DF_PLR51_PERIO_R51]  DEFAULT (' ') FOR [PERIO_R51]
GO
ALTER TABLE [dbo].[PLR51] ADD  CONSTRAINT [DF_PLR51_RAEAI_R51]  DEFAULT (0) FOR [RAEAI_R51]
GO
ALTER TABLE [dbo].[PLR51] ADD  CONSTRAINT [DF_PLR51_PTCEA_R51]  DEFAULT (0) FOR [PTCEA_R51]
GO
ALTER TABLE [dbo].[PLR51] ADD  CONSTRAINT [DF_PLR51_RBAAI_R51]  DEFAULT (0) FOR [RBAAI_R51]
GO
ALTER TABLE [dbo].[PLR51] ADD  CONSTRAINT [DF_PLR51_PORDI_R51]  DEFAULT (0) FOR [PORDI_R51]
GO
ALTER TABLE [dbo].[PLR51] ADD  CONSTRAINT [DF_PLR51_MONDI_R51]  DEFAULT (0) FOR [MONDI_R51]
GO
ALTER TABLE [dbo].[PLR51] ADD  CONSTRAINT [DF_PLR51_NTDLE_R51]  DEFAULT (0) FOR [NTDLE_R51]
GO
ALTER TABLE [dbo].[PLR51] ADD  CONSTRAINT [DF_PLR51_RCTPE_R51]  DEFAULT (0) FOR [RCTPE_R51]
GO
ALTER TABLE [dbo].[PLR52] ADD  CONSTRAINT [DF_PLR52_PERIO_R52]  DEFAULT (' ') FOR [PERIO_R52]
GO
ALTER TABLE [dbo].[PLR52] ADD  CONSTRAINT [DF_PLR52_NOMBR_R52]  DEFAULT (' ') FOR [NOMBR_R52]
GO
ALTER TABLE [dbo].[PLR52] ADD  CONSTRAINT [DF_PLR52_RUBRO_R52]  DEFAULT (' ') FOR [RUBRO_R52]
GO
ALTER TABLE [dbo].[PLR52] ADD  CONSTRAINT [DF_PLR52_NDLET_R52]  DEFAULT (0) FOR [NDLET_R52]
GO
ALTER TABLE [dbo].[PLR52] ADD  CONSTRAINT [DF_PLR52_PTSDL_R52]  DEFAULT (0) FOR [PTSDL_R52]
GO
ALTER TABLE [dbo].[PLR52] ADD  CONSTRAINT [DF_PLR52_RCTPT_R52]  DEFAULT (0) FOR [RCTPT_R52]
GO
ALTER TABLE [dbo].[PLR52] ADD  CONSTRAINT [DF_PLR52_PTSRP_R52]  DEFAULT (0) FOR [PTSRP_R52]
GO
ALTER TABLE [dbo].[PLR52] ADD  CONSTRAINT [DF_PLR52_TOTAL_R52]  DEFAULT (0) FOR [TOTAL_R52]
GO
ALTER TABLE [dbo].[PLR52] ADD  CONSTRAINT [DF_PLR52_TIPOT_R52]  DEFAULT (' ') FOR [TIPOT_R52]
GO
USE [master]
GO
ALTER DATABASE [PL] SET  READ_WRITE 
GO
