USE [master]
GO
/****** Object:  Database [PR]    Script Date: 18/02/2023 19:52:59 ******/
CREATE DATABASE [PR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PR_Data', FILENAME = N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\PR.MDF' , SIZE = 8896KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'PR_Log', FILENAME = N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\PR.LDF' , SIZE = 5184KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
ALTER DATABASE [PR] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PR].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [PR] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PR] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PR] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PR] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PR] SET ARITHABORT OFF 
GO
ALTER DATABASE [PR] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [PR] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [PR] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PR] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PR] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PR] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PR] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PR] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PR] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PR] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PR] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PR] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PR] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PR] SET  MULTI_USER 
GO
ALTER DATABASE [PR] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [PR] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PR] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [PR] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PR] SET QUERY_STORE = OFF
GO
USE [PR]
GO
/****** Object:  User [wbuenano]    Script Date: 18/02/2023 19:53:00 ******/
CREATE USER [wbuenano] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[wbuenano]
GO
/****** Object:  User [user]    Script Date: 18/02/2023 19:53:00 ******/
CREATE USER [user] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[user]
GO
/****** Object:  User [sqlbackup]    Script Date: 18/02/2023 19:53:00 ******/
CREATE USER [sqlbackup] WITH DEFAULT_SCHEMA=[sqlbackup]
GO
/****** Object:  User [consulta]    Script Date: 18/02/2023 19:53:00 ******/
CREATE USER [consulta] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[consulta]
GO
ALTER ROLE [db_owner] ADD MEMBER [wbuenano]
GO
ALTER ROLE [db_owner] ADD MEMBER [user]
GO
ALTER ROLE [db_owner] ADD MEMBER [sqlbackup]
GO
ALTER ROLE [db_owner] ADD MEMBER [consulta]
GO
/****** Object:  Schema [consulta]    Script Date: 18/02/2023 19:53:00 ******/
CREATE SCHEMA [consulta]
GO
/****** Object:  Schema [sqlbackup]    Script Date: 18/02/2023 19:53:00 ******/
CREATE SCHEMA [sqlbackup]
GO
/****** Object:  Schema [user]    Script Date: 18/02/2023 19:53:00 ******/
CREATE SCHEMA [user]
GO
/****** Object:  Schema [wbuenano]    Script Date: 18/02/2023 19:53:00 ******/
CREATE SCHEMA [wbuenano]
GO
/****** Object:  Table [dbo].[_PRI34]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[_PRI34](
	[IDCAB_I34] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PERIO_I34] [char](7) NULL,
	[FEREG_I34] [datetime] NULL,
	[OVENT_I34] [char](8) NULL,
	[FECHA_I34] [datetime] NULL,
	[MAEST_I34] [char](11) NULL,
	[SEGUI_I34] [char](4) NULL,
	[NUGUI_I34] [char](8) NULL,
	[TOTCJ_I34] [float] NULL,
	[TOTSO_I34] [float] NULL,
	[VOUCH_I34] [char](12) NULL,
	[TOTKG_I34] [float] NULL,
	[STATU_I34] [char](12) NULL,
 CONSTRAINT [PK_PRI34] PRIMARY KEY CLUSTERED 
(
	[IDCAB_I34] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[_PRI35]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[_PRI35](
	[IDDET_I35] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I35] [int] NULL,
	[CAJAS_I35] [float] NULL,
	[ENVAS_I35] [char](15) NULL,
	[PRODU_I35] [char](6) NULL,
	[CALID_I35] [char](15) NULL,
	[KILOS_I35] [float] NULL,
	[CAMPO_I35] [char](8) NULL,
	[PRECI_I35] [float] NULL,
	[SUBTO_I35] [float] NULL,
 CONSTRAINT [PK_PRI35] PRIMARY KEY CLUSTERED 
(
	[IDDET_I35] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[_PRI43]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[_PRI43](
	[IDDET_I43] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I43] [int] NULL,
	[MAEST_I43] [varchar](11) NULL,
	[DESCR_I43] [varchar](50) NULL,
	[STATU_I43] [varchar](20) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[_PRM01]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[_PRM01](
	[EMPRE_M01] [char](2) NOT NULL,
	[CODIG_M01] [char](6) NOT NULL,
	[DESCR_M01] [char](50) NULL,
	[ABREV_M01] [char](10) NULL,
	[UNIDA_M01] [char](10) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[_PRT05]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[_PRT05](
	[CODIG_T05] [char](2) NOT NULL,
	[DESCR_T05] [char](30) NULL,
	[ABREV_T05] [char](10) NULL,
	[PRODU_T05] [char](6) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[_PRT06]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[_PRT06](
	[CODIG_T06] [char](2) NOT NULL,
	[DESCR_T06] [char](30) NULL,
	[ABREV_T06] [char](10) NULL,
	[UNIDA_T06] [char](2) NULL,
	[VALOR_T06] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI30]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI30](
	[IDCAB_I30] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[LOCAL_I30] [char](2) NULL,
	[PERIO_I30] [char](7) NULL,
	[VOUCH_I30] [char](12) NULL,
	[FEREG_I30] [datetime] NULL,
	[FECHA_I30] [datetime] NULL,
	[CAMPO_I30] [varchar](8) NULL,
	[PRODU_I30] [varchar](8) NULL,
	[TOTPL_I30] [float] NULL,
	[TOTJB_I30] [float] NULL,
	[TOTKG_I30] [float] NULL,
	[PPROM_I30] [float] NULL,
	[FLDES_I30] [char](1) NULL,
	[CULTI_I30] [varchar](4) NULL,
	[TOTCA_I30] [float] NULL,
	[FLDPC_I30] [char](1) NULL,
	[FLFTD_I30] [char](1) NULL,
	[PALET_I30] [char](12) NULL,
	[TOTPQ_I30] [float] NULL,
	[PEMAX_I30] [int] NULL,
 CONSTRAINT [PK_PRI30] PRIMARY KEY CLUSTERED 
(
	[IDCAB_I30] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI31]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI31](
	[IDDET_I31] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I31] [int] NULL,
	[PALET_I31] [int] NULL,
	[PPALE_I31] [int] NULL,
	[PAQUE_I31] [float] NULL,
	[JABAS_I31] [int] NULL,
	[PBRUT_I31] [float] NULL,
	[PNETO_I31] [float] NULL,
	[FLDES_I31] [char](1) NULL,
	[KILOS_I31] [float] NULL,
	[CASIL_I31] [float] NULL,
	[LOTE__I31] [varchar](4) NULL,
	[ITEM__I31] [int] NULL,
 CONSTRAINT [PK_PRI31] PRIMARY KEY CLUSTERED 
(
	[IDDET_I31] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI32]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI32](
	[IDCAB_I32] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[VOUCH_I32] [char](12) NULL,
	[PALET_I32] [char](12) NULL,
	[FECHA_I32] [datetime] NULL,
	[PEMAX_I32] [int] NULL,
	[LOCAL_I32] [char](2) NULL,
	[PRODU_I32] [char](6) NULL,
	[FEREG_I32] [datetime] NULL,
	[TOTCJ_I32] [float] NULL,
	[TOTKG_I32] [float] NULL,
	[PPROM_I32] [float] NULL,
	[FLDPC_I32] [char](1) NULL,
	[FLFTD_I32] [char](1) NULL,
	[PERIO_I32] [char](7) NULL,
 CONSTRAINT [PK_PRI32] PRIMARY KEY CLUSTERED 
(
	[IDCAB_I32] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI33]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI33](
	[IDDET_I33] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I33] [int] NULL,
	[ITEM__I33] [int] NULL,
	[CAJAS_I33] [float] NULL,
	[ENVAS_I33] [char](2) NULL,
	[CALID_I33] [char](2) NULL,
	[KILOS_I33] [float] NULL,
	[CAMPO_I33] [char](8) NULL,
 CONSTRAINT [PK_PRI33] PRIMARY KEY CLUSTERED 
(
	[IDDET_I33] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI34]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI34](
	[IDCAB_I34] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[VOUCH_I34] [char](12) NULL,
	[PERIO_I34] [char](7) NULL,
	[FEREG_I34] [datetime] NULL,
	[OVENT_I34] [char](8) NULL,
	[FECHA_I34] [datetime] NULL,
	[MAEST_I34] [char](11) NULL,
	[SEGUI_I34] [char](4) NULL,
	[NUGUI_I34] [char](8) NULL,
	[TOTCJ_I34] [float] NULL,
	[TOTSO_I34] [float] NULL,
	[STATU_I34] [char](12) NULL,
	[TOTKG_I34] [float] NULL,
	[MONED_I34] [char](12) NULL,
	[CAMPA_I34] [char](15) NULL,
	[CULTI_I34] [char](6) NULL,
	[TIVTA_I34] [varchar](2) NULL,
	[SBTVT_I34] [varchar](4) NULL,
 CONSTRAINT [PK_PRI34_1] PRIMARY KEY CLUSTERED 
(
	[IDCAB_I34] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI35]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI35](
	[IDDET_I35] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I35] [int] NULL,
	[CAJAS_I35] [float] NULL,
	[ENVAS_I35] [varchar](6) NULL,
	[PRODU_I35] [varchar](8) NULL,
	[CALID_I35] [varchar](6) NULL,
	[KILOS_I35] [float] NULL,
	[CAMPO_I35] [varchar](8) NULL,
	[PRECI_I35] [float] NULL,
	[SUBTO_I35] [float] NULL,
	[KILNT_I35] [float] NULL,
	[STATU_I35] [char](12) NULL,
 CONSTRAINT [PK_PRI35_1] PRIMARY KEY CLUSTERED 
(
	[IDDET_I35] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI36]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI36](
	[IDCAB_I36] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[VOUCH_I36] [char](12) NULL,
	[PERIO_I36] [char](7) NULL,
	[FEREG_I36] [datetime] NULL,
	[NURPC_I36] [char](8) NULL,
	[FECHA_I36] [datetime] NULL,
	[MAEST_I36] [char](11) NULL,
	[SEGUI_I36] [char](4) NULL,
	[NUGUI_I36] [char](8) NULL,
	[TOTKG_I36] [float] NULL,
	[TOTSO_I36] [float] NULL,
	[TOTDO_I36] [float] NULL,
	[MONED_I36] [char](12) NULL,
	[STATU_I36] [char](12) NULL,
	[IDLIQ_I36] [int] NULL,
	[CAMPA_I36] [char](15) NULL,
	[CULTI_I36] [char](4) NULL,
 CONSTRAINT [PK_PRI36] PRIMARY KEY CLUSTERED 
(
	[IDCAB_I36] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI37]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI37](
	[IDDET_I37] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I37] [int] NULL,
	[KILOS_I37] [float] NULL,
	[CALIB_I37] [char](15) NULL,
	[PRECI_I37] [float] NULL,
	[SUBTO_I37] [float] NULL,
	[CAMPO_I37] [char](8) NULL,
	[IDTRA_I37] [int] NULL,
 CONSTRAINT [PK_PRI37] PRIMARY KEY CLUSTERED 
(
	[IDDET_I37] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI40]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI40](
	[IDCAB_I40] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[LOCAL_I40] [varchar](2) NULL,
	[PERIO_I40] [varchar](7) NULL,
	[VOUCH_I40] [varchar](12) NULL,
	[FEREG_I40] [datetime] NULL,
	[ENEMI_I40] [varchar](2) NULL,
	[TIDVT_I40] [varchar](2) NULL,
	[OVENT_I40] [varchar](8) NULL,
	[FECHA_I40] [datetime] NULL,
	[MONED_I40] [varchar](12) NULL,
	[TICLT_I40] [varchar](2) NULL,
	[TIVTA_I40] [varchar](2) NULL,
	[GRUPO_I40] [varchar](12) NULL,
	[MAEST_I40] [varchar](11) NULL,
	[OBSER_I40] [varchar](50) NULL,
	[SOLES_I40] [float] NULL,
	[DOLAR_I40] [float] NULL,
	[STATU_I40] [varchar](20) NULL,
	[FLGPO_I40] [bit] NULL,
 CONSTRAINT [PK_PRI40] PRIMARY KEY CLUSTERED 
(
	[IDCAB_I40] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI41]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI41](
	[IDDET_I41] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I41] [int] NULL,
	[CANTI_I41] [float] NULL,
	[DESCR_I41] [varchar](50) NULL,
	[PESO__I41] [float] NULL,
	[PRECI_I41] [float] NULL,
	[TOTAL_I41] [float] NULL,
	[PRODU_I41] [varchar](8) NULL,
	[ITEM__I41] [varchar](2) NULL,
 CONSTRAINT [PK_PRI41] PRIMARY KEY CLUSTERED 
(
	[IDDET_I41] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI42]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI42](
	[IDDET_I42] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I42] [int] NULL,
	[CANTI_I42] [float] NULL,
	[DESCR_I42] [varchar](50) NULL,
	[TPCAS_I42] [varchar](2) NULL,
	[PRECI_I42] [float] NULL,
	[TOTAL_I42] [float] NULL,
	[ITEM__I42] [varchar](2) NULL,
 CONSTRAINT [PK_PRI42] PRIMARY KEY CLUSTERED 
(
	[IDDET_I42] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI43]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI43](
	[IDCAB_I43] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[LOCAL_I43] [char](2) NULL,
	[PERIO_I43] [char](7) NULL,
	[VOUCH_I43] [char](12) NULL,
	[FEREG_I43] [datetime] NULL,
	[FECHA_I43] [datetime] NULL,
	[TIDES_I43] [char](2) NULL,
	[TOTPL_I43] [float] NULL,
	[TOTJB_I43] [float] NULL,
	[TOTKG_I43] [float] NULL,
	[PPROM_I43] [float] NULL,
	[FLDES_I43] [char](1) NULL,
	[CULTI_I43] [char](4) NULL,
	[REFER_I43] [varchar](100) NULL,
	[FLGUI_I43] [char](1) NULL,
 CONSTRAINT [PK_PRI43] PRIMARY KEY CLUSTERED 
(
	[IDCAB_I43] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI44]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI44](
	[IDDET_I44] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I44] [int] NOT NULL,
	[LOCAL_I44] [char](2) NULL,
	[PERIO_I44] [char](7) NULL,
	[VOUCH_I44] [char](12) NULL,
	[FEREG_I44] [datetime] NULL,
	[FECHA_I44] [datetime] NULL,
	[CAMPO_I44] [char](8) NULL,
	[PRODU_I44] [char](8) NULL,
	[PALET_I44] [float] NULL,
	[JABAS_I44] [float] NULL,
	[PNETO_I44] [float] NULL,
	[FLDES_I44] [char](1) NULL,
	[CULTI_I44] [char](4) NULL,
	[IDCPC_I44] [int] NULL,
	[IDDPC_I44] [int] NULL,
 CONSTRAINT [PK_PRI44] PRIMARY KEY CLUSTERED 
(
	[IDDET_I44] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI45]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI45](
	[IDCAB_I45] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[LOCAL_I45] [char](2) NULL,
	[PERIO_I45] [char](7) NULL,
	[VOUCH_I45] [char](12) NULL,
	[FEREG_I45] [datetime] NULL,
	[FECHA_I45] [datetime] NULL,
	[TIDES_I45] [char](2) NULL,
	[TOIPL_I45] [float] NULL,
	[TOIJB_I45] [float] NULL,
	[TOIKG_I45] [float] NULL,
	[IPROM_I45] [float] NULL,
	[FLDES_I45] [char](1) NULL,
	[CULTI_I45] [char](4) NULL,
	[TOPCJ_I45] [float] NULL,
	[TOPKG_I45] [float] NULL,
	[PPROM_I45] [float] NULL,
	[IDDPC_I45] [int] NULL,
 CONSTRAINT [PK_PRI45] PRIMARY KEY CLUSTERED 
(
	[IDCAB_I45] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI46]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI46](
	[IDDET_I46] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I46] [int] NOT NULL,
	[LOCAL_I46] [char](2) NULL,
	[PERIO_I46] [char](7) NULL,
	[VOUCH_I46] [char](12) NULL,
	[FEREG_I46] [datetime] NULL,
	[FECHA_I46] [datetime] NULL,
	[CAMPO_I46] [char](8) NULL,
	[PRODU_I46] [char](8) NULL,
	[PALET_I46] [float] NULL,
	[JABAS_I46] [float] NULL,
	[PNETO_I46] [float] NULL,
	[FLDES_I46] [char](1) NULL,
	[CULTI_I46] [char](4) NULL,
	[IDDDC_I46] [int] NULL,
	[IDCPC_I46] [int] NULL,
	[IDDPC_I46] [int] NULL,
 CONSTRAINT [PK_PRI46] PRIMARY KEY CLUSTERED 
(
	[IDDET_I46] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI47]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI47](
	[IDDET_I47] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I47] [int] NULL,
	[CAJAS_I47] [float] NULL,
	[ENVAS_I47] [varchar](20) NULL,
	[PRODU_I47] [char](6) NULL,
	[CALID_I47] [char](15) NULL,
	[KILOS_I47] [float] NULL,
	[CAMPO_I47] [char](8) NULL,
	[PRECI_I47] [float] NULL,
	[SUBTO_I47] [float] NULL,
	[KILNT_I47] [float] NULL,
 CONSTRAINT [PK_PRI47] PRIMARY KEY CLUSTERED 
(
	[IDDET_I47] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI48]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI48](
	[IDDET_I48] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I48] [int] NULL,
	[CAMPO_I48] [char](8) NULL,
	[MERMA_I48] [float] NULL,
	[SOBRA_I48] [float] NULL,
	[PRODU_I48] [char](8) NULL,
	[SDOJB_I48] [float] NULL,
	[SDOKG_I48] [float] NULL,
 CONSTRAINT [PK_PRI48] PRIMARY KEY CLUSTERED 
(
	[IDDET_I48] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRI49]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRI49](
	[IDDET_I49] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[IDCAB_I49] [int] NULL,
	[MAEST_I49] [varchar](11) NULL,
	[DESCR_I49] [varchar](50) NULL,
	[STATU_I49] [varchar](20) NULL,
 CONSTRAINT [PK_PRI49] PRIMARY KEY CLUSTERED 
(
	[IDDET_I49] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRM01]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRM01](
	[EMPRE_M01] [char](2) NOT NULL,
	[CODIG_M01] [varchar](2) NOT NULL,
	[DESCR_M01] [varchar](50) NULL,
	[DCORT_M01] [varchar](10) NULL,
	[UNIDA_M01] [varchar](10) NULL,
	[CULTI_M01] [varchar](4) NULL,
	[VARIE_M01] [varchar](6) NULL,
	[ABREV_M01] [varchar](8) NOT NULL,
	[CUENT_M01] [varchar](8) NULL,
	[ACTIV_M01] [bit] NULL,
 CONSTRAINT [PK_PRM01] PRIMARY KEY CLUSTERED 
(
	[ABREV_M01] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRM02]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRM02](
	[CODIG_M02] [char](8) NOT NULL,
	[DESCR_M02] [varchar](50) NULL,
	[ABREV_M02] [char](2) NULL,
	[UNIDA_M02] [varchar](10) NULL,
 CONSTRAINT [PK_PRM02] PRIMARY KEY CLUSTERED 
(
	[CODIG_M02] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT01]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT01](
	[EMPRE_T01] [varchar](2) NULL,
	[CODIG_T01] [varchar](2) NULL,
	[DESCR_T01] [varchar](50) NULL,
	[ABREV_T01] [varchar](4) NOT NULL,
	[COSTO_T01] [varchar](2) NULL,
	[FLCUL_T01] [varchar](1) NULL,
	[HECTA_T01] [float] NULL,
	[CODUG_T01] [varchar](2) NULL,
	[SDCON_T01] [varchar](2) NULL,
	[CULTIVO] [varchar](20) NULL,
	[NIOAF_T01] [float] NULL,
 CONSTRAINT [PK_PRT01] PRIMARY KEY CLUSTERED 
(
	[ABREV_T01] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT01$]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT01$](
	[EMPRE_T01] [float] NULL,
	[CODIG_T01] [nvarchar](255) NULL,
	[DESCR_T01] [nvarchar](255) NULL,
	[ABREV_T01] [nvarchar](255) NULL,
	[COSTO_T01] [nvarchar](255) NULL,
	[FLCUL_T01] [nvarchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT02]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT02](
	[EMPRE_T02] [varchar](2) NULL,
	[CODIG_T02] [varchar](2) NULL,
	[DESCR_T02] [varchar](50) NULL,
	[ABREV_T02] [varchar](6) NOT NULL,
	[NIV01_T02] [varchar](4) NULL,
	[FLVAR_T02] [varchar](1) NULL,
	[HECTA_T02] [float] NULL,
	[CODUG_T02] [varchar](2) NULL,
	[DEHIL_T02] [float] NULL,
 CONSTRAINT [PK_PRT02] PRIMARY KEY CLUSTERED 
(
	[ABREV_T02] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT02$]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT02$](
	[EMPRE_T02] [varchar](53) NULL,
	[CODIG_T02] [nvarchar](255) NULL,
	[DESCR_T02] [nvarchar](255) NULL,
	[ABREV_T02] [nvarchar](255) NULL,
	[NIV01_T02] [nvarchar](255) NULL,
	[FLVAR_T02] [nvarchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT03]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT03](
	[EMPRE_T03] [char](2) NULL,
	[CODIG_T03] [char](6) NULL,
	[DESCR_T03] [varchar](100) NULL,
	[ABREV_T03] [varchar](8) NOT NULL,
	[NIV02_T03] [varchar](6) NULL,
	[FLLOT_T03] [char](1) NULL,
	[LOTE__T03] [varchar](4) NULL,
	[FLCAM_T03] [char](1) NULL,
	[CAMPO_T03] [varchar](8) NULL,
	[HECTA_T03] [float] NULL,
	[DCORT_T03] [varchar](10) NULL,
	[SCOND_T03] [char](2) NULL,
	[CAMPA_T03] [varchar](10) NULL,
	[FSIEM_T03] [datetime] NULL,
	[ACTIV_T03] [char](1) NULL,
	[DEHIL_T03] [float] NULL,
	[DEPLA_T03] [float] NULL,
	[DEGOT_T03] [float] NULL,
	[CDGOT_T03] [float] NULL,
	[NFMAN_T03] [float] NULL,
	[SUHAB_T03] [float] NULL,
	[TDRIE_T03] [float] NULL,
	[NDSEC_T03] [float] NULL,
	[CREAL_T03] [varchar](8) NULL,
	[CAMFL_T03] [bit] NULL,
	[CTOCB_T03] [varchar](50) NULL,
	[CODAN_T03] [varchar](10) NULL,
	[DCHRM_T03] [varchar](200) NULL,
	[DCXHA_T03] [varchar](200) NULL,
	[DTVAR_T03] [varchar](1) NULL,
	[DTCUL_T03] [varchar](1) NULL,
	[DTFUN_T03] [varchar](1) NULL,
	[DTGEN_T03] [varchar](1) NULL,
	[DTLOT_T03] [varchar](1) NULL,
	[DTHMQ_T03] [varchar](1) NULL,
	[FUNDO_T03] [varchar](2) NULL,
	[CULTI_T03] [varchar](6) NULL,
	[DTLO2_T03] [varchar](1) NULL,
	[CODUG_T03] [varchar](2) NULL,
	[FLOEC_T03] [bit] NULL,
	[NUOEC_T03] [varchar](7) NULL,
	[FLACT_T03] [bit] NULL,
 CONSTRAINT [PK_PRT03] PRIMARY KEY CLUSTERED 
(
	[ABREV_T03] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT03$]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT03$](
	[EMPRE_T03] [float] NULL,
	[CODIG_T03] [float] NULL,
	[DESCR_T03] [nvarchar](255) NULL,
	[ABREV_T03] [float] NULL,
	[NIV02_T03] [float] NULL,
	[FLLOT_T03] [nvarchar](255) NULL,
	[LOTE__T03] [nvarchar](255) NULL,
	[FLCAM_T03] [nvarchar](255) NULL,
	[CAMPO_T03] [nvarchar](255) NULL,
	[HECTA_T03] [float] NULL,
	[DCORT_T03] [nvarchar](255) NULL,
	[SCOND_T03] [nvarchar](255) NULL,
	[CAMPA_T03] [nvarchar](255) NULL,
	[FSIEM_T03] [smalldatetime] NULL,
	[ACTIV_T03] [nvarchar](255) NULL,
	[DEHIL_T03] [float] NULL,
	[DEPLA_T03] [float] NULL,
	[DEGOT_T03] [float] NULL,
	[CDGOT_T03] [float] NULL,
	[NFMAN_T03] [float] NULL,
	[SUHAB_T03] [float] NULL,
	[TDRIE_T03] [float] NULL,
	[NDSEC_T03] [float] NULL,
	[CREAL_T03] [nvarchar](255) NULL,
	[CAMFL_T03] [float] NULL,
	[CTOCB_T03] [nvarchar](255) NULL,
	[CODAN_T03] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT03$__]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT03$__](
	[EMPRE_T03] [varchar](53) NULL,
	[CODIG_T03] [varchar](53) NULL,
	[DESCR_T03] [nvarchar](255) NULL,
	[ABREV_T03] [varchar](53) NULL,
	[NIV02_T03] [varchar](53) NULL,
	[FLLOT_T03] [nvarchar](255) NULL,
	[LOTE__T03] [nvarchar](255) NULL,
	[FLCAM_T03] [nvarchar](255) NULL,
	[CAMPO_T03] [nvarchar](255) NULL,
	[HECTA_T03] [float] NULL,
	[DCORT_T03] [nvarchar](255) NULL,
	[SCOND_T03] [nvarchar](255) NULL,
	[CAMPA_T03] [nvarchar](255) NULL,
	[FSIEM_T03] [smalldatetime] NULL,
	[ACTIV_T03] [nvarchar](255) NULL,
	[DEHIL_T03] [float] NULL,
	[DEPLA_T03] [float] NULL,
	[DEGOT_T03] [float] NULL,
	[CDGOT_T03] [float] NULL,
	[NFMAN_T03] [float] NULL,
	[SUHAB_T03] [float] NULL,
	[TDRIE_T03] [float] NULL,
	[NDSEC_T03] [float] NULL,
	[CREAL_T03] [nvarchar](255) NULL,
	[CAMFL_T03] [float] NULL,
	[CTOCB_T03] [nvarchar](255) NULL,
	[CODAN_T03] [varchar](53) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT04]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT04](
	[CODIG_T04] [char](2) NOT NULL,
	[DESCR_T04] [char](30) NULL,
	[ABREV_T04] [char](10) NULL,
 CONSTRAINT [PK_PRT04] PRIMARY KEY CLUSTERED 
(
	[CODIG_T04] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT05]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT05](
	[CODIG_T05] [char](2) NOT NULL,
	[DESCR_T05] [varchar](50) NULL,
	[ABREV_T05] [varchar](6) NOT NULL,
	[DCORT_T05] [varchar](15) NULL,
	[PRODU_T05] [varchar](6) NULL,
	[CULTI_T05] [varchar](4) NULL,
	[ACTIV_T05] [bit] NULL,
 CONSTRAINT [PK_PRT05] PRIMARY KEY CLUSTERED 
(
	[ABREV_T05] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT06]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT06](
	[EMPRE_T06] [varchar](2) NULL,
	[CODIG_T06] [varchar](2) NOT NULL,
	[DESCR_T06] [varchar](30) NULL,
	[ABREV_T06] [varchar](6) NOT NULL,
	[UNIDA_T06] [varchar](15) NULL,
	[VALOR_T06] [float] NULL,
	[CULTI_T06] [varchar](4) NULL,
	[UMGRF_T06] [varchar](15) NULL,
	[DCORT_T06] [varchar](15) NULL,
	[ACTIV_T06] [bit] NULL,
 CONSTRAINT [PK_PRT06] PRIMARY KEY CLUSTERED 
(
	[ABREV_T06] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT07]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT07](
	[CODIG_T07] [char](2) NOT NULL,
	[DESCR_T07] [char](15) NULL,
	[ABREV_T07] [char](2) NULL,
	[PRCER_T07] [char](1) NULL,
	[CULTI_T07] [char](4) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT08]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT08](
	[IDCAB_T08] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CULTI_T08] [char](4) NULL,
	[ANIO__T08] [char](4) NULL,
	[CODIG_T08] [char](2) NULL,
	[DESCR_T08] [varchar](50) NULL,
	[DESDE_T08] [datetime] NULL,
	[HASTA_T08] [datetime] NULL,
	[ABREV_T08] [char](15) NULL,
	[ACTIV_T08] [bit] NULL,
	[PERIO_T08] [char](10) NULL,
	[ACTIV1_T08] [char](1) NULL,
	[CDESD_T08] [datetime] NULL,
	[CHAST_T08] [datetime] NULL,
 CONSTRAINT [PK_PRT08] PRIMARY KEY CLUSTERED 
(
	[IDCAB_T08] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT10]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT10](
	[CODIG_T10] [char](2) NOT NULL,
	[DESCR_T10] [varchar](50) NULL,
	[ABREV_T10] [char](2) NULL,
	[FLPRO_T10] [char](1) NULL,
	[PRODU_T10] [char](8) NULL,
 CONSTRAINT [PK_PRT10] PRIMARY KEY CLUSTERED 
(
	[CODIG_T10] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT11]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT11](
	[CODIG_T11] [char](2) NOT NULL,
	[DESCR_T11] [varchar](50) NULL,
	[ABREV_T11] [char](2) NULL,
 CONSTRAINT [PK_PRT11] PRIMARY KEY CLUSTERED 
(
	[CODIG_T11] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT12]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT12](
	[CODIG_T12] [varchar](2) NOT NULL,
	[DESCR_T12] [varchar](50) NULL,
	[ABREV_T12] [varchar](2) NULL,
	[FLMVD_T12] [varchar](1) NOT NULL,
 CONSTRAINT [PK_PRT12] PRIMARY KEY CLUSTERED 
(
	[CODIG_T12] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT13]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT13](
	[CODIG_T13] [char](2) NULL,
	[DESCR_T13] [varchar](50) NULL,
	[ABREV_T13] [char](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT14]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT14](
	[CODIG_T14] [char](2) NULL,
	[DESCR_T14] [varchar](50) NULL,
	[ABREV_T14] [char](10) NOT NULL,
	[CAMPO_T14] [varchar](8) NULL,
	[HECTA_T14] [float] NULL,
	[FSIEM_T14] [datetime] NULL,
	[DCORT_T14] [varchar](20) NULL,
	[ACTIV_T14] [char](1) NULL,
	[DEHIL_T14] [float] NULL,
	[DEPLA_T14] [float] NULL,
	[DEGOT_T14] [float] NULL,
	[CDGOT_T14] [float] NULL,
	[NFMAN_T14] [float] NULL,
	[SUHAB_T14] [float] NULL,
	[TDRIE_T14] [float] NULL,
	[NDSEC_T14] [float] NULL,
 CONSTRAINT [PK_PRT14] PRIMARY KEY CLUSTERED 
(
	[ABREV_T14] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT15]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT15](
	[IDCAB_T15] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CULTI_T15] [char](4) NULL,
	[ANIO__T15] [char](4) NULL,
	[CAMPA_T15] [char](10) NULL,
	[CAMPO_T15] [char](8) NULL,
	[CODIG_T15] [char](2) NULL,
	[DESCR_T15] [varchar](100) NULL,
	[DESDE_T15] [datetime] NULL,
	[HASTA_T15] [datetime] NULL,
	[ABREV_T15] [char](20) NULL,
	[ACTIV_T15] [bit] NULL,
	[PERIO_T15] [char](10) NULL,
	[CDESD_T15] [datetime] NULL,
	[CHAST_T15] [datetime] NULL,
	[FPCOS_T15] [datetime] NULL,
 CONSTRAINT [PK_PRT15] PRIMARY KEY CLUSTERED 
(
	[IDCAB_T15] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT16]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT16](
	[CODIG_T16] [varchar](2) NOT NULL,
	[DESCR_T16] [varchar](50) NULL,
	[ABREV_T16] [varchar](20) NULL,
	[FLDPG_T16] [bit] NULL,
	[ENEMI_T16] [varchar](2) NULL,
	[MAEST_T16] [varchar](11) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT17]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT17](
	[CODIG_T17] [varchar](2) NOT NULL,
	[DESCR_T17] [varchar](50) NULL,
	[ABREV_T17] [varchar](20) NULL,
	[TIDVT_T17] [varchar](2) NULL,
	[SERIE_T17] [varchar](4) NULL,
 CONSTRAINT [PK_PRT17] PRIMARY KEY CLUSTERED 
(
	[CODIG_T17] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT18]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT18](
	[CODIG_T18] [varchar](2) NOT NULL,
	[DESCR_T18] [varchar](50) NULL,
	[ABREV_T18] [varchar](20) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT19]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT19](
	[CODIG_T19] [varchar](2) NOT NULL,
	[DESCR_T19] [varchar](50) NULL,
	[ABREV_T19] [varchar](20) NOT NULL,
	[ENEMI_T19] [varchar](2) NULL,
	[TIDVT_T19] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT20]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT20](
	[CODIG_T20] [char](2) NULL,
	[DESCR_T20] [varchar](50) NULL,
	[ABREV_T20] [char](10) NOT NULL,
	[CAMPO_T20] [char](8) NULL,
	[HECTA_T20] [float] NULL,
	[FSIEM_T20] [datetime] NULL,
	[DCORT_T20] [varchar](20) NULL,
	[ACTIV_T20] [char](1) NULL,
	[DEHIL_T20] [float] NULL,
	[DEPLA_T20] [float] NULL,
	[DEGOT_T20] [float] NULL,
	[CDGOT_T20] [float] NULL,
	[NFMAN_T20] [float] NULL,
	[SUHAB_T20] [float] NULL,
	[TDRIE_T20] [float] NULL,
	[NDSEC_T20] [float] NULL,
	[NIV02_T20] [varchar](6) NULL,
	[NIV01_T20] [varchar](6) NULL,
	[COSTO_T20] [varchar](50) NULL,
 CONSTRAINT [PK_PRT20] PRIMARY KEY CLUSTERED 
(
	[ABREV_T20] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT21]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT21](
	[CODIG_T21] [varchar](2) NOT NULL,
	[DESCR_T21] [varchar](50) NULL,
	[ABREV_T21] [varchar](10) NULL,
 CONSTRAINT [PK_PRT21] PRIMARY KEY CLUSTERED 
(
	[CODIG_T21] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRT22]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRT22](
	[CODIG_T22] [varchar](2) NOT NULL,
	[DESCR_T22] [varchar](50) NULL,
	[TIPOV_T22] [varchar](2) NOT NULL,
	[ABREV_T22] [varchar](4) NOT NULL,
	[FLIRP_T22] [bit] NULL,
 CONSTRAINT [PK_PRT22] PRIMARY KEY CLUSTERED 
(
	[ABREV_T22] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRW01]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRW01](
	[CAMPO_W01] [char](8) NULL,
	[DESCR_W01] [varchar](50) NULL,
	[HECTA_W01] [float] NULL,
	[FECHA_W01] [datetime] NULL,
	[KILOS_W01] [float] NULL,
	[KGXHA_W01] [float] NULL,
	[ITEM__W01] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRW02]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRW02](
	[CAMPO_W02] [varchar](8) NULL,
	[DESCR_W02] [varchar](50) NULL,
	[FECHA_W02] [datetime] NULL,
	[HECTA_W02] [float] NULL,
	[KILOS_W02] [float] NULL,
	[USUAR_W02] [varchar](20) NULL,
	[COMPU_W02] [varchar](50) NULL,
	[CULTI_W02] [char](4) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRW03]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRW03](
	[CAMPO_W03] [varchar](8) NULL,
	[DESCR_W03] [varchar](50) NULL,
	[HECTA_W03] [float] NULL,
	[KILOS_W03] [float] NULL,
	[USUAR_W03] [varchar](20) NULL,
	[COMPU_W03] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRW04]    Script Date: 18/02/2023 19:53:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRW04](
	[CAMPO_W04] [char](8) NULL,
	[DESCR_W04] [varchar](50) NOT NULL,
	[CALIB_W04] [varchar](50) NOT NULL,
	[HECTA_W04] [float] NULL,
	[FECHA_W04] [datetime] NOT NULL,
	[KILOS_W04] [float] NULL,
	[KGXHA_W04] [float] NULL,
	[ITEM__W04] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[_PRI34] ADD  CONSTRAINT [DF_PRI34_TOTCJ_I34]  DEFAULT (0) FOR [TOTCJ_I34]
GO
ALTER TABLE [dbo].[_PRI34] ADD  CONSTRAINT [DF_PRI34_TOTSO_I34]  DEFAULT (0) FOR [TOTSO_I34]
GO
ALTER TABLE [dbo].[_PRI34] ADD  CONSTRAINT [DF_PRI34_TOTKG_I34]  DEFAULT (0) FOR [TOTKG_I34]
GO
ALTER TABLE [dbo].[_PRI43] ADD  CONSTRAINT [DF_PRI43_IDCAB_I43]  DEFAULT (0) FOR [IDCAB_I43]
GO
ALTER TABLE [dbo].[_PRI43] ADD  CONSTRAINT [DF_PRI43_MAEST_I43]  DEFAULT (' ') FOR [MAEST_I43]
GO
ALTER TABLE [dbo].[_PRI43] ADD  CONSTRAINT [DF_PRI43_DESCR_I43]  DEFAULT (' ') FOR [DESCR_I43]
GO
ALTER TABLE [dbo].[_PRI43] ADD  CONSTRAINT [DF_PRI43_STATU_I03]  DEFAULT ('01 PENDIENTE') FOR [STATU_I43]
GO
ALTER TABLE [dbo].[_PRT06] ADD  CONSTRAINT [DF_PRT06_VALOR_T06]  DEFAULT (0) FOR [VALOR_T06]
GO
ALTER TABLE [dbo].[PRI30] ADD  CONSTRAINT [DF_PRI30_TOTPL_I30]  DEFAULT (0) FOR [TOTPL_I30]
GO
ALTER TABLE [dbo].[PRI30] ADD  CONSTRAINT [DF_PRI30_FLDES_I30]  DEFAULT ('N') FOR [FLDES_I30]
GO
ALTER TABLE [dbo].[PRI31] ADD  CONSTRAINT [DF_PRI31_PALET_I31]  DEFAULT (0) FOR [PALET_I31]
GO
ALTER TABLE [dbo].[PRI31] ADD  CONSTRAINT [DF_PRI31_PPALE_I31]  DEFAULT (0) FOR [PPALE_I31]
GO
ALTER TABLE [dbo].[PRI34] ADD  CONSTRAINT [DF_PRI34_CULTI_I34]  DEFAULT (' ') FOR [CULTI_I34]
GO
ALTER TABLE [dbo].[PRI34] ADD  CONSTRAINT [DF_PRI34_TIVTA_I34]  DEFAULT (' ') FOR [TIVTA_I34]
GO
ALTER TABLE [dbo].[PRI34] ADD  CONSTRAINT [DF_PRI34_SBTVT_I34]  DEFAULT (' ') FOR [SBTVT_I34]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_LOCAL_I40]  DEFAULT (' ') FOR [LOCAL_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_PERIO_I40]  DEFAULT (' ') FOR [PERIO_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_VOUCH_I40]  DEFAULT (' ') FOR [VOUCH_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_FEREG_I40]  DEFAULT (0) FOR [FEREG_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_ENEMI_I40]  DEFAULT (' ') FOR [ENEMI_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_TIDVT_I40]  DEFAULT (' ') FOR [TIDVT_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_OVENT_I40]  DEFAULT (' ') FOR [OVENT_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_FECHA_I40]  DEFAULT (0) FOR [FECHA_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_MONED_I40]  DEFAULT (' ') FOR [MONED_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_TICLT_I40]  DEFAULT (' ') FOR [TICLT_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_TIVTA_I40]  DEFAULT (' ') FOR [TIVTA_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_GRUPO_I40]  DEFAULT (' ') FOR [GRUPO_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_MAEST_I40]  DEFAULT (' ') FOR [MAEST_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_OBSER_I40]  DEFAULT (' ') FOR [OBSER_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_SOLES_I40]  DEFAULT (0) FOR [SOLES_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_DOLAR_I40]  DEFAULT (0) FOR [DOLAR_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_STATU_I40]  DEFAULT ('01 PENDIENTE') FOR [STATU_I40]
GO
ALTER TABLE [dbo].[PRI40] ADD  CONSTRAINT [DF_PRI40_FLGPO_I40]  DEFAULT (0) FOR [FLGPO_I40]
GO
ALTER TABLE [dbo].[PRI41] ADD  CONSTRAINT [DF_PRI41_IDCAB_I41]  DEFAULT (0) FOR [IDCAB_I41]
GO
ALTER TABLE [dbo].[PRI41] ADD  CONSTRAINT [DF_PRI41_CANTI_I41]  DEFAULT (0) FOR [CANTI_I41]
GO
ALTER TABLE [dbo].[PRI41] ADD  CONSTRAINT [DF_PRI41_DESCR_I41]  DEFAULT (' ') FOR [DESCR_I41]
GO
ALTER TABLE [dbo].[PRI41] ADD  CONSTRAINT [DF_PRI41_PESO__I41]  DEFAULT (0) FOR [PESO__I41]
GO
ALTER TABLE [dbo].[PRI41] ADD  CONSTRAINT [DF_PRI41_PRECI_I41]  DEFAULT (0) FOR [PRECI_I41]
GO
ALTER TABLE [dbo].[PRI41] ADD  CONSTRAINT [DF_PRI41_TOTAL_I41]  DEFAULT (0) FOR [TOTAL_I41]
GO
ALTER TABLE [dbo].[PRI41] ADD  CONSTRAINT [DF_PRI41_PRODU_I41]  DEFAULT (' ') FOR [PRODU_I41]
GO
ALTER TABLE [dbo].[PRI41] ADD  CONSTRAINT [DF_PRI41_ITEM__I41]  DEFAULT (' ') FOR [ITEM__I41]
GO
ALTER TABLE [dbo].[PRI42] ADD  CONSTRAINT [DF_PRI42_IDCAB_I42]  DEFAULT (0) FOR [IDCAB_I42]
GO
ALTER TABLE [dbo].[PRI42] ADD  CONSTRAINT [DF_PRI42_CANTI_I42]  DEFAULT (0) FOR [CANTI_I42]
GO
ALTER TABLE [dbo].[PRI42] ADD  CONSTRAINT [DF_PRI42_DESCR_I42]  DEFAULT (' ') FOR [DESCR_I42]
GO
ALTER TABLE [dbo].[PRI42] ADD  CONSTRAINT [DF_PRI42_TPCAS_I42]  DEFAULT (' ') FOR [TPCAS_I42]
GO
ALTER TABLE [dbo].[PRI42] ADD  CONSTRAINT [DF_PRI42_PRECI_I42]  DEFAULT (0) FOR [PRECI_I42]
GO
ALTER TABLE [dbo].[PRI42] ADD  CONSTRAINT [DF_PRI42_TOTAL_I42]  DEFAULT (0) FOR [TOTAL_I42]
GO
ALTER TABLE [dbo].[PRI42] ADD  CONSTRAINT [DF_PRI42_ITEM__I42]  DEFAULT (' ') FOR [ITEM__I42]
GO
ALTER TABLE [dbo].[PRI49] ADD  CONSTRAINT [DF_PRI49_IDCAB_I49]  DEFAULT (0) FOR [IDCAB_I49]
GO
ALTER TABLE [dbo].[PRI49] ADD  CONSTRAINT [DF_PRI49_MAEST_I49]  DEFAULT (' ') FOR [MAEST_I49]
GO
ALTER TABLE [dbo].[PRI49] ADD  CONSTRAINT [DF_PRI49_DESCR_I49]  DEFAULT (' ') FOR [DESCR_I49]
GO
ALTER TABLE [dbo].[PRI49] ADD  CONSTRAINT [DF_PRI49_STATU_I49]  DEFAULT (' ') FOR [STATU_I49]
GO
ALTER TABLE [dbo].[PRM01] ADD  CONSTRAINT [DF_PRM01_CULTI_M01]  DEFAULT (' ') FOR [CULTI_M01]
GO
ALTER TABLE [dbo].[PRM01] ADD  CONSTRAINT [DF_PRM01_CUENT_M01]  DEFAULT (' ') FOR [CUENT_M01]
GO
ALTER TABLE [dbo].[PRM01] ADD  CONSTRAINT [DF_PRM01_ACTIV_M01]  DEFAULT (1) FOR [ACTIV_M01]
GO
ALTER TABLE [dbo].[PRT01] ADD  CONSTRAINT [DF_PRT01_FLCUL_T01]  DEFAULT ('N') FOR [FLCUL_T01]
GO
ALTER TABLE [dbo].[PRT01] ADD  CONSTRAINT [DF_PRT01_HECTA_T]  DEFAULT (0) FOR [HECTA_T01]
GO
ALTER TABLE [dbo].[PRT01] ADD  CONSTRAINT [DF_PRT01_SDCON_T01]  DEFAULT (' ') FOR [SDCON_T01]
GO
ALTER TABLE [dbo].[PRT01] ADD  CONSTRAINT [DF_PRT01_NIOAF_T01]  DEFAULT (0) FOR [NIOAF_T01]
GO
ALTER TABLE [dbo].[PRT02] ADD  CONSTRAINT [DF_PRT02_FLVAR_T02]  DEFAULT ('N') FOR [FLVAR_T02]
GO
ALTER TABLE [dbo].[PRT02] ADD  CONSTRAINT [DF_PRT02_HECTA_T02]  DEFAULT (0) FOR [HECTA_T02]
GO
ALTER TABLE [dbo].[PRT02] ADD  CONSTRAINT [DF_PRT02_DEHIL_T02]  DEFAULT (0) FOR [DEHIL_T02]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_CODIG_T03]  DEFAULT (' ') FOR [CODIG_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_DESCR_T03]  DEFAULT (' ') FOR [DESCR_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_NIV02_T03]  DEFAULT (' ') FOR [NIV02_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_FLLOT_T03]  DEFAULT ('N') FOR [FLLOT_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_LOTE__T03]  DEFAULT (' ') FOR [LOTE__T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_FLCAM_T03]  DEFAULT ('N') FOR [FLCAM_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_CAMPO_T03]  DEFAULT (' ') FOR [CAMPO_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_HECTA_T03]  DEFAULT (0) FOR [HECTA_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_DCORT_T03]  DEFAULT (' ') FOR [DCORT_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_SCOND_T03]  DEFAULT (' ') FOR [SCOND_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_CAMPA_T03]  DEFAULT (' ') FOR [CAMPA_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_ACTIV_T03]  DEFAULT ('S') FOR [ACTIV_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_DEHIL_T03]  DEFAULT (0) FOR [DEHIL_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_DEPLA_T03]  DEFAULT (0) FOR [DEPLA_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_DEGOT_T03]  DEFAULT (0) FOR [DEGOT_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_CDGOT_T03]  DEFAULT (0) FOR [CDGOT_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_NFMAN_T03]  DEFAULT (0) FOR [NFMAN_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_SUHAB_T03]  DEFAULT (0) FOR [SUHAB_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_TDRIE_T03]  DEFAULT (0) FOR [TDRIE_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_NDSEC_T03]  DEFAULT (0) FOR [NDSEC_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_CREAL_T03]  DEFAULT (' ') FOR [CREAL_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_CAMFL_T03]  DEFAULT (0) FOR [CAMFL_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_CTOCB_T03]  DEFAULT (' ') FOR [CTOCB_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_CODAN_R03]  DEFAULT (' ') FOR [CODAN_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_DCHRM_T03]  DEFAULT (' ') FOR [DCHRM_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_DCXHA_T03]  DEFAULT (' ') FOR [DCXHA_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_FLVAT_T03]  DEFAULT ('N') FOR [DTVAR_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_FLCUL_T03]  DEFAULT ('N') FOR [DTCUL_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_FLFUN_T03]  DEFAULT ('N') FOR [DTFUN_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_FLGEN_T03]  DEFAULT ('N') FOR [DTGEN_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_DTLOT_T03]  DEFAULT ('N') FOR [DTLOT_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_DTHMQ_T03]  DEFAULT ('N') FOR [DTHMQ_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_fFUNDO_T03]  DEFAULT (' ') FOR [FUNDO_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_CULTI_T03]  DEFAULT (' ') FOR [CULTI_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_DTLO2_T03]  DEFAULT ('N') FOR [DTLO2_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_FLOEC_T03]  DEFAULT (0) FOR [FLOEC_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_NUOEC_T03]  DEFAULT (' ') FOR [NUOEC_T03]
GO
ALTER TABLE [dbo].[PRT03] ADD  CONSTRAINT [DF_PRT03_FLACT_T03]  DEFAULT (1) FOR [FLACT_T03]
GO
ALTER TABLE [dbo].[PRT05] ADD  CONSTRAINT [DF_PRT05_ACTIV_T05]  DEFAULT (1) FOR [ACTIV_T05]
GO
ALTER TABLE [dbo].[PRT06] ADD  CONSTRAINT [DF_PRT06_EMPRE_T06]  DEFAULT ('64') FOR [EMPRE_T06]
GO
ALTER TABLE [dbo].[PRT06] ADD  CONSTRAINT [DF_PRT06_ACTIV_T06]  DEFAULT (1) FOR [ACTIV_T06]
GO
ALTER TABLE [dbo].[PRT08] ADD  CONSTRAINT [DF_PRT08_CULTI_T08]  DEFAULT (' ') FOR [CULTI_T08]
GO
ALTER TABLE [dbo].[PRT08] ADD  CONSTRAINT [DF_PRT08_ANIO__T08]  DEFAULT (' ') FOR [ANIO__T08]
GO
ALTER TABLE [dbo].[PRT08] ADD  CONSTRAINT [DF_PRT08_CODIG_T08]  DEFAULT (' ') FOR [CODIG_T08]
GO
ALTER TABLE [dbo].[PRT08] ADD  CONSTRAINT [DF_PRT08_DESCR_T08]  DEFAULT (' ') FOR [DESCR_T08]
GO
ALTER TABLE [dbo].[PRT08] ADD  CONSTRAINT [DF_PRT08_DESDE_T08]  DEFAULT (0) FOR [DESDE_T08]
GO
ALTER TABLE [dbo].[PRT08] ADD  CONSTRAINT [DF_PRT08_HASTA_T08]  DEFAULT (0) FOR [HASTA_T08]
GO
ALTER TABLE [dbo].[PRT08] ADD  CONSTRAINT [DF_PRT08_ABREV_T08]  DEFAULT (' ') FOR [ABREV_T08]
GO
ALTER TABLE [dbo].[PRT08] ADD  CONSTRAINT [DF_PRT08_PERIO_T08]  DEFAULT (' ') FOR [PERIO_T08]
GO
ALTER TABLE [dbo].[PRT08] ADD  CONSTRAINT [DF_PRT08_ACTIV1_T08]  DEFAULT ('S') FOR [ACTIV1_T08]
GO
ALTER TABLE [dbo].[PRT08] ADD  CONSTRAINT [DF_PRT08_CDESD_T081]  DEFAULT (0) FOR [CDESD_T08]
GO
ALTER TABLE [dbo].[PRT08] ADD  CONSTRAINT [DF_PRT08_CHAST_T081]  DEFAULT (0) FOR [CHAST_T08]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_CODIG_T14]  DEFAULT (' ') FOR [CODIG_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_DESCR_T14]  DEFAULT (' ') FOR [DESCR_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_ABREV_T14]  DEFAULT (' ') FOR [ABREV_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_CAMPO_T14]  DEFAULT (' ') FOR [CAMPO_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_HECTA_T14]  DEFAULT (0) FOR [HECTA_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_DCORT_T14]  DEFAULT (' ') FOR [DCORT_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_ACTIV_T14]  DEFAULT ('S') FOR [ACTIV_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_DEPLA_T14]  DEFAULT (0) FOR [DEPLA_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_DEGOT_T14]  DEFAULT (0) FOR [DEGOT_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_CDGOT_T14]  DEFAULT (0) FOR [CDGOT_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_NFMAN_T14]  DEFAULT (0) FOR [NFMAN_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_SUHAB_T14]  DEFAULT (0) FOR [SUHAB_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_TDRIE_T14]  DEFAULT (0) FOR [TDRIE_T14]
GO
ALTER TABLE [dbo].[PRT14] ADD  CONSTRAINT [DF_PRT14_NDSEC_T14]  DEFAULT (0) FOR [NDSEC_T14]
GO
ALTER TABLE [dbo].[PRT15] ADD  CONSTRAINT [DF_PRT15_CULTI_T15]  DEFAULT (' ') FOR [CULTI_T15]
GO
ALTER TABLE [dbo].[PRT15] ADD  CONSTRAINT [DF_PRT15_ANIO__T15]  DEFAULT (' ') FOR [ANIO__T15]
GO
ALTER TABLE [dbo].[PRT15] ADD  CONSTRAINT [DF_PRT15_CAMPA_T15]  DEFAULT (' ') FOR [CAMPA_T15]
GO
ALTER TABLE [dbo].[PRT15] ADD  CONSTRAINT [DF_PRT15_CAMPO_T15]  DEFAULT (' ') FOR [CAMPO_T15]
GO
ALTER TABLE [dbo].[PRT15] ADD  CONSTRAINT [DF_PRT15_CODIG_T15]  DEFAULT (' ') FOR [CODIG_T15]
GO
ALTER TABLE [dbo].[PRT15] ADD  CONSTRAINT [DF_PRT15_DESCR_T15]  DEFAULT (' ') FOR [DESCR_T15]
GO
ALTER TABLE [dbo].[PRT15] ADD  CONSTRAINT [DF_PRT15_DESDE_T15]  DEFAULT (0) FOR [DESDE_T15]
GO
ALTER TABLE [dbo].[PRT15] ADD  CONSTRAINT [DF_PRT15_HASTA_T15]  DEFAULT (0) FOR [HASTA_T15]
GO
ALTER TABLE [dbo].[PRT15] ADD  CONSTRAINT [DF_PRT15_ABREV_T15]  DEFAULT (' ') FOR [ABREV_T15]
GO
ALTER TABLE [dbo].[PRT15] ADD  CONSTRAINT [DF_PRT15_PERIO_T15]  DEFAULT (' ') FOR [PERIO_T15]
GO
ALTER TABLE [dbo].[PRT15] ADD  CONSTRAINT [DF_PRT15_DESDE_T151]  DEFAULT (0) FOR [CDESD_T15]
GO
ALTER TABLE [dbo].[PRT15] ADD  CONSTRAINT [DF_PRT15_HASTA_T151]  DEFAULT (0) FOR [CHAST_T15]
GO
ALTER TABLE [dbo].[PRT16] ADD  CONSTRAINT [DF_PRT16_DESCR_T16]  DEFAULT (' ') FOR [DESCR_T16]
GO
ALTER TABLE [dbo].[PRT16] ADD  CONSTRAINT [DF_PRT16_ABREV_T16]  DEFAULT (' ') FOR [ABREV_T16]
GO
ALTER TABLE [dbo].[PRT16] ADD  CONSTRAINT [DF_PRT16_FLDPG_T16]  DEFAULT (0) FOR [FLDPG_T16]
GO
ALTER TABLE [dbo].[PRT16] ADD  CONSTRAINT [DF_PRT16_ENEMI_T16]  DEFAULT (' ') FOR [ENEMI_T16]
GO
ALTER TABLE [dbo].[PRT16] ADD  CONSTRAINT [DF_PRT16_MAEST_T16]  DEFAULT (' ') FOR [MAEST_T16]
GO
ALTER TABLE [dbo].[PRT17] ADD  CONSTRAINT [DF_PRT17_DESCR_T17]  DEFAULT (' ') FOR [DESCR_T17]
GO
ALTER TABLE [dbo].[PRT17] ADD  CONSTRAINT [DF_PRT17_ABREV_T17]  DEFAULT (' ') FOR [ABREV_T17]
GO
ALTER TABLE [dbo].[PRT17] ADD  CONSTRAINT [DF_PRT17_TIDVT_T17]  DEFAULT (' ') FOR [TIDVT_T17]
GO
ALTER TABLE [dbo].[PRT17] ADD  CONSTRAINT [DF_PRT17_SERIE_T17]  DEFAULT (' ') FOR [SERIE_T17]
GO
ALTER TABLE [dbo].[PRT18] ADD  CONSTRAINT [DF_PRT18_DESCR_T18]  DEFAULT (' ') FOR [DESCR_T18]
GO
ALTER TABLE [dbo].[PRT18] ADD  CONSTRAINT [DF_PRT18_ABREV_T18]  DEFAULT (' ') FOR [ABREV_T18]
GO
ALTER TABLE [dbo].[PRT19] ADD  CONSTRAINT [DF_PRT19_DESCR_T19]  DEFAULT (' ') FOR [DESCR_T19]
GO
ALTER TABLE [dbo].[PRT19] ADD  CONSTRAINT [DF_PRT19_ABREV_T19]  DEFAULT (' ') FOR [ABREV_T19]
GO
ALTER TABLE [dbo].[PRT19] ADD  CONSTRAINT [DF_PRT19_ENEMI_T19]  DEFAULT (' ') FOR [ENEMI_T19]
GO
ALTER TABLE [dbo].[PRT19] ADD  CONSTRAINT [DF_PRT19_TIDVT_T19]  DEFAULT (' ') FOR [TIDVT_T19]
GO
ALTER TABLE [dbo].[PRT20] ADD  CONSTRAINT [DF_PRT20_NIV02_T20]  DEFAULT (' ') FOR [NIV02_T20]
GO
ALTER TABLE [dbo].[PRT20] ADD  CONSTRAINT [DF_PRT20_NIV01_T20]  DEFAULT (' ') FOR [NIV01_T20]
GO
ALTER TABLE [dbo].[PRT20] ADD  CONSTRAINT [DF_PRT20_COSTO_T20]  DEFAULT (' ') FOR [COSTO_T20]
GO
ALTER TABLE [dbo].[PRT22] ADD  CONSTRAINT [DF_PRT22_FLIRP_T22]  DEFAULT (1) FOR [FLIRP_T22]
GO
ALTER TABLE [dbo].[_PRI35]  WITH NOCHECK ADD  CONSTRAINT [FK_PRI35_PRI34] FOREIGN KEY([IDCAB_I35])
REFERENCES [dbo].[_PRI34] ([IDCAB_I34])
ON UPDATE CASCADE
ON DELETE CASCADE
NOT FOR REPLICATION 
GO
ALTER TABLE [dbo].[_PRI35] CHECK CONSTRAINT [FK_PRI35_PRI34]
GO
ALTER TABLE [dbo].[_PRI43]  WITH NOCHECK ADD  CONSTRAINT [FK_PRI43_PRI40] FOREIGN KEY([IDCAB_I43])
REFERENCES [dbo].[PRI40] ([IDCAB_I40])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[_PRI43] CHECK CONSTRAINT [FK_PRI43_PRI40]
GO
ALTER TABLE [dbo].[PRI31]  WITH NOCHECK ADD  CONSTRAINT [FK_PRI31_PRI30] FOREIGN KEY([IDCAB_I31])
REFERENCES [dbo].[PRI30] ([IDCAB_I30])
ON UPDATE CASCADE
ON DELETE CASCADE
NOT FOR REPLICATION 
GO
ALTER TABLE [dbo].[PRI31] CHECK CONSTRAINT [FK_PRI31_PRI30]
GO
ALTER TABLE [dbo].[PRI33]  WITH NOCHECK ADD  CONSTRAINT [FK_PRI33_PRI32] FOREIGN KEY([IDCAB_I33])
REFERENCES [dbo].[PRI32] ([IDCAB_I32])
ON UPDATE CASCADE
ON DELETE CASCADE
NOT FOR REPLICATION 
GO
ALTER TABLE [dbo].[PRI33] CHECK CONSTRAINT [FK_PRI33_PRI32]
GO
ALTER TABLE [dbo].[PRI35]  WITH NOCHECK ADD  CONSTRAINT [FK_PRI35_PRI341] FOREIGN KEY([IDCAB_I35])
REFERENCES [dbo].[PRI34] ([IDCAB_I34])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRI35] CHECK CONSTRAINT [FK_PRI35_PRI341]
GO
ALTER TABLE [dbo].[PRI37]  WITH CHECK ADD  CONSTRAINT [FK_PRI37_PRI36] FOREIGN KEY([IDCAB_I37])
REFERENCES [dbo].[PRI36] ([IDCAB_I36])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRI37] CHECK CONSTRAINT [FK_PRI37_PRI36]
GO
ALTER TABLE [dbo].[PRI41]  WITH NOCHECK ADD  CONSTRAINT [FK_PRI41_PRI40] FOREIGN KEY([IDCAB_I41])
REFERENCES [dbo].[PRI40] ([IDCAB_I40])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRI41] CHECK CONSTRAINT [FK_PRI41_PRI40]
GO
ALTER TABLE [dbo].[PRI42]  WITH NOCHECK ADD  CONSTRAINT [FK_PRI42_PRI40] FOREIGN KEY([IDCAB_I42])
REFERENCES [dbo].[PRI40] ([IDCAB_I40])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRI42] CHECK CONSTRAINT [FK_PRI42_PRI40]
GO
ALTER TABLE [dbo].[PRI44]  WITH CHECK ADD  CONSTRAINT [FK_PRI44_PRI43] FOREIGN KEY([IDCAB_I44])
REFERENCES [dbo].[PRI43] ([IDCAB_I43])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRI44] CHECK CONSTRAINT [FK_PRI44_PRI43]
GO
ALTER TABLE [dbo].[PRI46]  WITH CHECK ADD  CONSTRAINT [FK_PRI46_PRI45] FOREIGN KEY([IDCAB_I46])
REFERENCES [dbo].[PRI45] ([IDCAB_I45])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRI46] CHECK CONSTRAINT [FK_PRI46_PRI45]
GO
ALTER TABLE [dbo].[PRI47]  WITH CHECK ADD  CONSTRAINT [FK_PRI47_PRI45] FOREIGN KEY([IDCAB_I47])
REFERENCES [dbo].[PRI45] ([IDCAB_I45])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRI47] CHECK CONSTRAINT [FK_PRI47_PRI45]
GO
ALTER TABLE [dbo].[PRI48]  WITH CHECK ADD  CONSTRAINT [FK_PRI48_PRI45] FOREIGN KEY([IDCAB_I48])
REFERENCES [dbo].[PRI45] ([IDCAB_I45])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRI48] CHECK CONSTRAINT [FK_PRI48_PRI45]
GO
ALTER TABLE [dbo].[PRI49]  WITH NOCHECK ADD  CONSTRAINT [FK_PRI49_PRI40] FOREIGN KEY([IDCAB_I49])
REFERENCES [dbo].[PRI40] ([IDCAB_I40])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRI49] CHECK CONSTRAINT [FK_PRI49_PRI40]
GO
ALTER TABLE [dbo].[PRT02]  WITH NOCHECK ADD  CONSTRAINT [FK_PRT02_PRT01] FOREIGN KEY([NIV01_T02])
REFERENCES [dbo].[PRT01] ([ABREV_T01])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRT02] CHECK CONSTRAINT [FK_PRT02_PRT01]
GO
ALTER TABLE [dbo].[PRT03]  WITH NOCHECK ADD  CONSTRAINT [FK_PRT03_PRT02] FOREIGN KEY([NIV02_T03])
REFERENCES [dbo].[PRT02] ([ABREV_T02])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRT03] CHECK CONSTRAINT [FK_PRT03_PRT02]
GO
ALTER TABLE [dbo].[PRT14]  WITH NOCHECK ADD  CONSTRAINT [FK_PRT14_PRT03] FOREIGN KEY([CAMPO_T14])
REFERENCES [dbo].[PRT03] ([ABREV_T03])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRT14] CHECK CONSTRAINT [FK_PRT14_PRT03]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DESCONTINUADO YA NO ES NECESARIO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRI40', @level2type=N'COLUMN',@level2name=N'FLGPO_I40'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SEDE DE CONSUMO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT01', @level2type=N'COLUMN',@level2name=N'SDCON_T01'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'NUMERO INICIAL OAF POR FUNDO Y CULTIVO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT01', @level2type=N'COLUMN',@level2name=N'NIOAF_T01'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT02', @level2type=N'COLUMN',@level2name=N'FLVAR_T02'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'CODIGO DE COSTO/CAMPO DENTRO DE SU CLASE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'CODIG_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DESCRIPCION' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DESCR_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ABREVIATURA/CODIGO AUTOGENERADO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'ABREV_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'NIVEL 02 / VARIEDAD' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'NIV02_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FLAG DE LOTE AVICOLA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'FLLOT_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'LOTE AVICOLA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'LOTE__T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FALG DE CAMPO AGRICOLA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'FLCAM_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'CAMPO AGRICOLA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'CAMPO_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'HECTAREAS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'HECTA_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DESCRIPCION CORTA PARA TRAZABILIDAD ' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DCORT_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SISTEMA DE CONDUCCION' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'SCOND_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'CAMPAÑA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'CAMPA_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FECHA DE SIEMBRA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'FSIEM_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FLAG ACTIVO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'ACTIV_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DISTANCIA ENTRE HILERAS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DEHIL_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DISTANCIA ENTRE PLANTAS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DEPLA_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DISTANCIA ENTRE GOTEROS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DEGOT_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'CAUDAL DE GOTEROS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'CDGOT_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'NUMERO DE FILAS DE MANGUERAS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'NFMAN_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SUPERFICIE HABILITADA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'SUHAB_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'TIEMPO DE RIEGO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'TDRIE_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'NUMERO DE SECTORES' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'NDSEC_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DIST DE COSTOS POR HORA MAQUINA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DCHRM_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DIST. DE COSTOS POR HECTAREA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DCXHA_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DISTRIBUCION POR VARIEDAD' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DTVAR_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DISTRIBUCION POR CULTIVO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DTCUL_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DISTRIBUCION POR FUNDO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DTFUN_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DISTRIBUCION POR GENERAL' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DTGEN_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DISTRIBUCION POR LOTE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DTLOT_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'distribucion DE HORAS MAQUINAS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DTHMQ_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FUNDO ASOCIADO PARA LA DISTRIBUCION' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'FUNDO_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'CULTIVO ASOCIADO PARA LA DISTRIBUCION' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'CULTI_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DISTR COSTOS X LOTE HAS II' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'DTLO2_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FLAG ES OBRA EN CURSO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'FLOEC_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'NUMERO OBR EN CURSO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'NUOEC_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FLAG INDICA SI EL CENTRO DE COSTO ESTA ACTIVO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT03', @level2type=N'COLUMN',@level2name=N'FLACT_T03'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'CODIGO DE CULTIVO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT08', @level2type=N'COLUMN',@level2name=N'CULTI_T08'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'AÑO DE INICIO DE LA CAMPAÑA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT08', @level2type=N'COLUMN',@level2name=N'ANIO__T08'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'CODIGO DE ACUERDO AL CULTIVO Y CAMPAÑA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT08', @level2type=N'COLUMN',@level2name=N'CODIG_T08'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DESCRIPCION DE LA CAMPAÑA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT08', @level2type=N'COLUMN',@level2name=N'DESCR_T08'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'CODIGO AUTOGENERADO DE LA CAMPAÑA' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT08', @level2type=N'COLUMN',@level2name=N'ABREV_T08'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FLAG INDICA SI ESTA ACTIVO O NO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT08', @level2type=N'COLUMN',@level2name=N'ACTIV_T08'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'PERIODO (CAMPO ANTIGUO)' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT08', @level2type=N'COLUMN',@level2name=N'PERIO_T08'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'FLAG INCLUIR EN REPORTES DE PRODUCCION' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'PRT22', @level2type=N'COLUMN',@level2name=N'FLIRP_T22'
GO
USE [master]
GO
ALTER DATABASE [PR] SET  READ_WRITE 
GO
