USE [master]
GO
/****** Object:  Database [RG]    Script Date: 18/02/2023 19:53:26 ******/
CREATE DATABASE [RG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RG', FILENAME = N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\RG.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RG_log', FILENAME = N'D:\MSSQL14.MSSQLSERVER\MSSQL\DATA\RG_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [RG] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RG] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RG] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RG] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RG] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RG] SET ARITHABORT OFF 
GO
ALTER DATABASE [RG] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RG] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RG] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RG] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RG] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RG] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RG] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RG] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RG] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RG] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RG] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RG] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RG] SET RECOVERY FULL 
GO
ALTER DATABASE [RG] SET  MULTI_USER 
GO
ALTER DATABASE [RG] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RG] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RG] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RG] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RG] SET QUERY_STORE = OFF
GO
USE [RG]
GO
/****** Object:  User [COPACABANA\rcervantes]    Script Date: 18/02/2023 19:53:26 ******/
CREATE USER [COPACABANA\rcervantes] FOR LOGIN [COPACABANA\rcervantes] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [COPACABANA\rcervantes]
GO
/****** Object:  Table [dbo].[RGI01]    Script Date: 18/02/2023 19:53:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RGI01](
	[N_GAL_SYSTEM] [int] NULL,
	[D_GAL_TIME] [datetime] NULL,
	[N_GAL_PROGRAM] [float] NULL,
	[N_GAL_VALVE_A] [float] NULL,
	[N_GAL_VALVE_B] [float] NULL,
	[N_GAL_VALVE_C] [float] NULL,
	[N_GAL_VALVE_D] [float] NULL,
	[N_GAL_VALVE_E] [float] NULL,
	[N_GAL_WATER_DONE] [float] NULL,
	[N_GAL_TIME_WATER_DONE] [float] NULL,
	[N_GAL_LAST_FLOW] [float] NULL,
	[N_GAL_LOCAL_FERT_NUM] [float] NULL,
	[N_GAL_FERT_DONE] [float] NULL,
	[N_GAL_LOCAL_FERT_UNIT] [int] NULL,
	[N_GAL_FERT_A_NUM] [float] NULL,
	[N_GAL_FERT_A] [float] NULL,
	[N_GAL_FERT_B_NUM] [float] NULL,
	[N_GAL_FERT_B] [float] NULL,
	[N_GAL_FERT_C_NUM] [float] NULL,
	[N_GAL_FERT_C] [float] NULL,
	[N_GAL_FERT_D_NUM] [float] NULL,
	[N_GAL_FERT_D] [float] NULL,
	[N_GAL_FERT_E_NUM] [float] NULL,
	[N_GAL_FERT_E] [float] NULL,
	[N_GAL_FERT_F_NUM] [float] NULL,
	[N_GAL_FERT_F] [float] NULL,
	[N_GAL_CENTER_FERT_UNIT] [int] NULL,
	[N_GAL_LAST_EC] [float] NULL,
	[N_GAL_LAST_PH] [float] NULL,
	[N_GAL_REQUEST_EC] [float] NULL,
	[N_GAL_REQUEST_PH] [float] NULL,
	[N_GAL_ACUMULATION_SENSOR] [float] NULL,
	[N_GAL_FUNDO] [varchar](50) NULL,
	[VC_GAL_ORIGIN] [varchar](50) NULL,
	[B_GAL_ESTADO] [bit] NULL,
	[D_GAL_DATE_CR] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RGI02]    Script Date: 18/02/2023 19:53:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RGI02](
	[N_GAL_SYSTEM] [int] NULL,
	[D_GAL_TIME] [datetime] NULL,
	[R_GAL_EC] [float] NULL,
	[R_GAL_PH] [float] NULL,
	[R_GAL_T1] [float] NULL,
	[R_GAL_T2] [float] NULL,
	[N_GAL_FUNDO] [varchar](50) NULL,
	[VC_GAL_ORIGIN] [varchar](50) NULL,
	[B_GAL_ESTADO] [bit] NULL,
	[D_GAL_DATE_CR] [datetime] NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [RG] SET  READ_WRITE 
GO
